cmd/relay/p2p.go

Fixes relay connection limit issue in v0.13.0.
category: bug
ticket: none

cmd/relay: fix relay connection limit issue

---

p2p/relay.go

That log line wasn't useful anyway.
ticket: none

p2p: remove pointless "No connections to relay" log line

---

cmd/createcluster.go
dkg/disk.go
dkg/dkg.go
dkg/dkg_internal_test.go
dkg/dkg_test.go
eth2util/deposit/deposit.go
eth2util/deposit/deposit_test.go
tbls/v2/tblsconv/tblsconv.go
tbls/v2/tblsconv/tblsconv_test.go
testutil/random.go

Populates the deposit data field in the generated lock files.
ticket: #1775

dkg: add deposit data to lock file

---

p2p/relay.go

Fixes recursive context wrapping that caused a memory leak.
category: bug
ticket: none

p2p: fix recursive context leak

---

app/app.go
core/interfaces.go
core/tracker/tracker2/tracker.go
core/tracker/tracker2/tracker_internal_test.go
core/tracking.go

Fixes duty expired context in tracker2. This happens when duty is already expired and retryer calls tracker2 with a context which has timed out resulting in closing of ctx.Done() channel. Due to this some events don't get registered in tracker2:
https://github.com/ObolNetwork/charon/blob/eeab76e1f388af478052734eea61803df8f5f38d/core/tracker/tracker2/tracker.go#L741
category: bug
ticket: #1478 
feature_flag: tracker_v2

core: fix duty expired context tracker2 

---

app/metrics.go
app/monitoringapi.go
testutil/compose/static/grafana/dash_charon_overview.json

Adds a constant gauge with label set to the upstream beacon node version. It is refreshed every 10mins. 
Also adds a new panel for beacon node metrics to simnet grafana dashboard.
ticket: #1773

app: add beacon node version metric

---

app/app.go
go.mod
testutil/beaconmock/headproducer.go
testutil/beaconmock/headproducer_test.go
testutil/beaconmock/server.go
testutil/compose/config.go
testutil/compose/run.go
testutil/compose/static/vouch/Dockerfile
testutil/compose/static/vouch/run.sh
testutil/compose/static/vouch/vouch.yml
testutil/random.go

Adds vouch to compose and also made some changes to beaconmock which were needed by vouch specifically.
Note: Vouch doesn't support block proposals because of RANDAO check in go-eth2-client.
ticket: #1403

compose: add vouch to compose

---

app/app.go
app/featureset/featureset.go

`herumi_bls` has been tested in the dev cluster for a while now, works as expected.
This PR moves it as under the stable feature set flag, while flipping the logic around the feature flag presence check: if explicitly disabled, fall back to Kryptology for BLS features.
ticket: #1743 

app: promote `herumi_bls` feature flag to stable

---

core/consensus/msg.go
core/consensus/msg_internal_test.go

Fixes `value hash not found in values` issue when a legacy peer sends you a message containing latest justification which would contain the `ValueHash` while the `values` envelope is empty.
category: bug
ticket: none

core/consensus: swap value vs hash parsing

---

.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/track-pr.yml
.github/workflows/verify-pr.yml
.golangci.yml
.pre-commit-config.yaml
Dockerfile
testutil/promrated/Dockerfile
testutil/random.go

Updates repo to [go1.20.2](https://go.dev/doc/devel/release#go1.20.minor). This fixes failing govuln checks.
ticket: none

*: update to go1.20.2

---

app/eth2wrap/synthproposer.go
core/validatorapi/router.go

Adds proposer index in synthetic blocks which lets lighthouse VC propose synthetic blocks since it checks proposer index: [refer](https://github.com/sigp/lighthouse/blob/319cc61afeb1dbf3692e280dfa18e7b455542b16/validator_client/src/block_service.rs#L398).
Also updates how we return block version in block proposal endpoint which let's us to support block proposals with prysm. 
category: misc
ticket: none

app/eth2wrap: add proposer index in synthetic blocks

---

core/scheduler/scheduler.go

Fixes data race in scheduler.go. 
ticket: none

core: fix data race in scheduler

---

cmd/createcluster.go
cmd/createcluster_internal_test.go

Handle multiple addresses error in `charon create cluster` command for remote definition.
category: bug
ticket: none

cmd/createcluster: handle multiple addresses with remote definition

---

app/k1util/k1util.go
app/k1util/k1util_test.go

Trims newlines when decoding `charon-enr-private-key`.
category: bug
ticket: none

k1util: trim newline when decoding `charon-enr-private-key`

---

Dockerfile

Wget is needed for the container healthcheck as defined here: https://github.com/ObolNetwork/charon-distributed-validator-node/blob/main/docker-compose.yml  
Moved to slim base in commit 8c1dcc6bfa2e4ba1f2db9b54dfaf8a953a43defa but slim image does not include wget anymore, needs to be added.
category: bug
ticket: #1879

dockerfile: fix container healthcheck

---

.pre-commit-config.yaml

Only check minor go-version for pre-commit hooks. Few reasons:
- Homebrew is slow to support latest versions, so it is pain to upgrade.
- Local dev patch versions doesn't matter, only local dev minor versions actually matter.
- Most important is what version we use to build the docker images, that isn't done locally.  
category: misc
ticket: none

precommit: only check major go version locally

---

cmd/createcluster.go
cmd/createcluster_internal_test.go
cmd/createdkg.go
cmd/createdkg_internal_test.go

Fixes split keys bug when there are more than one validator keystore in split keys directory. This creates definition by reading numDVs cluster config struct rather than creating definition with NumValidators equal to the number of keystores in split keys directory which results in mismatch of NumValidators field in lock file with the number of distributed validators created.
Here's an example:
```json
{
"cluster_definition": {
"name": "testobol",
"creator": {
"address": "",
"config_signature": ""
},
"operators": [
{
"address": "",
"enr": "enr:-HW4QN-rWB5a12pbRZHOYa2d1sON6_Cg5rXZ_Ft3Tz6fFfNTU9XMZ7un8W6ZyNtuyBHm2v95YxBjvm--SfVgoNTjqJqAgmlkgnY0iXNlY3AyNTZrMaEDeu6WQMO1sw_-GD6J9y_n3fcI97EyJVCvdvMl4832zGs",
"config_signature": "",
"enr_signature": ""
},
{
"address": "",
"enr": …
```

cmd/createcluster: fix split keys bug for multiple validators

---

go.mod
p2p/metrics.go
p2p/receive.go
p2p/receive_test.go
p2p/sender.go
p2p/sender_internal_test.go

This adds support for wire protocols to upgrade to length delimited wire messages while still supporting current undelimited messages. This allows a smooth upgrade migration.
Note this hasn't been used yet. Will do that in subsequent PRs.
ticket: #1884

p2p: add support for delimited wire protocol upgrades

---

p2p/relay.go

Always ensure active connections to relay. This is required since peers can only connect to you via a relay if you are connected to the relay. This reverts the change introduced in #1816. It also mitigates increase in DKG failures and general "not connected to peer" issues.
category: bug
ticket: #1898

p2p: always ensure relay connection

---

app/app.go
app/simnet_test.go
app/version/version.go
core/consensus/component.go
core/consensus/component_test.go
core/consensus/msg.go
core/consensus/msg_internal_test.go
core/consensus/transport.go

Removes support for backwards compatible duplicate QBFT wire values. Only support "value pointers" in envelope. This decreases QBFT bandwidth by a lot. 
> Note this removes support for v0.13. Only v0.14 is supported.
ticket: #1552

core/consensus: remove support for legacy wire protocol

---

app/obolapi/api.go
app/obolapi/api_test.go

Adds content type header to api post so that it can be understood.
category: bug
ticket: #1906

dkg: add content type to lock file post

---

cmd/createcluster.go
cmd/dkg.go

There were two bugs:
- Config flags were not getting set for publish in dkg because it was not getting passed a reference
- Signature_aggregate was only written at the `writeLock` step of createcluster so was not present when saved to api
category: bug
ticket: #1906

dkg: fixes publish arg and signature_aggregate creation

---

app/app.go
app/app_test.go
cmd/relay/p2p.go
dkg/dkg.go
p2p/p2p.go
p2p/relay.go

Disables the relay's libp2p resource manager so it uses all available resources. Note that the circuitv2 relay resources still apply.
ticket: none

cmd/relay: disable resource manager

---

core/validatorapi/validatorapi.go
dkg/disk.go

Adds an error log to debug `pubkey not found` error.
category: misc
ticket: none

core/validatorapi: add an error log to debug lodestar integration

---

dkg/sync/client.go

This fixes a DKG race deadlock on shutdown. When one `sync/client` is busy "connecting with reconnect=true", it blocks forever trying to reconnect even though the DKG is shutting down an `DisableReconnect` has been called.
category: bug
ticket: #1925

dkg/sync: fix shutdown reconnect deadlock

---

.github/workflows/build-push-deploy.yml

Only allow building docker images from trunk (`main`) or patch (`main/v0.X`) protected branches.
category: misc
ticket: none

github/workflows: only build images for protected branches

---

cmd/combine.go
combine/combine.go
combine/combine_test.go

This PR changes the `combine` command as follows:
- handle relative input paths properly
- make output path explicit with sane defaults
- combine keys in a single directory rather than one directory for each validator
ticket: #1836
Closes #1836.

combine: explicit output directory, new output keystore directory format

---

app/version/version.go

Bumps version to v0.15.0-dev since main/trunk already includes breaking changes from v0.14 and isn't compatible with v0.13 anymore. So this indicates the compatibility is more aligned with v0.15 rather than v0.14. 
category: misc
ticket: none

app/version: bump version to v0.15.0-dev

---

app/app.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
cmd/run.go
docs/configuration.md
go.mod
go.sum
testutil/beaconmock/beaconmock.go
testutil/beaconmock/beaconmock_fuzz.go
testutil/beaconmock/headproducer.go
testutil/beaconmock/options.go
testutil/compose/compose/main.go
testutil/compose/config.go
testutil/compose/lock.go
testutil/compose/testdata/TestDockerCompose_run_template.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden
testutil/compose/testdata/TestNewDefaultConfig.golden

Adds initial PoC for beacon fuzz to fuzz test charon where beacon mock returns random/malicious responses to charon.
ticket: #1848

testutil/beaconmock: initial PoC for beacon fuzz

---

dkg/dkg.go

Logs peer summary at the start of DKG with peer names, ethereum addresses and peer index.
ticket: #1912

dkg: log peer summary at the start of DKG

---

dkg/dkg.go

Improve dkg peer summary logs to omit empty addresses and local peer.
category: misc
ticket: #1912

dkg: improve dkg logs for empty addresses

---

dkg/keycast.go

Fixes race condition in keycast for concurrent write of map.
category: bug
ticket: #1867

dkg: fix race condition in keycast

---

p2p/p2p.go

Guarantees that identify.ActivationThresh is only initialized once, on the first call to NewTCPNode.
category: bug
ticket: #1867

p2p: move ActivationThresh in a sync.Once

---

dkg/exchanger_internal_test.go

Fixes race condition in exchanger test by removing shared slice and using channels.
category: bug
ticket: #1867

dkg: fix race condition in exchanger test

---

app/featureset/config.go
app/featureset/featureset.go

Respect `initMu` locking.
category: bug 
ticket: #1867

app/featureset: fix data race in Enabled

---

core/aggsigdb/memory.go
core/aggsigdb/memory_internal_test.go

Use sync.Map with a thin abstraction for data and keys by duty maps.
category: bug
ticket: #1867

core/aggsigdb: refactor concurrent access issue in test

---

.github/workflows/test.yml
.pre-commit/run_tests.sh

This PR enables execution of Go tests with the race detector enabled.
Also enables it in `pre-commit` tasks.
Let's merge this once all the data races are solved!
ticket: #1867

ci: run tests with `-race` flag

---

p2p/receive_test.go
p2p/sender.go

Disable dynamic length delimited protocol negotation, postponing it until v0.16.0-dev release. 
This is because v0.14 still uses the naive `p2p.ProtocolSupported` which doesn't
support dynamically negotiated protocols. It only supports the static advertised protocols.
Our implementation of the length delimited protocol is dynamically negotiated so not supported
by v0.14. The upcoming v0.15.0 release must be compatible with v0.14.
category: bug
ticket: #1948

p2p: disable dynamic length delimited protocol negotation

---

app/peerinfo/adhoc_test.go
p2p/receive_test.go
p2p/sender.go
p2p/sender_internal_test.go

Fix regression introduced by length-delimited upgrades which assumed that legacy-stream-delimited protocols handled requests and responses the same while it didn't. It allowed zero length requests while it didn't allow zero-length responses. This aligns the new implementation with that.
category: bug
ticket: #1956

p2p: support zero length request protos

---

app/simnet_test.go

Improves simnet test logs to aid debugging flapping tests.
category: test
ticket: none

app: improve simnet test logging

---

.github/workflows/test.yml
app/simnet_test.go

It seems like integration test timeout might be due to tests taking too long to run. So only run explicit integrations tests during the integration test CI step. Prevent other tests from running if `--integration=true`. Also increase timeout. 
category: test
ticket: none

github/workflows: isolate integration tests

---

.github/workflows/test.yml
testutil/integration/doc.go
testutil/integration/helpers_test.go
testutil/integration/infosync_test.go
testutil/integration/ping_test.go
testutil/integration/simnet_test.go

Move `app` tests to `testutil/integration`, increase timeout.
category: test
ticket: none

testutil/integration: move app tests

---

core/parsigex/memory.go
core/parsigex/memory_test.go
testutil/integration/simnet_test.go

Fix race in parsigex mem to wait for all peers to register before broadcasting.
category: test
ticket: none

testutil/integration: fix parsigexmem race

---

cmd/createcluster_internal_test.go

Fix timeouts in `TestPublish` by making the channel buffered.
category: test
ticket: none

cmd: fix publish test timeout

---

.pre-commit/run_tests.sh
dkg/dkg_test.go

Improve DKG `SyncFlow` test to help debugging flapping tests.
ticket: none

dkg: improve sync flow test logs

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_test.go

Fix flapping eth2wrap test by not relying on timeout but rather returning a 500. This allows increasing the timeout since CI/CD server is overloaded and often takes longer than 10ms to connect to valid server.
category: test
ticket: none

app/eth2wrap: improve flapping test

---

README.md

Removes any "testing" language as well as any project status sections, point to `dev.obol.tech` instead. 
category: misc
ticket: #1968

readme: point to dvt.obol.tech for project status

---

dkg/dkg.go

Enables peerinfo server handler in DKG command so nodes identify themselves to relays. This mitigates the "protocol not supported errors" in the relay when DKG happens.
category: bug
ticket: #1978

dkg: enable peerinfo server

---

cmd/createcluster.go
cmd/createcluster_internal_test.go
cmd/createdkg_internal_test.go

Change `charon create cluster` and `charon create dkg` to default to mainnet. This mitigates the risk of users thinking they generated a mainnet cluster and activiting it, while the actually created a testnet cluster.
ticket: #1969

cmd: change to mainnet by default

---

eth2util/rlp/rlp.go
eth2util/rlp/rlp_test.go

Add fuzz tests to `eth2util/rlp` as identified by sigma-prime audit.
Fixes OBOL-04.
category: bug
ticket: none

eth2util/rlp: add fuzz tests

---

cluster/test_cluster.go
cmd/combine/combine_test.go
dkg/disk.go
dkg/dkg.go
dkg/dkg_test.go

Improve test speed by using `insecure` keystores.
category: test
ticket: none

*: speed up keystore tests

---

testutil/beaconmock/headproducer_internal_test.go

Speed up head producer tests by not relying on normally scheduled slots (minimum is 1s), rather refactor to internal tests and update head very fast.
category: test
ticket: none

testutil/beaconmock: speed up head producer tests

---

cmd/createcluster.go
cmd/createcluster_internal_test.go
dkg/dkg_test.go
dkg/transport.go
eth2util/keymanager/keymanager_test.go
eth2util/keystore/keystore_test.go
testutil/integration/simnet_test.go

Speed up tests using `keystore` by using insecure keys.
category: test
ticket: none

keystore: speed up tests

---

cmd/combine/combine.go
cmd/combine/combine_test.go

Allow `combine` package tests to override keystore with insecure keys for snappier tests.
category: test
ticket: none

cmd/combine: add support for insure keys in tests

---

app/metrics.go
app/monitoringapi.go
app/monitoringapi_internal_test.go
testutil/compose/static/grafana/dash_charon_overview.json

Adds "BeaconNode far behind" metric value to `/readyz`. This would help node operators to monitor their beacon node health if the `Healthy` panel shows `BeaconNode far behind` for a longer time.
ticket: #1967

app: add beacon node far behind metric value to readyz

---

core/scheduler/scheduler_test.go
go.mod
go.sum

Upgrade `github.com/jonboulle/clockwork` from `v0.3.0` to  `v0.4.0` . Also fix test.
category: misc
ticket: none

gomod: upgrade clockwork to v0.4.0

---

p2p/relay.go

Increase the relay reserve "check if connected" frequency to be more sensitive to failing relay connections so it reconnects quicker. 
category: misc
ticket: none

p2p: increase relay reserver check freq

---

cmd/relay/p2p.go

Increases relay circuit limit from 2m to 1h. This should improve sporadic relay networking issues due to recycling of connections resulting in more stable networking. Note this doesn't solve any problems, it just reduces probabilities.
Also increase buffer size for snappier relay throughput.
category: misc
ticket: none

cmd/relay: increase relay connection limit

---

dkg/dkg.go
dkg/frostp2p.go

Addresses OBOL-01, closes #1999.
category: bug
ticket: #1999

dkg: ensure number of commitments

---

cmd/dkg.go
dkg/dkg.go
dkg/dkg_test.go

Workaround for the DKG shutdown race issue described in #887. Instead of immediately shutting down after writing artefacts to disk, wait for 1s by default, allowing other peers to also write their artefacts to disk before disconnecting. 
This issue doesn't happen in production that often due to +100ms latency between peers that allow peers to write artefacts to disk before peer disconnects are detected. This does however occur in unit tests and compose tests and could occur in local network DKGs.
category: bug
ticket: #887

dkg: shutdown race workaround

---

p2p/p2p.go

Add libp2p disconnect debug logs to aid debugging relay issues. 
category: misc
ticket: none

p2p: add disconnect logs

---

p2p/relay.go

Fix relay connection check, should by regular ticker, not once off timer.
category: bug
ticket: none

p2p: fix relay conn checker

---

testutil/compose/compose/main.go
testutil/compose/define.go

Add a `build-local` command to `compose` to support running new source code without regenerating the whole compose cluster.
category: misc
ticket: none

testutil/compose: add build-local command

---

app/version/version.go

Bumps main/trunk version to `v0.16.0-dev`.
category: misc
ticket: none

version: bump version to v0.16.0-dev

---

.github/workflows/codeql-analysis.yml

Ensures `codeql` checks also run against release branch commits and PRs.
category: misc
ticket: none

github/workflows: include release branch in codeql

---

app/version/version.go

Bumps version to `v0.15.0-rc1`
category: misc
ticket: none

version: bump version to v0.15.0-rc1

---

.github/workflows/build-push-deploy.yml

Removes the `Build and Publish Docker Image` action's "branch check" logic, since one cannot easily map a tagged commit to a branch. Can worry about this later. For now we need to remove the check so that docker tagged images are built for release branch git tags.
category: misc
ticket: none

github/workflows: remove release branch check

---

.github/workflows/build-push-deploy-promrated.yaml
.github/workflows/build-push-deploy.yml

Improves docker image tagging rules.
charon:
- always tag `short sha`
- only tag `latest` on main branch commits (not on `v0.X` tags)
- only tag `git tag value` on git tag events
promrated:
- always tag `short sha`
- always tag `latest`
category: misc
ticket: none

github/workflows: improve docker image tagging rules

---

core/scheduler/scheduler.go
core/tracker/incldelay.go

Unlock mutex before doing any i/o in core/tracker/incldelay.go.
category: bug
ticket: #2028

core/tracker: unlock mutex

---

app/app.go
app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/eth2wrap_test.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/lazy.go
core/scheduler/scheduler_test.go

Fix eth2wrap lazy client when http requests block/timeout. Also respect context cancel while lazy resolving.
category: bug
ticket: none

app/eth2wrap: fix lazy client if http times out

---

core/consensus/component.go
core/consensus/component_internal_test.go

Check that:
- there is a pubkey for the message peerIdx
- justification messages are not nil
- there is a public key for the justification peerIdx
Add a test case to assert that those properties hold.
Fixes OBOL-06.
category: bug
ticket: none

core/consensus: stricter checking on ConsensusMsg

---

core/deadline_test.go

Fixes flappy deadliner test. Looks like clockwork.FakeClock is not thread safe. Found out while debugging we were calling `clock.Advance` in deadline_test and `setCurrState` in deadline.go at the same time.
category: test
ticket: #1721

core/deadliner: fix deadliner flappy test

---

.github/workflows/label-pr.yml

Automatically add labels to PRs that are not on main branch. This makes it obvious and clear if PRs are non-standard.
category: misc
ticket: none

github/workflows: add a branch labeler

---

app/monitoringapi.go

Fixes peer count beacon node query to occur every min instead of every 10s. 
Also, fixes it to query only once since we query this both in `startReadyzChecker()` and `beaconNodeMetrics()` and set the `beaconNodeVersionGauge` in `startReadyzChecker` instead.
category: misc 
ticket: none

app: fix peer count bn query to occur every min instead of every 10s

---

app/app.go
p2p/metrics.go

Enable libp2p built-in bandwidth metrics reporting in `charon run`.
ticket: none
cherry-pick: #2050

app: enable libp2p bandwidth metrics

---

testutil/verifypr/verify.go
testutil/verifypr/verify_internal_test.go

Limit PR titles to 60 chars. This drives the use of succinct PR titles and more verbose bodies. Commit and PR titles should be glanceable. It should be easy to glance over a long list of PRs and quickly identify and find things "at a glance". This requires short titles. Details about what changed, the types involved, the constants changed all need to be in the body. 
category: misc
ticket: none

testutil/verifypr: limit PR titles to 60 chars

---

.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/track-pr.yml
.github/workflows/verify-pr.yml
.golangci.yml
Dockerfile
testutil/promrated/Dockerfile

Addresses recent CVEs detected by govulncheck.
category: misc
ticket: none

workflows: update Go to 1.20.3 on v0.15 release branch 

---

core/sigagg/sigagg.go
core/sigagg/sigagg_test.go

Adds check to `sigAgg` so that it returns an error when `Aggregate()` is called with less than `threshold` number of unique partial signatures.
category: bug 
ticket: https://github.com/ObolNetwork/charon/issues/2053

sigagg: validate threshold unique partial signatures

---

core/fetcher/fetcher.go
core/fetcher/fetcher_test.go

Dedup aggregate attestations in fetcher for aggregators of same committee. This solves `clashing aggregated attestation` error in dutydb in case of different aggregate attestations for aggregators of same committee.
category: bug
ticket: none

core/fetcher: dedup aggregate attestations

---

core/tracker/tracker.go

Initialise participation metrics to 0 to avoid non-existent metrics issue on startup.
category: misc
ticket: none

core/tracker: initialise participation metrics

---

eth2util/deposit/deposit.go
eth2util/deposit/testdata/TestMarshalDepositData.golden

Updates `deposit_cli_version` to `2.5.0`.
category: misc
ticket: https://github.com/ObolNetwork/charon/issues/2067

eth2util: update deposit cli version

---

eth2util/enr/enr.go
eth2util/enr/enr_test.go

Adds a check when duplicate keys are found in ENR parsing. Also adds tests.
category: bug 
ticket: #2054

enr: fix duplicate keys in enr parsing

---

core/tracker/metrics.go
core/tracker/tracker.go

Adds a `missed participation by peer` counter so that we can calculate `duty participation % per peer` and so we can highlight missed participations instead of only successful participations.
category: misc
ticket: #2034

core/tracker: add missed participation counter

---

.github/workflows/build-push-deploy.yml
.github/workflows/deploy-relay-dev.yml
.github/workflows/deploy-relay-prod.yml

Fix formatting and input
category: bug
ticket: #2031

github/workflows: fix multi line formatting

---

core/tracker/metrics.go
core/tracker/tracker.go

Adds success/failure/expected counters for both peer participation and overall duty. This allows improving our dashboard to show duty and participation percentage success/failure with simple queries.
category: misc
ticket: #2034
cherry-pick: #2080

core/tracker: ensure success/fail/expected counters

---

core/tracker/tracker.go
core/tracker/tracker_internal_test.go
testutil/random.go

Improves ignoring of unsupported duties, so ignore for both failure and participation logs and metrics. Also fix edge case mentioned in #1348 where aggregation duties succeeded and then later fails.
category: bug
ticket: #1348

core/tracker: improve ignoring of unsupported duties

---

dkg/dkg.go
dkg/frostp2p.go

Adds nil pointer checks for relevant functions in dkg package.
Refer: OBOL-03
category: misc
ticket: #1997

dkg: add nil checks

---

eth2util/rlp/rlp.go
eth2util/rlp/rlp_internal_test.go

Fixes bug in RLP `decodeLength()` by ensuring that calculations of length should use units of bytes instead of bits.
category: bug 
ticket: #2076

rlp: fix bug in decodeLength

---

go.mod
testutil/beaconmock/headproducer_internal_test.go

Remove `gopkg.in/cenkalti/backoff.v1` direct dependency by removing its usage in `headproducer_internal_test.go`. Though it is still present as an indirect dependency since `sse/v2` uses it.
ticket: https://github.com/ObolNetwork/charon/issues/2083

beaconmock: remove backoff dependency

---

core/parsigex/parsigex.go
core/priority/component.go
core/proto.go
core/proto_test.go

Adds nil checks before reading proto messages in core package mentioned in audit report.
Refer: OBOL-03
category: misc
ticket: #1997

core: add nil checks

---

app/app.go
app/featureset/featureset.go
core/consensus/component.go
core/consensus/component_test.go
core/consensus/roundtimer.go
core/consensus/roundtimer_internal_test.go
core/consensus/sniffed_internal_test.go

Introduces alpha feature `QBFTDoubleLeadTimer` that attempts to address sporadic consensus timeouts on block proposals by doubling round timers on receive justified pre-prepare for the current round.
ticket: #2092

core/consensus: double lead time alpha feature

---

app/forkjoin/forkjoin.go
core/consensus/strategysim_internal_test.go

Implements a basic consensus simulator using a fake clock that is able to check succesful consensus given different network latencies, start times, and round timers. Next step is to expand it into a benchmark to compare different round timer implementations.
category: test
ticket: none

core/consensus: implement simulator test

---

app/app.go
core/scheduler/scheduler.go
core/tracker/incldelay.go
core/validatorapi/validatorapi.go
testutil/beaconmock/beaconmock_fuzz.go
testutil/compose/fuzz/beacon_fuzz_test.go

Fixes panics found by initial beacon fuzz tests. Also improve efficiency of beacon fuzzer to trigger more panics in charon workflow.
category: test
ticket: #1962

testutil/beaconmock: fix fuzz issues

---

dkg/dkg.go
dkg/frostp2p.go
dkg/frostp2p_internal_test.go

Adds check to ensure validator indexes (`ValIdx`) in frost DKG messages are in the range `[0, num_validators)`.
Also refactors out broadcast and p2p callbacks and adds tests for them.
ticket: #1888

dkg: verify valIdx in frost dkg messages

---

testutil/compose/smoke/smoke_test.go
testutil/compose/static/vouch/Dockerfile

Adds a smoke test which uses vouch as VC.
category: misc
ticket: none

compose/smoke: add vouch in smoke tests

---

core/tracker/tracker.go
core/tracker/tracker_internal_test.go

Improves participation metric to count multiple duties per slot. For example, we can have multiple attester duties per slot.
ticket: #2034

core/tracker: improve participation

---

app/log/config.go
core/consensus/strategysim_internal_test.go

Improve consensus round timer silmulator test.
ticket: #2117

core/consensus: improve simulator test

---

app/app.go
core/fetcher/fetcher_test.go
core/interfaces.go
core/tracker/inclusion.go
core/tracker/inclusion_internal_test.go
core/tracking.go
testutil/random.go

When checking attestation and aggregation inclusion, check whether our submissions's aggbits are included in the block attestation aggbits. Also fix matching using attestation data root (not attestation root which changes on additional aggregation). 
ticket: #1538

core/tracker: check aggbits for inclusion

---

app/app.go
app/disk_internal_test.go
app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/httpwrap.go
app/eth2wrap/lazy.go
app/eth2wrap/synthproposer.go
app/eth2wrap/synthproposer_test.go
app/eth2wrap/valcache.go
app/eth2wrap/valcache_test.go
app/vmock.go
core/scheduler/scheduler.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go
testutil/validatormock/attest.go
testutil/validatormock/synccomm.go
testutil/validatormock/validatormock.go
testutil/validatormock/validatormock_test.go

This is a second attempt at caching active validators. Instead of caching the `eth2client.ValidatorProvider` endpoints which return full `Validator` objects that are not actually immutable by epoch, rather implement a new set of client endpoint specifically for cached immutable active validators by current epoch that only return the validator index and pubkey which are immutable. The only race condition is the fact that we query this by "head", so could be for another slot that what we think is current, although this was already the case previously, so no new races are introdcued.
This should significantly decrease BN load, especially if using the validatormock.  
ticket: #1396

app/eth2wrap: implement and wire validator cache

---

app/app.go
app/featureset/featureset.go
core/consensus/component.go
core/consensus/component_test.go
core/consensus/metrics.go
core/consensus/roundtimer.go
core/consensus/roundtimer_internal_test.go
core/consensus/strategysim_internal_test.go

Refactors the timer selection alpha feature to AB test 3 different timers using a round-robin selection. This allows much better 1-to-1 comparison using metrics.  Note this introduces a 3rd timer, the exponential timer that the simulator showed is very robust and as performant as the increasing timer.
ticket: #2092

core/consensus: refactor alpha timer AB testing

---

app/app.go
core/sigagg/sigagg.go
core/sigagg/sigagg_test.go
core/signeddata.go

Verify reconstructed aggregated signature.
Fixes OBOL-17 of sigp audit.
ticket: #2122

core/sigagg: verify aggregated signature

---

app/monitoringapi_internal_test.go

Increases tick frequency to 1ms to fix flapping test in monitoringapi.
Now the condition is checked every 1ms in a 1s window, ie, 1000 times in a second. This should fix the flapping behaviour.
ticket: #2125

app: fix flapping test

---

core/consensus/component.go
core/consensus/sniffed_internal_test.go
core/consensus/strategysim_internal_test.go
core/qbft/qbft.go
core/qbft/qbft_internal_test.go

Adds support for lazy QBFT input values that are not necessarily provided at the start of the instance. Next step is to add support for this consensus component.
ticket: #928

core/qbft: add support for lazy input values

---

core/consensus/component.go
core/consensus/component_internal_test.go
core/consensus/roundtimer.go
core/consensus/transport.go
core/interfaces.go
core/leadercast/leadercast.go
core/retry.go
core/tracing.go
core/tracking.go

Adds support for eager consensus if timer contains `eager` substring. This starts consensus via scheduler without waiting for fetcher.  
ticket: #928

core/consensus: add support for eager consensus

---

.pre-commit-config.yaml
.pre-commit/run_testutil.sh
app/app.go
app/vmock.go
tools.go

Extend the `run_regexp.sh` linter to check for `testutil` imports in any non-test package.
category: misc
ticket: #1683

precommit: lint importing of testutil

---

core/tracker/inclusion.go

Add debug logs to aid debugging false negative inclusion checks. 
category: bug
ticket: #2130

core/tracker: add inclusion missed debug logs

---

cmd/combine/combine.go
cmd/combine/combine_test.go
eth2util/keystore/keystore.go
eth2util/keystore/keystore_internal_test.go
eth2util/keystore/keystore_test.go

Fixes an error in `cmd/combine` where the i'th combined key was different than expected one if the amount of validator in the lock file is greater than 10.
`filepath.Glob()` orders its input in lexicographical order, so that the following output is obtained:
```
├── keystore-insecure-0.json
├── keystore-insecure-0.txt
├── keystore-insecure-1.json
├── keystore-insecure-1.txt
├── keystore-insecure-10.json
├── keystore-insecure-10.txt
├── keystore-insecure-2.json
├── keystore-insecure-2.txt
```
In this instance, keystore 10 comes before keystore 2.
`cmd/combine` uses the lock file keys order to orchestrate its logic and given the mismatch between that and the `LoadKeys()` output, a key mismatch error will result: `combine` expected key at index 2 to be what's contained in …

eth2util/keystore: order keystores by index

---

eth2util/signing/signing_test.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go

Simple unit test demonstrating that DomainApplicationBuilder uses genesis fork version domain.
category: test
ticket: none

eth2util/signing: add constant genesis domain test

---

app/app.go
cmd/cmd.go
cmd/combine/combine.go
cmd/create.go
cmd/createdkg.go
cmd/run.go
dkg/dkg.go
main.go

Improve all command fatal error logs:
- Remove duplicates
- Use app/log to print errors, so structured fields are included.
- Only show usage on flag parsing errors.  
Also improve `combine` mismatch error logs.
category: misc
ticket: #2151

cmd: improve error logs

---

eth2util/keystore/keystore.go

Miga Labs testing revealed that loading a huge amount of keys (1000 in their case) takes an unbearable amount of time.
Manual debugging with a similar amount of secure keys also revealed that writing them is slow.
Use `errgroup` to make the reading/writing process concurrent, utilising as much host resources as possible, reducing the time needed to execute those operations.
ticket: none

eth2util/keystore: concurrently read/write keystore files

---

app/genssz/genssz.go
app/genssz/template.go
app/genssz/testdata/example.go
app/genssz/testdata/ssz_gen.go
app/genssz/types.go

Add support for optional transform functions when auto-generating ssz hashing. This allows transformation of `time.Time` into `uint64` by specifying `ssz:"uint64,Unix"` which would result in `uint64(m.Timestamp.Unix())`.
Also skip structs with tags but without ssz tags.
category: misc
ticket: none

app/genssz: support transform funcs

---

cmd/relay/relay_internal_test.go
core/consensus/component_test.go

Fixes flapping test when binding to port fails sporadically. 
category: test
ticket: none

cmd/relay: properly skip test on bind issue

---

cluster/state/load.go
cluster/state/materialise.go
cluster/state/mutation.go
cluster/state/mutationlegacylock.go
cluster/state/mutationlegacylock_test.go
cluster/state/types.go

Implement a basic materialise logic as well as loading either a legacy lock or raw DAG from disk.
ticket: #1886

cluster/state: implement load and materialise

---

.github/workflows/long-wait-dkg.yml
app/privkeylock/privkeylock.go
testutil/integration/longwait_dkg_test.go

Adds github workflow which runs long wait DKG test once a day at 12 noon.
ticket: #1971

*: cron job for long wait dkg

---

cluster/test_cluster.go
tbls/herumi.go
tbls/tbls.go
tbls/tbls_test.go

Adds support for deterministic tbls key generation for use in golden file tests.
category: test
ticket: none

tbls: support deterministic key gen for testing

---

app/genssz/template.go
app/genssz/testdata/example.go
app/genssz/testdata/ssz_gen.go

Supports transform functions for composite list types. This aims to support SSZ hashing of `[][]byte` via simple `[]sszPubkey `ssz:"CompositeList[256],toSSZ"` custom type and override.
category: misc
ticket: none

app/genssz: transforms for composite list types

---

core/validatorapi/router.go
core/validatorapi/router_internal_test.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
testutil/beaconmock/options.go
testutil/random.go

Adds support to get all validators from validatorapi if no validator index or pubkey is provided. This issue came up while testing with prysm VC which needs to query beacon node to get the information of total validators active on beacon chain.
Refer: https://github.com/prysmaticlabs/prysm/blob/5c00fcb84ffef6e85d3d105d7288281ae44b44b2/validator/client/wait_for_activation.go#L139
category: misc
ticket: none

core/validatorapi: get all validators

---

app/app.go
core/dutydb/memory.go

Don't wrap old, nil error when a lockfile fork mismatch one is being created.
ticket: none

app: refactor lockfile fork version mismatch error

---

app/featureset/featureset.go
cmd/dkg.go
dkg/dkg.go
dkg/dkg_test.go
dkg/exchanger.go
eth2util/registration/registration.go
eth2util/registration/registration_test.go

This functionality lives behind the `pregen_validator_registrations` feature flag.
This PR is only concerned with the DKG pre-generation section of the design document (https://docs.google.com/document/d/1lCYiEv7JmVYymp4CBrEvExj3WNmSqWVvZwl9dwATCmA/edit#).
A follow-up PR will implement the lock file changes and wire it accordingly.
ticket: #2172 
feature_flag: pregen_registrations

dkg: pre-generate validator registration messages

---

dkg/dkg_test.go
eth2util/keystore/keystore.go

Avoids resource exhaustion due to high amount of validators to be read/written concurrently.
category: bug
ticket: none

eth2util/keystore: finite amount of goroutines in read/write

---

.github/workflows/nightly-dkg.yml
cmd/dkg.go
dkg/dkg.go
dkg/dkg_test.go
testutil/integration/nightly_dkg_test.go

Also rename longwait_dkg_test.go to nightly_dkg_test.go, since it contains more than a DKG long-wait test.
category: test
ticket: none

testutil/integration: add DKG test with 5000 validators 

---

p2p/receive_test.go
p2p/sender.go

Enables length delimited protocol negotiation in upcoming v0.16. 
This was delayed in v0.15, so enabling now, see https://github.com/ObolNetwork/charon/pull/1954.
ticket: https://github.com/ObolNetwork/charon/issues/1884

p2p: enable delimited protocol negotiation

---

cluster/examples/cluster-definition-004.json
cluster/version.go
cmd/createcluster.go
cmd/createcluster_internal_test.go
dkg/dkg.go
dkg/dkg_test.go
eth2util/registration/registration.go

Generate validator builder registrations when running `charon create cluster` manually.
ticket: #2172

cmd: generate validator builder registrations

---

core/consensus/roundtimer.go
core/consensus/roundtimer_internal_test.go

Refactors the roundtimer AB testing candidates: Just the legacy `inc` and the new `eager_dlinear`. This is after simulation benchmarking showed that the following timer would work best:
- `eager`, so start times are aligned between all nodes.
- `double`, doubles round times if pre-prepare is detected (extended round with valid leaders).
- `linear`, 1s, 2s, 3s, which means 4 round in 10s, which should be enough for almost all clusters.
ticket: #2117

core/consensus: change round AB test timers

---

core/consensus/component_test.go
core/qbft/qbft_internal_test.go

Add a qbft component test for different cluster sizes and count of offline nodes, including 2 of 3. This shows that a 2of3 cluster works, even though it isnt' BFT.
category: test
ticket: none

core/consensus: add 2 of 3 test

---

app/app.go
app/lifecycle/order.go
app/lifecycle/orderstart_string.go
cmd/relay/p2p.go
p2p/p2p.go

Force direct connection when there is an existing relay connection to the peer.
ticket: #2114

p2p: force direct connections

---

p2p/p2p.go
p2p/ping.go

The Ping service was reporting wrong latencies. This is because the ping service creates a long lived stream to the peer using the relay connection. It uses relay connection to report metrics even if direct connection is now available. This is resolved by using new stream/connection for each ping.
category: bug
ticket: none

p2p: use direct connection for ping

---

.github/workflows/build-push-deploy.yml
Dockerfile
app/version/version.go

Sets the app/version.Version variable to the git tag when building tagged docker images. 
category: misc
ticket: #2097

github: overwrite version with tagged releases

---

.github/workflows/build-push-deploy.yml

Tags the docker image with additional "branch version" when building from branch commits. Also only tag "latest" from main not release branches.
category: misc
ticket: #2098

github: tag image with branch version

---

cmd/createcluster.go
cmd/createdkg.go
cmd/createdkg_internal_test.go
cmd/testdata/TestCreateCluster_goerli_files.golden
cmd/testdata/TestCreateCluster_goerli_output.golden
testutil/compose/smoke/smoke_test.go

Decreases the minimum number of nodes to 3 so we can test this scenario. 
Also fix matrix smoke test.
category: misc
ticket: none

cmd: reduce minimum nodes to 3

---

eth2util/network.go
eth2util/network_test.go

Removes ropsten from supported networks as it is already [deprecated](https://blog.ethereum.org/2022/06/21/testnet-deprecation) by the EF in Q4'22.
category: misc
ticket: none

eth2util: remove ropsten from supported networks

---

cluster/version.go
cmd/createcluster_internal_test.go
dkg/dkg_test.go

Moves v1.7.0 of cluster version to draft and makes v1.6.0 current version.
category: misc
ticket: #2246

cluster: move v1.7.0 to draft

---

core/scheduler/scheduler.go

Fixes data race in `scheduler`.
The data race was identified in one of our integration test runs - https://github.com/ObolNetwork/charon/actions/runs/5112385783/jobs/9190355166?pr=2240#step:5:4209.
category: bug 
ticket: none

core/scheduler: fix race

---

cmd/createcluster.go
cmd/createcluster_internal_test.go

Makes `charon create cluster` command feature-complete with regards to `charon dkg` execution output.
ticket: #2204

cmd: add NodeSignatures to create cluster

---

p2p/p2p.go
p2p/ping.go

Close existing streams after each ping. This solves the errors from ping service `stream scope not attached to a protocol` which was caused by creating new streams for each ping and NOT closing them.
Note: We need to test this on our core team cluster.
category: bug
ticket: #2259

p2p: close existing ping streams

---

app/app.go
app/privkeylock/privkeylock.go
app/privkeylock/privkeylock_internal_test.go
dkg/dkg.go
dkg/dkg_test.go

Block `dkg` exit until `privkeylock.Run()` enclosing goroutine exits, ensuring that the private key lock file is always deleted.
`Run()` is supposed to be executed in a goroutine, and since we can't control the scheduler it might be scheduled *after* the `main` one exits, leading to the `ctx.Done()` code path to sometimes never be executed.
category: bug
ticket: #2258

dkg: sync privkeylock before exiting

---

cluster/version.go
dkg/dkg_test.go

Make v1.7.0 cluster config version default.
category: misc
ticket: none

cluster: release config version v1.7.0

---

testutil/integration/nightly_dkg_test.go

Nightly tests are sometimes not able to be executed in 1h30m, so we're dropping them to 700.
category: test
ticket: #2239

testutil/integration: 700 validators in nightly

---

Dockerfile

Prints the built version inside the docker file to debug incorrect tagged versions.
category: misc
ticket: #2270

dockerfile: print built version

---

testutil/integration/nightly_dkg_test.go

Nightly tests are still timing out, try with 200 validators now.
category: test
ticket: #2239

testutil/integration: drop down to 200 validators

---

.github/workflows/build-push-deploy.yml
Dockerfile

Also use `-a` flag to force rebuild when setting `-ldflags` when overriding tagged versions. 
Since `-ldflags=-X path/to/package.Var=foo` contains a space inside the value, the only way I could get this to work is to provide it via an additional `GO_BUILD_FLAG_2` variable. The other option would be wrangling arrays and splitting using something like `IFS=' ' read -ra BUILD_ARGS <<< "$OPTIONAL_BUILD_ARGS"` but I feel this is more verbose but simpler to understand.
category: misc
ticket: #2270

github: set -a when building with flags

---

.github/workflows/build-push-deploy.yml
Dockerfile

Fixes the github action "build-push-deploys" `build-args` parameter. It is a [list parameter that is new line delimited](https://github.com/docker/build-push-action#inputs).
Also remove `-a` build arg since it isn't required. Make it explicit that `GO_BUILD_FLAG` only supports a single flag.
category: misc
ticket: #2270

github: fix build push build arg format

---

docs/metrics.md
p2p/metrics.go
p2p/p2p.go
p2p/ping.go

Adds a Prometheus metric to track the opened streams by protocol.
category: bug
ticket: #2277

p2p: add stream counter metric

---

cmd/addvalidators.go
cmd/addvalidators_internal_test.go
cmd/alpha.go
cmd/cmd.go

Adds `charon alpha add-validators-solo` command to `cmd` package. It doesn't contain the actual functionality for adding validators.
ticket: #1887

cmd: add charon alpha add-validators-solo command

---

app/app.go
cmd/relay/p2p.go

Disable resource manager in charon to avoid `resource limit exceeded` error from libp2p.
category: misc
ticket: #2277

app: disable resource manager

---

app/app.go
app/monitoringapi.go
app/peerinfo/peerinfo.go
app/promauto/resetgauge.go
app/promauto/resetgauge_test.go
cmd/relay/p2p.go
core/scheduler/metrics.go
docs/metrics.md
p2p/metrics.go
p2p/p2p.go

Cherry picks the following PRs from main:
- #2278 
- #2289 
- #2290 
category: bug
ticket: #2277

app: add p2p stream metric and disable resource manager

---

.github/workflows/build-push-deploy.yml
app/app.go
app/metrics.go
app/peerinfo/adhoc_test.go
app/peerinfo/metrics.go
app/peerinfo/peerinfo.go
app/peerinfo/peerinfo_internal_test.go
app/peerinfo/peerinfo_test.go
app/version/version.go
app/version/version_internal_test.go
app/version/version_test.go
cmd/version.go
core/fetcher/fetcher.go
core/infosync/infosync.go
core/validatorapi/validatorapi.go
dkg/dkg.go
dkg/sync/client.go
dkg/sync/server.go
dkg/sync/sync_test.go
docs/metrics.md
p2p/p2p.go
testutil/compose/smoke/smoke_test.go

Instrument whether peer versions are supported or not.
Introduces a `version.SemVer` type to avoid string wrangling.
ticket: #2293

app/peerinfo: instrument version compatibility

---

cmd/createcluster.go

Fixes flag description for `--nodes` in `charon create cluster` command.
category: bug 
ticket: none

cmd: fix flag description

---

app/app.go
core/interfaces.go
core/tracker/inclusion.go
core/tracker/inclusion_internal_test.go
core/tracker/reason.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go
docs/reasons.md

Extends tracker duty failure reasons to include "chain inclusion" results. Duties will subsequently only be marked as success if included onchain, and accordinlgy marked as failed if not included onchain.
Note that chain inclusion is only checked if the duty was broadcasted, so this doesn't actually "make duty failures objective", since if the local node failed to broadcast, it will not check inclusion and will mark the duty as failed regardless of actual results.
ticket: #2200

core/tracker: track inclusion events

---

cmd/createcluster.go

Revert default `create cluster` size from 3 to 4 as 3 is not BFT.
ticket: none

cmd: fix default create cluster size

---

cmd/createcluster.go

Revert default create cluster size from 3 to 4 as 3 is not BFT.
ticket: none
cherry-picks: #2303

cmd: fix create cluster default size

---

cmd/createcluster.go

Fixes the minimum number of nodes in the `create cluster` `--nodes` flag description.
category: misc
ticket: none
cherry-picks: #2301

cmd: fix create cluster node flag decsription

---

cmd/createcluster.go
cmd/createdkg.go

Remove deprecated networks `kiln` & `ropsten`.
category: misc
ticket: #1633

cmd: remove deprecated networks

---

testutil/compose/config.go
testutil/compose/docker-compose.template
testutil/compose/run.go
testutil/compose/smoke/smoke_test.go
testutil/compose/template.go
testutil/compose/testdata/TestDockerCompose_define_create_template.golden
testutil/compose/testdata/TestDockerCompose_define_create_yml.golden
testutil/compose/testdata/TestDockerCompose_define_dkg_template.golden
testutil/compose/testdata/TestDockerCompose_define_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_lock_create_template.golden
testutil/compose/testdata/TestDockerCompose_lock_create_yml.golden
testutil/compose/testdata/TestDockerCompose_lock_dkg_template.golden
testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_run_template.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden
testutil/compose/testdata/TestNewDefaultConfig.golden

Disable visualisation services in smoke tests. It includes grafana, loki and jaegar.
ticket: none

compose: disable visualisation in smoke tests

---

core/tracker/inclusion.go

Reports inclusion events for synthetic blocks to tracker component. Prior to this, tracker was reporting duty failures for synthetic blocks with the following log:
```
WARN tracker    Duty failed: bug: missing chain inclusion event {"step": "bcast", "reason": "unknown error", "reason_code": "unknown", "duty": "5859001/builder_proposer"}
```
category: bug
ticket: none

core/tracker: report inclusion events for synthetic blocks

---

core/consensus/msg.go
core/priority/prioritiser.go

Add remaining nil checks that were missing as part of OBOL-03.
category: misc
ticket: #1997

core: add remaining nil checks

---

cluster/manifest/load.go
cmd/addvalidators.go
cmd/addvalidators_internal_test.go

Writes cluster updated by `charon alpha add-validators-solo` command to disk. The new file is named `cluster-manifest.pb`.
ticket: #1887

cmd: write cluster manifest to disk

---

app/vmock.go
testutil/validatormock/synccomm.go

Refactors validator mock logic to error when state already set (instead of panic). Also use explicit slot/poch to store stateful objects, rather then implicit "last slot" since out of order slot scheduling should cause problems. 
category: test
ticket: #2347

testutil/validatormock: error instead of panic

---

app/peerinfo/adhoc.go
app/peerinfo/peerinfo.go
core/consensus/component.go
core/consensus/transport.go
core/parsigex/parsigex.go
core/priority/prioritiser.go
dkg/bcast/client.go
dkg/bcast/server.go
dkg/frostp2p.go
p2p/receive_test.go
p2p/sender.go

Removes support for legacy stream delimited libp2p protocols. Only support length-delimited protocols.
ticket: #1934

p2p: remove support for legacy stream delimited protocols

---

cmd/combine.go
cmd/combine/combine.go
cmd/combine/combine_test.go

This flag warns the user if any of the cluster manifest files fail hash verification.
It behaves like exactly like `charon run --no-verify`.
The code will not stop if a diverging set of validator keys is present in the cluster manifests, but will error if not all public keys yielded by the combined private keys are present in the validator keys set.
ticket: #2321

combine: add support for `--no-verify`

---

core/tracker/inclusion.go
core/tracker/inclusion_internal_test.go
core/tracking.go

Submit inclusion check regardless the outcome of broadcasting, since even though we might fail to broadcast, peers may have succeeded. 
This is mostly the case in blinded beacon blocks since only a single peer will have the original builder connected.
Also make `inclTracker.Submitted` idempotent, since it may now be called multiple times on retries.
category: bug
ticket: none

core: increase inclusion checks

---

app/app.go
app/disk.go
cluster/manifest/load.go
cluster/manifest/load_test.go
cluster/manifest/mutationlegacylock_test.go
cmd/addvalidators.go
cmd/addvalidators_internal_test.go
cmd/cmd_internal_test.go
cmd/combine/combine.go
cmd/run.go
docs/configuration.md

Loads cluster either from `cluster manifest` or `legacy lock` file. If both files are provided, `cluster manifest` is read first.
ticket: #2334

cluster/manifest: load cluster from disk

---

testutil/compose/compose_internal_test.go
testutil/compose/config.go
testutil/compose/lock.go
testutil/compose/run.go
testutil/compose/smoke/smoke_test.go
testutil/compose/testdata/TestDockerCompose_run_template.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden
testutil/compose/testdata/TestNewDefaultConfig.golden

Adds compose smoke tests for blinded blocks, both vmock and teku.
category: test
ticket: #2317

compose/smoke: add blinded block smoke tests

---

core/tracker/inclusion_internal_test.go

Fixes failing `inclusion_internal_test` due to non-deterministic ordering of included duties.
Build: https://github.com/ObolNetwork/charon/actions/runs/5380913909/jobs/9764300053?pr=2361
ticket: none

core/tracker: fix inclusion test

---

cmd/addvalidators.go
cmd/addvalidators_internal_test.go

Backup `cluster-manifest.pb` files before overriding.
Also adds a new flag `--data-dir` to specify the directory where the backups will be stored, default is `.charon`.
The backup filenames following this pattern: `cluster-manifest-backup-20060102150405.pb`.
ticket: #2345

cmd: backup cluster manifests

---

cmd/addvalidators.go
cmd/addvalidators_internal_test.go

Fixes bug in `add-validators-solo` command identified [here](https://github.com/ObolNetwork/charon/pull/2369/files#r1243873252).
Also adds a unit test which runs the command twice and ensures that the final manifest has two extra validators as expected.
category: bug 
ticket: none

cmd: fix bug in `add-validators-solo` command

---

cmd/addvalidators.go

Fixes bug in add-validators test config.
This fixes the build failure on main - https://github.com/ObolNetwork/charon/actions/runs/5397078524/jobs/9801399390
category: bug 
ticket: none

cmd: fix bug in test config

---

cmd/createcluster.go
cmd/createcluster_internal_test.go

Fix non-intuitive error message in `create cluster` command.
ticket: #2340

cmd: fix error message

---

app/peerinfo/adhoc.go
app/peerinfo/peerinfo.go
core/consensus/component.go
core/consensus/transport.go
core/parsigex/parsigex.go
core/priority/prioritiser.go
dkg/bcast/client.go
dkg/bcast/server.go
dkg/frostp2p.go
p2p/receive_test.go
p2p/sender.go

p2p: revert #2350

---

p2p/receive_test.go
p2p/sender.go
p2p/sender_test.go

Add support for multi protocols to `p2p.Send(...)`.
category: bug
ticket: #2386

p2p: add support for multi protocols to Send

---

cmd/addvalidators.go

Adds `--log-level` flag and additional logs to `add-validators-solo` command.
ticket: #1887

cmd: add logs

---

cmd/createcluster.go
cmd/createcluster_internal_test.go

This PR refactors `create cluster` logic to make it slightly simpler.
New behaviors:
- if `--split-existing-keys` is enabled, `--num-validators` cannot be set
- `--num-validators` must be present unless `--split-existing-keys` is enabled, otherwise `create cluster` exits with error
- split key generation and disk read
- don't fill in with random keys when splitting: during `--split-existing-keys` before this PR, if the user specified a `--num-validators` greater than the amount of keys contained in `--split-keys-dir` Charon would fill in the blanks with random keys
- if definition file validator amount and `--num-validators` don't match, the creation process stops
ticket: #2341

cmd: simplify `create cluster` logic

---

cmd/createcluster.go
cmd/createcluster_internal_test.go
cmd/createdkg.go
cmd/createdkg_internal_test.go

- removed `--clean` subcommand in favor of explicit error messages
- removed default for `--nodes`
- removed default for `--network`
- the default cluster dir is now the current working directory
Closes https://github.com/ObolNetwork/charon/issues/2302.
ticket: #2302

cmd: `create cluster` cleanup

---

cluster/manifest/load.go
cmd/addvalidators.go
cmd/addvalidators_internal_test.go

Write deposit data file for new validators created in `add-validators-solo` command to each node directory. The new deposit files are named as `deposit-data-20230704173152.json`.
Also deletes logic for backing up cluster manifests. 
ticket: #2379

cmd: write deposit datas to disk

---

app/disk.go
cluster/manifest/load.go
cluster/manifest/load_test.go
cluster/manifest/mutationlegacylock_test.go
cmd/addvalidators.go
cmd/combine/combine.go

Remove `isLegacyLock` bool return value when loading cluster from either manifest or lock file.
ticket: none

cluster: remove deprecated return value

---

app/health/checks.go
app/health/checks_internal_test.go

Fixes the following checks:
- `high_error_log_rate` align with warning check since we not only log errors when user intervention is required.
- `insufficient_connected_peers` fix metric name
category: bug
ticket: none

app/health: fix peer and error checks

---

core/validatorapi/router.go
core/validatorapi/router_internal_test.go

Adds support to write response headers for API endpoints. This is added in order to support latest beacon APIs spec change to return response headers in some endpoints. Refer:
- https://ethereum.github.io/beacon-APIs/#/Validator/produceBlockV2
- https://ethereum.github.io/beacon-APIs/#/Validator/produceBlindedBlock
ticket: none

core/validatorapi: add response headers

---

app/app.go
core/tracker/inclusion.go

Adds inclusion checker delay to tracker analyser to capture inclusion errors. Also decreases inclusion checker delay to 4 slots from 16 slots.
category: bug
ticket: #2415

app: fix tracker delay to capture inclusion

---

core/proto.go

Return ssz unmarshalling errors when it is obvious that the data isn't json. This should improve troubleshooting ssz unmarshalling issues.
category: misc
ticket: none

core: improve ssz unmarshalling logs

---

core/parsigex/parsigex.go
core/proto.go

Also log full hex encoded byte arrays that fail to get unmarshaled in their original type.
Needed to troubleshoot https://github.com/ObolNetwork/charon/issues/2433.
category: misc
ticket: #2433

parsigex: unmarshal data that is about to be broadcasted

---

app/vmock.go

Add mutex to `onStartup` variable in `wireValidatorMock()`. This fixes data race identified in this build - https://github.com/ObolNetwork/charon/actions/runs/5551674526/jobs/10138073971?pr=2431#logs. 
The data race arises from two goroutines trying to modify the value of `onStartup`:
1. First goroutine which handles slot X tries to read the value of `onStartup`
2. Second goroutine which handles slot Y tries to update the value to `false`
category: bug 
ticket: none

app: add mutex to `onStartup`

---

core/consensus/component.go

Error when either `Participate` or `Propose` is called multiple times for the same duty since this results in goroutines hanging forever. 
Also removes debug logs.
ticket: #2439

core/consensus: error on subsequent calls

---

core/priority/prioritiser.go

If consensus has been started because enough messages have been received, don't also start it if exchangeTimeout is reached.
category: bug
ticket: #2439

core/priority: don't start consensus twice

---

core/consensus/component.go
core/consensus/component_internal_test.go

Adds a `ShouldRun` method to `instanceIO` to check if the instance was actually "running" rather than returning boolean from `getInstanceIO`.
category: bug
ticket: #2439

core/consensus: add ShouldRun method

---

core/testdata/TestJSONSerialisation_VersionedBeaconBlock.json.golden
core/testdata/TestJSONSerialisation_VersionedBlindedBeaconBlock.json.golden
core/testdata/TestJSONSerialisation_VersionedSignedBeaconBlock.json.golden
core/testdata/TestJSONSerialisation_VersionedSignedBlindedBeaconBlock.json.golden
core/validatorapi/router_internal_test.go
go.mod
go.sum

Downgrades `go-eth2-client` version to v0.17.0. We need to do this in order to be compatible with beacon nodes until all the clients implement latest updates of beacon API specs like returning `Eth-Consensus-Version` as response header in some endpoints.
category: bug
ticket: none

gomod: downgrade go-eth2-client

---

core/parsigex/parsigex.go
core/proto.go

This reverts commit 6075930ef2bcb64200cd2b8b762048540f0ca718, since we [identified](https://obollabs.slack.com/archives/C05GZ3U44F9/p1689937965228159) the cause for the unmarshaling error.
category: misc
ticket: #2433

parsigex: remove unmarshal logs

---

core/consensus/component.go
core/consensus/component_internal_test.go

Rename ShouldRun to MaybeStart as per @corverroos 's suggestion: https://github.com/ObolNetwork/charon/commit/8ad58039f961db4d7356050efb73d84f9f092cce#r122236580
category: misc
ticket: none

core/consensus: rename ShouldRun

---

.github/workflows/golangci-lint.yml
.golangci.yml
app/errors/errors.go
app/errors/go113.go
app/tracer/trace_test.go
app/z/zapfield.go
cmd/markdown_internal_test.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
eth2util/keymanager/keymanager_test.go
eth2util/keystore/keystore.go
p2p/p2p.go
testutil/golden.go
testutil/integration/helpers_test.go
testutil/trackpr/track.go

Bump `golangci-lint-action` to `v3` and `golangci-lint` version to `v1.52.2`.
category: misc
ticket: none

*: bump golangci-lint-action

---

app/log/filter.go

I think an hour is maybe too much, it is hiding information. Once a slot (every 12 secs) feels better. VC triggered logs are often roughly once a slot per type. So this would have same visibility level. 
ticket: none

app/log: decrease default log filter from 1h to 12s

---

core/signeddata.go
eth2util/types.go

Similar to the issue discovered in https://github.com/ObolNetwork/charon/pull/2462, we should also pre-empt such a change in the `eth2spec.BuilderVersion` by introducing our own `eth2util.BuilderVersion` type.
ticket: #2466

eth2util: clone builder version

---

core/validatorapi/router_internal_test.go
go.mod
go.sum

Downgrades `go-eth2-client` to v0.17.0 to remain compatible with lighthouse because of this issue: https://github.com/sigp/lighthouse/issues/4525
category: misc
ticket: none

gomod: downgrade go-eth2-client to v0.17.0

---

app/version/version.go

Bump version of `main-v0.17` release branch to `v0.17-rc` to prepare a release candidate for the `v0.17` release.
ticket: none

app/version: bump to `v0.17-rc`

---

Dockerfile

Fix `Dockerfile` by removing `\` symbols.
This fixes the `build-push-deploy` github workflow which is failing: https://github.com/ObolNetwork/charon/actions/runs/5689854878/job/15422120453
ticket: none

github: fix dockerfile

---

app/metrics.go
app/monitoringapi.go
app/peerinfo/metrics.go
app/peerinfo/peerinfo.go
app/promauto/resetgauge.go
app/promauto/resetgauge_test.go
core/scheduler/metrics.go
p2p/p2p.go

Refactor `Reset` method of the `ResetGauge` to accept a slice of label values to match against, adding support for partial reset, not just a full reset..
ticket: none

app/promauto: support partial resets

---

dkg/bcast/client.go
dkg/bcast/helpers.go
p2p/sender.go
p2p/sender_test.go

We didn't actually set timeouts when sending libp2p messages, only when receiving message. Not setting timeouts is bad practice. See more info on this [here](https://dev.to/bearer/the-importance-of-request-timeouts-l3n) and [here](https://medium.com/booking-com-development/io-socket-timeout-socket-timeout-made-easy-4dfd43e777f7).
This sets the send timeout equivalent to the read timeout, allowing up to 1s latency between nodes, so read timeout+2s.
category: misc
ticket: none

p2p: set default send timeout

---

cluster/manifest/load.go
cluster/manifest/load_test.go

Return error if clusters loaded from legacy lock and manifest files don't have the same cluster hash.
ticket: #2335

cluster/manifest: match cluster hashes

---

dkg/dkg.go
dkg/exchanger.go
dkg/exchanger_internal_test.go

Before this commit, calling `exchange()` would listen for new incoming messages and discard everything that didn't carry the expected `sigType`.
In a DKG one node might fall behind the others (for example, while DKG'ing 3000 validator keys) and send `sigTypes` that the other peers have already received threshold for.
This PR makes sure a given instance of `exchanger` will hold onto all messages whose `sigTypes` are specified during its initialization phase.
Calling `exchange()` will return as soon as there are enough messages for the specified `sigType`, but different `sigType`s messages will still be stored and will be returned when requested by means of another `exchange()` call, with a different `sigType` argument.
category: bug
ticket: #2491
Closes #2491.

dkg: exchange sigTypes concurrently

---

.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
.github/workflows/nightly-tests.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/track-pr.yml
.github/workflows/verify-pr.yml
.golangci.yml
Dockerfile
testutil/promrated/Dockerfile

Also fixes latest `govulncheck` issues.
category: misc
ticket: none

*: bump go version to `1.20.7`

---

.github/workflows/test.yml
testutil/compose/compose/main.go
testutil/compose/config.go
testutil/compose/fuzz/fuzz_test.go
testutil/compose/lock.go
testutil/compose/run.go
testutil/compose/testdata/TestNewDefaultConfig.golden

Integrates p2p fuzz to compose.
category: test
ticket: #2375

testutil/compose: integrate p2p fuzz to compose

---

dkg/exchanger.go
dkg/exchanger_internal_test.go

Wait until all peer's validator signatures over exchanger-handled data.
This should fix nightly test.
category: bug
ticket: none

dkg: wait for all validator key sigs

---

dkg/dkg.go
dkg/sync/client.go

Make every peer participating in the DKG wait for the "slow" one, and synchronize the `Successfully completed DKG ceremony 🎉` message output.
category: misc
ticket: none

dkg: lockstep success message

---

app/app.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go

Fixes soft shutdown by cancelling long running proxied requests.
This is because long lived connections are not interrupted by `http.Server.Shutdown`:
```
// Shutdown gracefully shuts down the server without interrupting any
// active connections. Shutdown works by first closing all open
// listeners, then closing all idle connections, and then waiting
// indefinitely for connections to return to idle and then shut down...
```
category: bug
ticket: #2435

core/validatorapi: close proxy requests on shutdown

---

app/peerinfo/peerinfo.go

Validates Git hash using regex and moves peer Charon version validation before submitting metrics.
ticket: #2500

app/peerinfo: verify git hash

---

app/app.go
core/aggsigdb/memory.go
core/aggsigdb/memory_internal_test.go
core/aggsigdb/memory_test.go
core/bcast/bcast.go
core/bcast/bcast_test.go
core/bcast/recast.go
core/interfaces.go
core/parsigdb/memory.go
core/parsigdb/memory_internal_test.go
core/retry.go
core/sigagg/sigagg.go
core/sigagg/sigagg_test.go
core/tracing.go
core/tracker/inclusion.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go
core/tracking.go
core/types.go
dkg/exchanger.go
testutil/integration/simnet_test.go

Introduce the `core.SignedDataSet` type and refactor `sigagg`, `aggSigDB` and `bcast` interfaces to use it. This supports batching when broadcasting signed data to beacon API which should improve latency and decrease BN load for large clusters.
ticket: #2373

core: batch signed data set

---

core/gater.go
core/gater_test.go

Implement duty gater that checks whether duties are too far in the future. Next step is to wire it when duties are received over the wire.
ticket: #2506

core: implement duty gater

---

cmd/combine/combine.go
cmd/combine/combine_test.go
eth2util/keystore/keystore.go
eth2util/keystore/keystore_test.go

Ensures the output folder exists before writing combined keys to it.
category: bug
ticket: #2536

cmd/combine: ensure output dir exists

---

docs/branching.md

Aligns the release process docs with the v2 [doc](https://docs.google.com/document/d/1A_TtUB54rhxz_Nxw3HHLfR6bVvJpUNe2S8AaIlP0rL0/edit).
category: docs
ticket: none

docs: update v2 release process

---

core/aggsigdb/memory_internal_test.go

This PR addresses a detected race condition in TestDutyExpiration tests. The issue arose from simultaneous read/write operations on the db.keysByDuty map. Instead of relying on timeouts, which proved unreliable, I switched to using a sync.WaitGroup to ensure effective coordination. 
Along with the race condition fix, this PR also enhances the test suite's performance by introducing t.Parallel() at the beginning of tests to allow for parallel execution of tests within the package.
category: bug
ticket: https://github.com/ObolNetwork/charon/issues/2546

core/aggsigdb: fix race condition in TestDutyExpiration

---

testutil/promrated/promrated.go
testutil/promrated/promrated/main.go

add networks flag
ticket: #2571

testutil/promrated: add networks flag

---

eth2util/network.go

Fix holesky genesis fork version.
category: bug
ticket: none

eth2util: fix fork version

---

eth2util/deposit/deposit.go
eth2util/deposit/testdata/TestMarshalDepositData.golden

Bump `deposit-cli-version` to `2.7.0`.
ticket: none

eth2util/deposit: bump deposit cli version

---

.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
.github/workflows/nightly-tests.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/verify-pr.yml
.golangci.yml
.pre-commit-config.yaml
Dockerfile
app/peerinfo/peerinfo.go
cluster/definition.go
cluster/deposit.go
cluster/distvalidator.go
cluster/lock.go
cluster/operator.go
cluster/registration.go
eth2util/keystore/keystore.go
go.mod
go.sum
testutil/promrated/Dockerfile
testutil/verifypr/verify.go

Bump charon to `go1.21.3`.
This fixes failing govulnchecks https://github.com/ObolNetwork/charon/actions/runs/6504583723.
ticket: none

*: bump go version

---

eth2util/keystore/keystore.go

When running `create cluster` with the `--split-existing-keys` flag, I ran into the charon service getting OOM killed. A bit of trial and error helped me figure this was related to the amount of keys to be split. A low amount (<30) would work fine.
I found out splitting 25 existing keys resulted in a memory consumption of over 6GB, 10 keys used about 2.5GB.
Curious to see what would lead to such high memory consumption, I built the binary locally and extracted a heap dump. The heap dump showed that pretty much all the memory was consumed by `golang.org/x/crypto/scrypt.Key objects` , 256MB per key (temporarily even 512MB is allocated if I'm looking at the data correctly).
64 workers (current value) * 256MB per key results in an upper limit of more than 16GB of memory consumed, with an even …

eth2util/keystore: lower amount of loadStoreWorkers

---

testutil/genchangelog/main.go

Always overwrite tags with whatever is available on remote when generating a changelog.
This has no consequence on tags *pushed* on the repo, but only on the working copy of the Github action that is executed.
category: bug
ticket: none

testutil/genchangelog: force fetch tags

---

testutil/validatormock/component.go

Fixes panics in simnet tests by introducing a delay in validatormock of 2 slots. The panics were caused by the race condition between scheduling duties of two slots. Note: In simnet tests we have 1s slot duration and 1 slot per epoch. This is happening when scheduler sends slot tick event in between the slot. 
For example, in above scenario on startup first peer got slot tick of 1st slot at 900th Millisecond but it took 200ms to schedule duties for that slot which results in slot tick of 2nd slot. And since we set attester duties once at the start of each epoch, this results in panic as it sets duties twice just because first two slots were out of sync.
ticket: none

testutil/validatormock: fix simnet tests

---

testutil/validatormock/component.go

Changes start time of sync selections in vmock to start of slot as proposed.
ticket: none

vmock: change start time of sync selections to start of slot

---

eth2util/keymanager/keymanager.go

Using the `--keymanager-addresses` flag to automatically import keystores fails when creating a cluster with more than a handful of keystores due to the request timing out while the remote signer is importing the keystores.
This PR adjusts the behavior by making the timeout value dependent on the amount of keystores to be imported, setting a timeout of 2 seconds per keystore. This value was chosen rather arbitrarily as a "safe", high enough value based on my experience with importing keystores, this taking around 0.25 - 0.5 seconds per keystore.
Feel free to lower the value as you deem fit. However, the request timing out can be rather annoying to resolve, since the entire `create cluster` process needs to be started over and keystores need to manually be removed from keymanagers where …

eth2util/keymanager: dynamically set request timeout

---

cmd/combine/combine.go
cmd/combine/combine_test.go

Allows threshold number of keys to combine private keyshares into single validator keystore.
ticket: #2663

cmd/combine: allow threshold number of keys to combine

---

app/version/version.go
app/version/version_test.go
testutil/genchangelog/main.go
testutil/genchangelog/main_internal_test.go
testutil/genchangelog/template.md
testutil/genchangelog/testdata/TestParsePRs_parsed_prs.golden
testutil/genchangelog/testdata/TestParsePRs_template.golden
testutil/genchangelog/testdata/TestParsePRs_template_data.golden

This PR:
- filters out pre-releases (i.e. `-rcX`) when automatically gathering tags
- modify changelog template to also output all the PRs that have been merged between two tags
ticket: none

testutil/genchangelog: ignore rc's, template changes

---

cmd/createcluster.go
cmd/createcluster_internal_test.go
cmd/testdata/TestCreateCluster_test_with_fee_recipient_and_withdrawal_addresses_files.golden
cmd/testdata/TestCreateCluster_test_with_fee_recipient_and_withdrawal_addresses_output.golden
testutil/random.go

This PR fixes a bug in the `create cluster` command that was generating incorrect builder registrations in cluster-lock.json. The issue stemmed from the usage of withdrawal addresses instead of fee recipient addresses, which resulted in signature verification failures when the command was used for the 'charon run' operation.
Here's the error log caused by this bug:
category: bug
ticket: #2674

cmd/createcluster: fix pre-gen builder registrations

---

core/validatorapi/validatorapi.go

Fixes get validators method to convert pubshares to pubkeys.
category: bug
ticket: none

core/validatorapi: fix get validators method

---

core/bcast/bcast.go

This PR fixes delay reports by bcast for builder registration duty. As reported multiple times:
```
12:32:23.134 INFO bcast      Successfully submitted validator registration to beacon node {"delay": "25416h32m0.13494757s", "pubkey": "858_9bf", "duty": "0/builder_registration"}
```
category: bug
ticket: #2681

core/bcast: fix builder registrations delays

---

app/obolapi/api.go

Update timeout to 30s for publishing lock to obol-api. This ensures that DKG doesn't error if lock files are large enough (>200kb) whose publishing takes more than 5s. 
30s is an empirical timeout value which is safe for publishing large lock files (1.5MB)  to obol-api.
ticket: none

obolapi: update publish lock timeout to 30s

---

app/version/version.go

Bumps current version to `v0.19-dev` and adds it to the supported versions.
category: misc
ticket: none

app/version: bump to `v0.19-dev`

---

app/obolapi/api.go
cmd/createcluster.go
cmd/createcluster_internal_test.go
cmd/testdata/TestCreateCluster_test_with_fee_recipient_and_withdrawal_addresses_files.golden
cmd/testdata/TestCreateCluster_test_with_fee_recipient_and_withdrawal_addresses_output.golden
testutil/random.go

This PR cherry-picks the following PRs:
- https://github.com/ObolNetwork/charon/pull/2685
- https://github.com/ObolNetwork/charon/pull/2673
category: bug
ticket: none

*: cherry pick 2685 and 2673

---

app/eth2wrap/synthproposer.go
testutil/compose/static/lighthouse/run.sh

Continue looking for signed beacon blocks if a block for a given slot is not found when proposing synthetic blocks.
This solves recurrent logs when synthetic block proposal feature is switched on:
```
{"code":404,"message":"NOT_FOUND: beacon block at slot 6916888","stacktraces":[]}
```
category: bug 
ticket: none

eth2wrap: fix synthetic block proposals

---

.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
.github/workflows/nightly-tests.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/verify-pr.yml
.golangci.yml
Dockerfile
testutil/promrated/Dockerfile

Bump go version to `1.21.4`.
This resolves failing govulncheck in https://github.com/ObolNetwork/charon/actions/runs/6809276170/job/18515227544?pr=2693.
ticket: none

*: bump to go 1.21.4

---

.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
.github/workflows/nightly-tests.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/verify-pr.yml
.golangci.yml
Dockerfile
app/eth2wrap/synthproposer.go
app/obolapi/api.go
testutil/compose/static/lighthouse/run.sh
testutil/promrated/Dockerfile

CHERRY-PICKED PRs
* Update timeout for publishing lock to 30s: https://github.com/ObolNetwork/charon/pull/2685
* Fix synthetic proposal errors when a block for a slot is not found: https://github.com/ObolNetwork/charon/pull/2693
* Bump go version to 1.21.4 to fix govulncheck builds: https://github.com/ObolNetwork/charon/pull/2694
category: bug 
ticket: none

*: cherry pick commits

---

app/version/version.go
testutil/genchangelog/main.go

Generates changelog between last non-rc release and latest rc release, but never between two rc's.
category: bug
ticket: none

testutil/genchangelog: generate logs for latest rc release

---

app/version/version.go
testutil/compose/smoke/smoke_test.go

Fixes version matrix smoke test. It was expected `v0.19.0-dev` image while it should expect `v0.19-dev` which is tagged on every commit to main. Also removes v0.16.0 from supported versions as it is not compatible with v0.18.0.
category: bug
ticket: none

compose: fix version matrix test

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_test.go
app/eth2wrap/synthproposer.go
app/eth2wrap/synthproposer_test.go

There was a small issue when comparing eth2api errors when searching for signed beacon block. The error returned should be part of eth2wrap multi implementation which was not able to decompose eth2 errors properly. This PR fixes decomposition of eth2 errors and adds a function to check if the relevant field is present as part of the error chain.
category: bug
ticket: #2695

app/eth2wrap: fix error comparison for synthetic blocks

---

core/scheduler/scheduler.go

Adds a check for activation epoch to filter active validators before resolving duties.
category: bug
ticket: #2721

scheduler: check for activation epoch

---

.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
.github/workflows/nightly-tests.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/verify-pr.yml
.golangci.yml
Dockerfile
testutil/promrated/Dockerfile

The previous build failed due to older go version (1.21.4), now bumped to 1.21.5.
ticket: none

*: bump go version to 1.21.5

---

app/app.go
core/interfaces.go

Wire recaster component in the Wire function of `interfaces.go` to integrate `DutyBuilderRegistration` to tracker. This will enable tracking of all the rebroadcast submissions by recaster.
ticket: #2669

core: wire recaster component

---

cluster/manifest/load.go
cluster/manifest/load_test.go

Corrects the load cluster error switch as default one was always returning the first z.Err field even if something went wrong with cluster-lock load.
```
charon-1      | 12:00:07.840 INFO app-start  Charon starting                          {"version": "v0.18.0", "git_commit_hash": "67725e4", "git_commit_time": "2023-11-10T15:18:42Z"}
charon-1      | 12:00:07.849 ERRO cmd        Fatal error: load cluster manifest: load dag from disk: couldn't load cluster dag from either manifest or legacy lock file {"error": "read manifest file: open .charon/cluster-manifest.pb: no such file or directory", "file": ".charon/cluster-manifest.pb"}
charon-1      |         cluster/manifest/load.go:65 .LoadDAG
charon-1      |         cluster/manifest/load.go:26 .LoadCluster
charon-1      | …
```

cluster/manifest: correct load cluster error

---

app/featureset/featureset.go
app/featureset/featureset_internal_test.go
core/consensus/component.go
core/consensus/roundtimer.go
core/consensus/roundtimer_internal_test.go

This PR splits `qbft_timers_ab_test` feature flag into two feature flags to enable consensus participate and eager double linear round timer separately. 
category: misc
ticket: none

app/featureset: split `qbft_timers_ab_test` feature flag

---

app/version/version.go

Only support v0.19 and 0.20 series versions.
category: misc
ticket: none

app/version: bump version to v0.20-dev

---

core/validatorapi/router.go
docs/contributing.md
docs/dkg.md
docs/goguidelines.md

Fix docs from PR#2755, PR#2758.
ticket: none

docs: fix docs from small prs

---

core/proto.go
core/unsigneddata.go
docs/structure.md

After removing the leadercast component, some leftovers were remaining the code, hence the cleanup.
category: misc
ticket: none

core: removed leadercast leftovers

---

core/proto.go
core/tracing.go
eth2util/rlp/rlp.go

Removed some unnecessary panic() calls and added recover() where appropriate.
ticket: none

core: addressed some panic instances

---

core/validatorapi/validatorapi.go

Correction in error return in validatorapi. Error should be returned as `errors.New(...)` rather that `errors.Wrap(...)`.
category: misc
ticket: none

core/validatorapi: correct error return

---

go.mod
go.sum

Cgo dependency linking fails, reverting to a known working version of Herumi.
Upstream ticket: https://github.com/herumi/bls-eth-go-binary/issues/56
---
Revert "build(deps): Bump github.com/herumi/bls-eth-go-binary from 1.32.1 to 1.33.0 (#2773)"
This reverts commit 42b1118da35c2229f7t d62b30b0a27ed21494250d.
ticket: none

*: revert Herumi to v1.32.1

---

cmd/createcluster.go
dkg/dkg.go
dkg/dkg_internal_test.go
eth2util/keymanager/keymanager.go
eth2util/keymanager/keymanager_test.go

Checking keymanager address.
category: misc
ticket: none

core: checking keymanager address

---

core/dutydb/memory.go

DutyDB's `Store()` function has inconsistent handling for `DutySyncContribution`.
category: bug
ticket: none

core: fixing DutyDB Store function

---

cmd/cmd_internal_test.go
cmd/run.go
docs/configuration.md
p2p/config.go

Removed unused p2p's allowlist and denylist flags to avoid user confusion and false assumptions.
category: bug
ticket: none

core: removed unused allowlist and denylist flags

---

dkg/dkg.go
dkg/sync/client.go
dkg/sync/server.go
dkg/sync/server_internal_test.go

Improved logic for steps update in DKG process.
category: misc
ticket: none

dkg: strengthen logic for steps update

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go

A quick refactor of eth2wrap to avoid panic() call, to remove extra loops and to remove ambiguity around address<->index translation.
ticket: none

app: eth2wrap best selector refactoring

---

core/proto.go
core/validatorapi/router_internal_test.go

Remove unimportant todos from router tests.
category: misc
ticket: none

core: remove unimportant todos

---

cmd/createcluster.go
cmd/createcluster_internal_test.go

Use the current timestamp for builder registration messages when using `--split-existing-keys` mode.
See [the issue](https://github.com/ObolNetwork/charon/issues/2770) for the full context.
category: bug
ticket: #2770

cmd: fixing builder registration timestamp

---

dkg/disk.go
p2p/bootnode.go

Warn if relay or definition file URLs are HTTP.
ticket: none

*: more warnings on HTTP URLs

---

Dockerfile
go.mod
go.sum

In order to support the latest version of the Herumi BLS library Charon links against, we had to update our Docker container to build and run on Debian Bookworm.
ticket: none
Closes #2814.

gomod: update Herumi BLS to v1.33.0

---

cmd/cmd_internal_test.go
cmd/run.go
docs/configuration.md

Add a secondary relay "https://1.relay.obol.tech" to the `--p2p-relays` flag default values.
ticket: none

cmd: add secondary charon relay

---

eth2util/types.go
eth2util/types_test.go

Removes legacy signed epoch as part of migration.
ticket: #2593

eth2util: remove legacy signed epoch

---

cmd/debug_tools.go
cmd/debug_tools_internal_test.go
cmd/relay.go
cmd/relay/relay.go
cmd/run.go
docs/configuration.md

Same principle as #2808.
Refactor the binding functions to be usable across multiple commands.
ticket: none

cmd/relay: bind debug and monitoring address separately

---

p2p/sender_test.go

Fixed flakey `TestWithSendTimeout`.
category: bug
ticket: none

p2p: fixed flakey TestWithSendTimeout

---

cmd/addvalidators.go
cmd/createcluster.go
dkg/dkg.go
dkg/dkg_internal_test.go
eth2util/deposit/deposit.go
eth2util/deposit/deposit_test.go

`NewMessage` function that creates `DepositMessage` to receive custom amount. Was 32ETH by default.
ticket: none

eth2util: new deposit message with amount

---

app/eth2wrap/eth2wrap_test.go
app/eth2wrap/httpwrap.go
app/obolapi/api_test.go
cmd/cmd.go
cmd/createcluster.go
core/validatorapi/router.go
eth2util/keymanager/keymanager.go
p2p/bootnode.go
testutil/beaconmock/headproducer_internal_test.go
testutil/promrated/prometheus.go
testutil/url.go
testutil/verifypr/verify.go

Replacing `url.Parse` with `url.ParseRequestURI` where appropriate. 
ticket: #2796

core: using `url.ParseRequestURI`

---

cmd/createcluster.go
cmd/createcluster_internal_test.go

Fix bug in `create cluster` command.
--
From @xenowits's explanation on slack:
> When create cluster command is run twice in the same directory, it doesn’t error out with “Fatal error: existing node directory found, please delete it before running this command” while it should
> Explanation: When we provide a definition file to the create cluster command, we don’t set the "conf.NumNodes" field when verifying the config
```go
//.....
func validateCreateConfig(ctx context.Context, conf clusterConfig) error {
if conf.NumNodes == 0 && conf.DefFile == "" { // if there's a definition file, infer this value from it later
return errors.New("missing --nodes flag")
}
// Check for valid network configuration.
if err := validateNetworkConfig(conf); err != nil {
return errors.Wrap(err, "get network …
```

cmd: fix create cluster bug

---

app/k1util/k1util_test.go
app/obolapi/api_test.go
cluster/cluster_internal_test.go
cluster/cluster_test.go
cluster/helpers_internal_test.go
cluster/lock_test.go
cluster/manifest/cluster_test.go
cluster/manifest/load_test.go
cluster/manifest/mutationaddvalidator_test.go
cluster/manifest/mutationnodeapproval_test.go
cluster/test_cluster.go
cluster/test_cluster_test.go
cmd/addvalidators_internal_test.go
cmd/combine/combine_test.go
cmd/createcluster_internal_test.go
cmd/view_cluster_manifest_internal_test.go
core/consensus/component_test.go
core/consensus/msg_internal_test.go
dkg/disk_internal_test.go
dkg/dkg_test.go
eth2util/rlp/rlp_test.go
p2p/peer_test.go
testutil/integration/infosync_test.go
testutil/integration/nightly_dkg_test.go
testutil/integration/ping_test.go
testutil/integration/simnet_test.go
testutil/random.go

- Update global `rand.Seed(x)` with local `rand.New(rand.NewSource(x))`;
- Update test random functions that used global seed with local seed;
- Update `math/rand.Read(x)` with `crypto/rand.Read(x)` (not included in the issue, but deprecated as well).
ticket: #2831

testutil: replace math/rand deprecation

---

.github/workflows/build-push-deploy.yml

Tag `latest` Docker images to the latest git tag.
Also tag `next` Docker images to the latest commit on `main.
Previously, we tagged `latest` to latest commit on `main` only.
category: misc
ticket: #2359 
Closes #2359

workflows: tag latest on git tags

---

cluster/test_cluster.go
cmd/combine.go
cmd/combine/combine.go
cmd/combine/combine_test.go

Add `--testnet-*` flags to `combine` command.
Users must specify custom network name, chain ID genesis timestamp and fork version as hex string to allow for a custom testnet configuration to work.
category: bug
ticket: #2838 
Closes #2838.

cmd/combine: support testnet config

---

core/consensus/component_test.go
core/qbft/qbft_internal_test.go
p2p/sender.go
p2p/sender_internal_test.go

This PR:
- fixes a data race in p2p.Sender which was flapping in integration and compose tests
- makes "prepare round 2, decide round 3" QBFT internal test more reliable; tested empirically by running the test 100.000 times, usually the flapping issue manifested itself after a couple runs
category: bug
ticket: #2763
Closes #2763.

*: fix flappy tests

---

core/validatorapi/router.go

Use go-eth2-client for block version string for blinded blocks.
category: bug
ticket: none

core/validatorapi: use go-eth2-client versioning

---

app/app.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go

Initial implementation of `/eth/v3/validator/blocks/{slot}` endpoint in according with the design doc.
Introduced some refactoring to the existing v1/v2 endpoints to reduce code duplication.
ticket: #2749

core/validatorapi: propose block v3

---

dkg/dkg_test.go
dkg/sync/server.go
dkg/sync/server_internal_test.go

Allow step increase by a maximum amount of 2 steps.
Since the sync protocol runs in the context of a distributed system, peer messages might be received in a different order than expected.
This is especially true when the nodes are e.g. writing data to disk.
This change still keeps the monotonic property of the function: step count will never decrease.
category: bug
ticket: none

dkg/sync: increase by max 2 steps

---

dkg/dkg_test.go

Fixed timings in dkg_test to address build failure.
ticket: none

dkg: fixing timings in test

---

cluster/manifest/helpers.go
cmd/addvalidators_internal_test.go
cmd/createdkg.go
cmd/relay.go
cmd/relay/p2p.go
cmd/relay/relay.go
cmd/run.go

Removes TODOs in the `cmd` package.
category: misc
ticket: none

cmd: remove todos

---

app/app.go
app/eth2wrap/synthproposer.go
app/health/checks.go
app/log/config.go
app/obolapi/api.go
app/peerinfo/adhoc.go
app/peerinfo/peerinfo.go
app/peerinfo/peerinfopb/v1/peerinfo.proto
app/priorities.go
app/retry/retry.go
app/tracer/trace.go
app/z/zapfield.go

Remove TODOs from app package.
category: misc
ticket: none

app: remove todos

---

Makefile
charon_version.sh

Add a Makefile to make compiling a release-ready Charon binary easier.
The `charon_version.sh` script generates a version string based on the current git status:
- if the repo has a git tag selected, the version string in that binary will be that
- if the repo does not have a git tag selected, the version string is whatever is written in `app/version/version.go`
- if the repo is dirty (i.e. there are uncommitted changes) the version string will have `-DIRTY` appended at the end
This information will be baked in the final binary, and can be viewed with `charon version`.
For a given architecture/OS combo, multiple invocation of `make` will produce binaries with the same SHA-256 hash.
category: misc
ticket: none

*: add Makefile

---

cluster/helpers.go
cluster/helpers_internal_test.go

Handle non-200 HTTP status code in a graceful way, returning it instead of potentially unmarshalling-related errors.
category: bug
ticket: #2897
Closes #2897.

cluster: handle definition download error

---

p2p/gater.go
p2p/ping.go
p2p/sender_internal_test.go

Remove TODOs from the `p2p` package.
category: misc
ticket: none

p2p: remove todos

---

app/obolapi/exit.go
app/obolapi/exit_model.go
app/obolapi/exit_model_test.go
app/obolapi/exit_server_test.go
app/obolapi/exit_test.go
go.mod

Add partial exit endpoints handlers to Charon's Obol API client package.
Added unit tests and a mock server.
This code was taken and adapted from lido-dv-exit: once this PR gets merged, we'll remove it from there.
ticket: #2848

app/obolapi: add exit endpoints

---

.pre-commit-config.yaml

On MacOS the current version of golangci-lint is constantly failing:
```
ERRO [runner] Panic: atomicalign: package "z" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference: goroutine 15917 [running]:
```
After upgrading to the latest version, the issue has gone.
ticket: none

*: bumped golangci-lint

---

testutil/validatormock/component.go
testutil/validatormock/propose.go
testutil/validatormock/propose_test.go

Added `UniversalProposal` support to `validatormock`.
ticket: #2918

testutil/validatormock: supporting universal proposal

---

go.mod
go.sum

Downgrade until https://github.com/attestantio/go-eth2-client/commit/644acdf47afde0f1bdc2b236567caa1f6f438604 is released in a new version.
category: bug
ticket: none

gomod: downgrade go-eth2-client to v0.19.7

---

codecov.yml

Explicitly ignore Go test files and the `testutil` directory, which contain utilities to aid testing.
category: test
ticket: none

codecov: ignore tests and testutil

---

cluster/cluster_internal_test.go
cluster/cluster_test.go
cluster/definition.go
cluster/examples/cluster-definition-005.json
cluster/ssz.go
cluster/version.go
cmd/createcluster.go
cmd/createcluster_internal_test.go
cmd/createdkg.go
dkg/dkg.go
dkg/dkg_test.go

Several fixes for bugs identified in partial deposits implementation.
Plus, a few improvements to prevent using partial deposits for unsupported lock version.
category: bug
ticket: none

*: partial deposits bugfixes

---

testutil/compose/fuzz/fuzz_test.go

Add `fuzz-timeout` CLI parameter for `TestFuzzer` test, that replaces the 20 minutes constant fuzz duration.
Defaults to 20 minutes.
ticket: none

testutil/compose: custom timeout for fuzzer

---

core/consensus/transport.go

Remove unimplemented function in `transport` package.
category: misc
ticket: none

core: remove todo

---

testutil/compose/smoke/smoke_test.go

`SmokeTest/dkg` was running by default with Teku VC, which caused a weird (yet unknown) error and the test to fail.
I verified all `main` commits for the past month trying to find where this was introduced and found that all the commits are failing reliably. I suspect this has something to do with docker engine update (I also updated mine locally and therefore could 100% reproduce the issue).
Even though we still don't know what was wrong with Teku in that specific test, in order to make our builds passing compose tests, I enabled Mock VC for this test, similar to what we do for other DKG tests in the same suite.
category: test
ticket: #2964

testutil/compose: fixed smoke dkg test

---

cluster/helpers.go
cluster/helpers_internal_test.go
cmd/createcluster.go
dkg/disk.go

In according with the issue description #2881, this is UX improvement - if the target validator_keys folder exists, the implementation checks if the folder is empty. If the existing directory is not empty, or in case of any IO error, the process fails.
ticket: #2881

cluster: unique validator_keys dir

---

cmd/combine/combine.go
cmd/combine/combine_test.go

Instead of checking if `validator_keys` directory exists at the end of the load manifest loop, do it earlier and exclude potential non-Charon node directories.
Also make so that `--force` deletes the existing keys, if any.
Solves the use case in which the user called `combine` command twice with an input directory that was also used as an output directory.
category: bug
ticket: #2538 
Closes #2538

cmd/combine: fix multiple runs 

---

app/app.go
app/health/checker.go
app/health/checks.go
app/health/checks_internal_test.go
app/health/metrics.go
app/monitoringapi.go
docs/metrics.md

This is to monitor metrics high cardinality, when a given metric gets too many distinct labels which results in high memory consumption in charon.
To this end this PR introduces one new metric: `app_health_metrics_high_cardinality` (gauge) which renders metric names => max labels count, if this metric exceeded the threshold (100 * num_of_validators).
In addition to the above metric which can be used in alerting, this also adds a new "health check" named `metrics_high_cardinality` which is triggered when `app_health_metrics_high_cardinality` reported any offense.
Note: `app_health_metrics_high_cardinality` will not "reset", because the purpose of this feature is to detect and signal an opportunity of memory leak.
ticket: #2446

app/health: app_health_metrics_high_cardinality

---

.github/workflows/build-push-deploy.yml
.github/workflows/nightly-tests.yml
.github/workflows/test.yml
.gitignore

Pin buildkit version in all `docker/setup-buildx-action@v2` steps (N.B.: at one place v1 is used, which is using buildkit version <0.10.5, so I haven't pinned it there). Other proposed solutions didn't seem to work currently (tested on private repo).
Included as well .vscode in .gitignore.
category: bug
ticket: #2654 
Closes #2654

workflows: avoid unknown/unknown architecture in ghcr

---

app/app.go
cmd/cmd.go
cmd/dkg.go
cmd/relay.go
cmd/run.go

Added logging of full lock_hash and node's enr when charon starts.
ticket: #2778

app: logging lock hash and enr

---

.github/workflows/build-push-deploy-promrated.yaml
.github/workflows/build-push-deploy.yml
.github/workflows/nightly-tests.yml
.github/workflows/test.yml

Some packages installed from the Dockerfile failed after #2971 was merged. Reason was it used default pre-installed version of qemu - the emulator used from amd64 architecture to build the arm64 images. Qemu is suggested by Dockerhub as well.
[Dockerhub](https://docs.docker.com/build/ci/github-actions/multi-platform/)
[Github Issue](https://github.com/docker/buildx/issues/495#issuecomment-918925854)
ticket: none

workflows: add QEMU for arm64 builds

---

go.mod
go.sum

Issue upstream: https://github.com/herumi/bls-eth-go-binary/issues/61
category: bug
ticket: none

*: downgrade herumi BLS to v1.33.0

---

app/featureset/featureset.go
core/consensus/roundtimer_internal_test.go

Promote `eager_dlinear`, `consensus_participate` to stable.
They can still be overridden by passing `eager_double_linear` and `consensus_participate` to the `--feature-set-disable` flag of `charon run`.
ticket: #3001
Closes #3001.

app/featureset: stabilise more features

---

app/app.go
app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/httpwrap.go
app/eth2wrap/lazy.go
eth2util/helper_capella.go
eth2util/helper_capella_test.go
testutil/beaconmock/beaconmock.go

Instead of returning the latest Domain available when the DomainName requested is VOLUNTARY_EXIT, returns the Capella one as detailed in EIP-7044.
Doing so fixes both `exit` commands generating wrong signatures and voluntary exits sent over the VC.
category: bug
ticket: #2981
Closes #2981.

app/eth2wrap: sign domain for `VOLUNTARY_EXIT`

---

core/tracker/reason.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go
docs/reasons.md

Improved operator UX by renaming tracker reasons to be more descriptive.
Verified Obol infra alerts and Dashboard V3 - these do not use the affected identifiers explicitly.
ticket: #2488

core/tracker: improved reasons wording

---

testutil/random.go

During high-load tests on Linux TCP port reuse might happen.
Disable it explicitly to make the test deterministic.
Closes #3041.
category: bug
ticket: #3041

testutil: disable TCP port reuse

---

cmd/exit.go
cmd/exit_broadcast.go
cmd/exit_broadcast_internal_test.go
cmd/exit_fetch_internal_test.go
cmd/exit_list.go
cmd/exit_list_internal_test.go
cmd/exit_sign.go
cmd/exit_sign_internal_test.go

Allow users to specify a custom beacon node HTTP communications timeout.
Defaults to 30 seconds.
category: misc
ticket: none

cmd: exit beacon node custom timeout

---

.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
.github/workflows/nightly-tests.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/verify-pr.yml
.golangci.yml
Dockerfile
testutil/promrated/Dockerfile

Fixes `govulncheck` to version v1.1.0 which fixes https://github.com/golang/go/issues/66139.
This version also renames "stacks" to "traces" for the `-show` flag.
Update to Go v1.22.2 at the same time in order to fix security issues.
category: misc
ticket: none

*: `govulncheck` v1.1.0, Go v1.22.2

---

.github/workflows/build-push-deploy.yml
.github/workflows/golangci-lint.yml
.github/workflows/nightly-tests.yml
.github/workflows/pre-commit.yml
.github/workflows/test.yml

Use self-hosted runners for compute-heavy actions like tests and Docker image builds.
Streamline the `test.yml` action so that its steps aren't executed in parallel but rather sequentially from top to bottom.
category: misc
ticket: none

workflows: use self-hosted runners

---

app/obolapi/exit_test.go
cmd/exit_broadcast.go
cmd/exit_broadcast_internal_test.go
cmd/exit_fetch_internal_test.go
cmd/exit_sign.go
cmd/exit_sign_internal_test.go
eth2util/helper_capella.go
testutil/obolapimock/obolapi_exit.go

Handle capella domain calculation for exits the correct way.
Fixes issues noticed during the offsite, that is, not being able to exit through API.
category: bug
ticket: none

cmd: proper exit Capella domain handling

---

cmd/exit.go
cmd/exit_broadcast.go
cmd/exit_fetch.go
cmd/exit_sign.go

Implement several UX tweaks on the `charon exit` subcommands:
- Instead of printing "Fatal error: could not load keystore: no keys found", add some more context and point the user to the culprit of the issue: "Fatal error: could not load keystore, check if path exists: no keys found {"path": ".charon/validator_keys"}".
- Add `[REQUIRED]` suffix to all the required CLI flags.
- Clarified what's the purpose of `fetch` and `broadcast`.
category: misc
ticket: none

cmd: exit UX tweak

---

dkg/nodesigs_internal_test.go

`TestSigsExchange` is a network-intensive test, that exchanges `n^n` messages at a given time.
While it runs fine on development machines, even our more powerful self-hosted runners need more time for it to finish properly.
Increase the timeout from 15 seconds to 45 seconds as well as reduce the amount of nodes from 10 to 7, in hope to reduce the chances of false positives failures in our CI.
ticket: none

dkg: increase test timeout for `TestSigsExchange`

---

cmd/testpeers.go

Fix writing to closed channel error.
category: bug 
ticket: #3053

cmd: move ctx check before writing to channel

---

cmd/test.go
cmd/testbeacon.go
cmd/testbeacon_internal_test.go
cmd/testpeers_internal_test.go
testutil/helpers.go

Charon alpha beacon node testing. Structure is identical to what we have in peers tests, with the exception that here we do not have separation between self and external (peers). The 4 test cases can be fired against multiple beacon nodes.
To test on your own machine:
```
make charon && ./charon alpha test beacon --endpoints="https://ethereum-holesky-beacon-api.publicnode.com,https://ethereum-sepolia-beacon-api.publicnode.com"
```
Similarly to peers tests, const values used to determine whether a measured test result is average or bad are nothing more than estimates for now on my side. I am open to suggestions on that front.
ticket: #2998

cmd: alpha test beacon

---

.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
.github/workflows/nightly-tests.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/verify-pr.yml
.golangci.yml
Dockerfile
testutil/promrated/Dockerfile

Bump go version to 1.22.3 to fix vulnerability issue with `net` package in standard library.
ticket: #3075

*: bump go version to 1.22.3

---

cmd/test.go
cmd/testpeers.go
cmd/testpeers_internal_test.go

Add alpha peers tests for the TCP node started. Currently only port opened is tested. Test for whether NAT is open is skipped for now as it makes more sense to be added to the peers' tests.
ticket: #3076

cmd: alpha test peers tests self

---

app/peerinfo/peerinfo_test.go
app/version/version.go
app/version/version_test.go

Instead of going with version v0.20, use v1.0.
category: misc
ticket: none

app/version: v1.0-dev

---

cmd/testbeacon_internal_test.go

Sometimes timeout is so little that the test doesn't even reach the second instance, as observed in the pipeline [here](https://github.com/ObolNetwork/charon/actions/runs/9002400755/job/24730617672?pr=3078).
category: bug
ticket: none

cmd: increase timeout of timeout test

---

cmd/testpeers.go

Adding test for direct connection between peers. This should also implicitly test if our NAT is open.
There is a separate ticket for unit testing for all peers tests, as there are more things to be improved on that side - there need to be couple of nodes spin up, with local relay, to be able to properly test the `testpeers.go` code. As soon as that is done, there will be better testing suite for that test case as well.
To try locally, a local relay needs to be spin up first (or expose your IP and port, however, the former is easier):
`./charon relay --p2p-tcp-address="0.0.0.0:9000" --p2p-advertise-private-addresses`
`./charon alpha test peers --enrs="enr:-Iu4QJyserRukhG0Vgi2csu7GjpHYUGufNEbZ8Q7ZBrcZUb0KqpL5QzHonkh1xxHlxatTxrIcX_IS5J3SEWR_sa0ptGAgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQMAUgEqczOje …

cmd: alpha test peers - add direct connection test

---

cmd/testpeers.go
cmd/testpeers_internal_test.go

Add proper unit test for peers - spinning up multiple peers and local relay and running the peer tests between them.
Some other minor improvements:
- use enrs of the deterministic private keys created in the beginning;
- remove logger init in `testpeers.go`;
- add prepare func;
- rename cfg to conf to be consistent with the rest of the codebase.
`testpeers.go` coverage has been increased to 86.4%.
category: test
ticket: #3064

cmd: add full unit test for test peers command

---

cmd/test.go
cmd/testpeers_internal_test.go
cmd/testvalidator.go
cmd/testvalidator_internal_test.go

- Add 3 ping tests for validator client (tested them against local Teku VC).
- Updated the generic functions to be similar to what we have in peers and beacon tests.
N.B.: VC tests are not expected to be as used and as vital as peers and beacon. 
ticket: #2999

cmd: add validator ping tests

---

cmd/testbeacon.go
cmd/testpeers.go
cmd/testvalidator.go

Context nil check is not necessary, as [cobra is always checking on their end](https://github.com/spf13/cobra/blob/v1.8.0/command.go#L1053) if the context is nil and if so, assigning background context to it.
ticket: none

cmd: remove nil context check on test command

---

app/obolapi/api.go
app/obolapi/api_internal_test.go
app/obolapi/exit.go
cmd/dkg.go
cmd/exit.go
cmd/exit_broadcast.go
cmd/exit_broadcast_internal_test.go
cmd/exit_fetch.go
cmd/exit_fetch_internal_test.go
cmd/exit_sign.go
cmd/exit_sign_internal_test.go
dkg/dkg.go
dkg/dkg_test.go

Allow users of `app/obolapi` to specify HTTP requests timeout.
As a result of this feature, add the `--publish-timeout` CLI flag to `exit` and `dkg` commands.
ticket: none

app/obolapi: specify HTTP requests timeout

---

app/eth2wrap/eth2wrap.go
app/featureset/featureset.go
app/featureset/featureset_internal_test.go
app/featureset/status_string.go

Add `WithEnforceJSON(true)` parameter when `json_requests` feature is enabled in `featureset`.
This is needed for Nimbus BN to properly handle SubmitProposal requests.
ticket: #3108
feature_flag: json_requests

app: json_requests feature

---

core/validatorapi/metrics.go
core/validatorapi/router.go
docs/metrics.md

Added two new metrics to VAPI:
* core_validatorapi_request_total
* core_validatorapi_vc_user_agent
These will allows us to track VC's User-Agent strings to determine VC vendor/version implicitly.
And the total number of requests have Content-Type label to track requests' format made by VC.
ticket: #3107

core/validatorapi: metrics for user-agent and content-type

---

cmd/exit.go
cmd/exit_broadcast.go
cmd/exit_broadcast_internal_test.go
cmd/exit_fetch_internal_test.go
cmd/exit_list.go
cmd/exit_list_internal_test.go
cmd/exit_sign.go
cmd/exit_sign_internal_test.go

Allow specifying more than one beacon node to use with the `--beacon-node-endpoints` flag.
Users can now sign exits directly with a validator index rather than specifying its public key.
If both are specified, validator liveliness (i.e. whether or not the validator exists on the beacon chain) is not checked.
`sign` checks that the specified validator index exists in the cluster lock before proceeding.
ticket: #3104 
Closes #3104

cmd: exit with validator index, allow BN URLs 

---

.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
.github/workflows/nightly-tests.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/verify-pr.yml
.golangci.yml
Dockerfile
testutil/promrated/Dockerfile

There was [new release of golang](https://github.com/golang/go/issues?q=milestone%3AGo1.22.4+label%3ACherryPickApproved) yesterday, that fixed security issues with `net` package.
category: misc
ticket: none

*: bump go version to 1.22.4

---

app/app.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go

Instead of always returning the full cache on Validators() requests, only return whatever was requested originally.
Still check cache first, then upstream BN, then if anything comes up return to the caller.
Harden tests to check for this behavior.
Log a debug message when refreshing the validator cache.
Make sure to always refresh the validator cache as soon as the first observed epoch begins, then fall back to the standard refresh pattern (once every epoch).
category: bug
ticket: none

core/validatorapi: return requested validators

---

cmd/exit_broadcast.go
cmd/exit_fetch.go
cmd/exit_sign.go

Allow exit commands to specify a publish timeout.
category: bug
ticket: none

cmd: bind publish timeout on exit

---

cmd/dkg.go
core/parsigex/parsigex.go
dkg/dkg.go
dkg/dkg_test.go
dkg/exchanger.go
dkg/exchanger_internal_test.go
testutil/integration/nightly_dkg_test.go

Users might DKG large clusters, containing high amounts of validators (like 2.5K).
With large validator amounts, the DKG process needs either more time or more power (CPU, network bandwidth) to complete.
Allow users to specify a custom timeout for the entire process, allowing large DKGs on normal-powered machines.
Tested 2.5K validator DKGs locally with 0.relay.obol.tech, 10 minutes timeout: completed with no issues.
ticket: none

dkg: add customizable timeout

---

cmd/cmd.go
cmd/createcluster.go
cmd/run.go
dkg/dkg.go

A warning log was output in the case "https" is missing as a scheme. This triggered anytime it was not https, even if the scheme was empty.
Linter complained for repeated "http", so I've moved it to const alongside "https".
category: misc
ticket: none

*: not https warning to show only on http

---

cmd/testbeacon.go
cmd/testpeers.go

Revise thresholds for pinging and BN peers.
category: misc
ticket: none

cmd: new thresholds for test command

---

cmd/testpeers.go
cmd/testvalidator.go

Continuation of PR #3132 , as this part was skipped because of cherrypicking for v1.
category: misc
ticket: none

cmd: add separate consts for testvalidator

---

cmd/run.go
docs/configuration.md
eth2util/helper_capella.go
eth2util/network.go

Add Capella hard fork to networks in `eth2util`. Refactor `CapellaFork` function to use the networks already specified. This way we can use the Capella fork value of a manually added test network through the flags. Useful for testing exits with Kurtosis.
ticket: none

*: capella fork to networks

---

cmd/exit_sign.go

Setting validx to be the configured index in the case of expert mode
category: bug
ticket: #3147

cmd: add valIdx to obolapi exit message in expert mode

---

core/tracker/inclusion.go
core/tracker/tracker_internal_test.go

Do the same type casting we do in core/bcast to switch on the type of block proposal.
Add a test to check for this property.
category: bug
ticket: none

core/tracker: track blinded proposals

---

core/tracker/inclusion.go
core/tracker/tracker_internal_test.go

Always recover when dealing with malformed proposals, and log some context to aid debugging.
ticket: none

core/tracker: harden inclusion proposal checks

---

core/bcast/bcast.go
core/tracker/inclusion.go
core/tracker/tracker_internal_test.go

- #3144
- #3149
- #3150
category: misc
ticket: none

*: cherry-pick for v1.0.0-rc7

---

go.mod
go.sum

Apparently docker deleted version v27.0.0 off their github repository, buf is still pointing to that version, this makes `go mod tidy` fail.
Update in our go.mod in preparation for buf's update.
ticket: none

*: update docker to v27.0.2

---

core/validatorapi/router.go
core/validatorapi/router_internal_test.go

Endpoints `produce_block` and `produce_blinded_block` must return 404 explicitly to prevent processing as proxy calls. Because previously we removed these from the router.
Also, this ensures all attempts to call these endpoint will increment `core_validatorapi_request_error_total` counter. 
ticket: #1255

core/validatorapi: propose v1 and v2 returns 404

---

.github/dependabot.yml
testutil/compose/static/lighthouse/Dockerfile
testutil/compose/static/lighthouse/run.sh

- Pin lighthouse version in Dockerfile for compose tests.
- Remove stdin flag (doesn't exist in new version).
- Add Docker images checks for dependabot.
category: bug
ticket: none

*: pin lighthouse version in compose tests

---

app/monitoringapi.go
app/stacksnipe/stacksnipe_test.go

Fix linter from stacksnipe PR...
category: misc
ticket: none

app: fix for loop linting

---

cmd/ascii.go
cmd/cmd.go
cmd/test.go
cmd/testmev.go
cmd/testmev_internal_test.go

Add `charon test mev` command for pings towards MEV relays. In the future more tests towards MEV relays can be added.
ticket: #3171

cmd: mev ping tests

---

cmd/testbeacon_internal_test.go
cmd/testpeers.go
cmd/testpeers_internal_test.go

Add ping tests (ping and RTT measurement) towards charon relays.
ticket: none

cmd: `charon test peers` ping charon relays

---

cmd/createcluster.go
cmd/dkg.go
cmd/exit.go
cmd/exit_broadcast_internal_test.go
cmd/exit_sign_internal_test.go
cmd/test.go
cmd/testbeacon.go
cmd/testmev.go
cmd/testpeers.go
cmd/testpeers_internal_test.go
cmd/testperformance.go
cmd/testperformance_internal_test.go
cmd/testvalidator.go
testutil/compose/static/vouch/Dockerfile

- Change Obol's API default URL in flags to include `/v1`
- validator-pubkey to validator-public-key in flag description
- Rename test command measurement from Bad to Poor
- Increase test peer unit tests timeout
- bump ethdo version in compose tests to 1.35.2
category: misc
ticket: none

*: flag refactors

---

Dockerfile
cmd/test.go
cmd/testperformance.go
cmd/testperformance_internal_test.go
go.mod

- Change the existing disk write test to use fio
- Add disk write IOPS test, disk read speed test, disk read IOPS test
- Update Dockerfile to include fio
ticket: #3207

*: add fio tests for disk performance

---

cmd/testperformance.go

Add file for test and do not use a dir (the homedir in the default scenario).
category: bug
ticket: none

cmd: add file to homedir for fio

---

cmd/testperformance.go

Add file for test and do not use a dir (the homedir in the default scenario).
category: bug
ticket: none

cmd: add file to homedir for fio in main-v1.1

---

cmd/cmd_internal_test.go
cmd/run.go
docs/configuration.md

Add a third relay "https://2.relay.obol.dev" to the `--p2p-relays` flag default values.
ticket: none

cmd: add third charon relay

---

testutil/promrated/rated.go
testutil/promrated/rated_internal_test.go

Rated api seemed to change the url for this endpoint 👍🏼 
category: misc
ticket: #3233

testutil/promrated: fixing promrated network overview stats

---

README.md

goerli launchpad is down, and link goes nowhere
category: docs
ticket: none

docs: launchpad link is broken

---

p2p/bootnode.go
testutil/compose/README.md
testutil/compose/alert.go
testutil/compose/auto.go
testutil/compose/compose/main.go
testutil/compose/define.go
testutil/compose/docker-compose.template
testutil/compose/lock.go
testutil/compose/template.go
testutil/compose/testdata/TestDockerCompose_define_create_yml.golden
testutil/compose/testdata/TestDockerCompose_define_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_lock_create_yml.golden
testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden

Compose tests were failing because of `docker-compose` command hasn't been changed to `docker compose` on some places and the version on top wasn't removed.
category: test
ticket: none

testutil: update docker-compose command to docker compose

---

.github/workflows/golangci-lint.yml
.golangci.yml
.pre-commit/run_linter.sh
app/eth2wrap/httpwrap.go
app/expbackoff/expbackoff.go
app/health/checks.go
app/health/checks_internal_test.go
app/health/reducers.go
app/health/select.go
app/log/loki/client.go
app/obolapi/api.go
cluster/helpers.go
cmd/markdown_internal_test.go
cmd/testperformance.go
core/aggsigdb/memory_v2_internal_test.go
core/tracker/tracker.go
core/validatorapi/router.go
eth2util/keymanager/keymanager.go
p2p/bootnode.go
testutil/promrated/rated.go

Bump golangci-lint version to v1.60.3
category: misc
ticket: none

*: bump linter to v1.60.3

---

.github/actions/setup-go/action.yml
.github/workflows/codeql-analysis.yml
.golangci.yml
.pre-commit-config.yaml
Dockerfile
cmd/testpeers_internal_test.go
go.mod
testutil/promrated/Dockerfile

Bump go version to 1.23.
category: misc
ticket: #3251

*: bump go to 1.23

---

cmd/exit.go
cmd/exit_sign.go
cmd/exit_sign_internal_test.go

Refactor exits logic. There is no change in the logic anywhere. The main differences are:
- fetching the validator index and validator pub key are in separate functions, which makes it more readable what is the flow
- `ExpertMode` is renamed to `SkipBeaconNodeCheck` as this is essentially what it does
If others agree, I'm in favour of completely removing the `SkipBeaconNodeCheck` config, as it is unnecessary.
ticket: none

cmd: refactor exits

---

.github/workflows/govulncheck.yml

govulncheck is failing currently in the pipeline, this is an attempt to fix it by simply bumping its version...
category: misc
ticket: none

workflows: bump govulncheck to v1.1.3

---

app/app.go
app/featureset/config.go
app/featureset/config_test.go
app/featureset/featureset.go
app/featureset/featureset_internal_test.go
cmd/createcluster.go
cmd/createdkg.go
eth2util/network.go
eth2util/network_test.go

* Added `chiado` network spec in addition to the existing `gnosis`.
* Feature `gnosis_block_hotfix` is enabled automatically when gnosis | chiado network is detected.
* When the user explicitly disables `gnosis_block_hotfix` feature, the app just yields warning during startup:
```
Feature gnosis_block_hotfix is required by gnosis/chiado, but explicitly disabled
```
ticket: none
feature_flag: gnosis_block_hotfix

*: enable gnosis hotfix automatically

---

cmd/testbeacon.go
cmd/testmev.go
cmd/testpeers.go

- fix test peers on timeout, sometimes it went in the case where the current context is done, but the result of the currently running test wasn't sent to the channel
- fix wrongly named variables
category: test
ticket: none

*: fix flaky testpeers test

---

cmd/testpeers_internal_test.go

Fixing flaky test in previous PR #3267 revealed another issue. Fixing that one, which is purely unit test related.
category: test
ticket: none

cmd: increase testpeers tests timeouts

---

cmd/testpeers.go

After #3267 was merged, on `ctx.Done()` we push the latest unfinished test. This causes out of range in the outer function in some ocassions.
category: bug
ticket: none

cmd: fix test peers out of range

---

app/obolapi/exit.go
app/obolapi/exit_test.go
cmd/exit.go
cmd/exit_sign.go
cmd/exit_sign_internal_test.go

Add `--all` command for signing partial exits. This PR is one of a couple incoming PRs that will be for the `--all` functionality. Mind that the CLI flag is not enabled until all of them are implemented and merged.
ticket: #3243

*: add --all for exit sign command

---

.golangci.yml

Go v1.23 allows to range over int slices without calling `len` first.
Since it's a low-importance change, we can disable intrange linter to avoid being blocked by it during pre-commit.
category: misc
ticket: none

*: disable intrange linter

---

cmd/exit.go
cmd/exit_broadcast.go
cmd/exit_broadcast_internal_test.go

Second part of adding the `--all` flag for exits.
This PR is for the `charon exit broadcast` command. Additionally, a flag `exitFromDir` is introduced so point to a directory with exit files.
ticket: #3243

cmd: broadcast all exits

---

cmd/exit_fetch.go
cmd/exit_fetch_internal_test.go

Third part of adding the `--all` flag for exits.
This PR is for the charon exit fetch command.
ticket: #3243

cmd: fetch all exits

---

app/app.go
app/monitoringapi.go
core/consensus/debugger.go
core/consensus/debugger_internal_test.go

Towards larger consensus abstraction work: reworked QBFT messages debugger to be the generic consensus messages debugger (except for wire representation). This is to eliminate QBFT specific leaked from the consensus/qbft packages.
Breaking change: the debug endpoint `/debug/qbft` has been changed to `/debug/consensus` (and the received file name is changed from `qbft_messages.pb.gz` to `consensus_messages.pb.gz`).
We are not aware of any systems or users actively using or relying on that endpoint in production.
ticket: #3299

app: generic consensus debugger

---

dkg/dkg_test.go

Possibly fixed the flakey test.
category: test
ticket: #3308

dkg: fixed TestSyncFlow

---

cmd/createcluster.go
cmd/createcluster_internal_test.go
cmd/createdkg.go
cmd/createdkg_internal_test.go
tbls/herumi.go

A [recent commit](https://github.com/ObolNetwork/charon/commit/98b84e11548e7267e2440fd6f582a9e8fcdfe970) introduced a misbehavior when omitting the optional `--threshold` flag of `create dkg` and `create cluster` commands.
Because the threshold configuration is tested before the threshold variable is assigned to the default value `ceil(2*n/3)`, the flag is not optional anymore.
This PR fixes this bug by moving the checks at the CLI level and by updating the corresponding tests accordingly.
It also adds an input validation check on the [`ThresholdSplit`](https://github.com/ObolNetwork/charon/blob/ced30abb5a8c168b358a9bfc976fbe23927d72de/tbls/herumi.go#L133) and [`ThresholdSplitInsecure`](https://github.com/ObolNetwork/charon/blob/ced30abb5a8c168b358a9bfc976fbe23927d72de/tbls/herumi.go#L83) …

cmd: move threshold check to CLI level

---

cmd/exit.go

Enable exit all.
ticket: #3243

cmd: enable exit all

---

cmd/createdkg_internal_test.go
cmd/testpeers_internal_test.go

Test performance writing to file was checking for the score, even though some tests are based on current machine's measurements. We have excluded testing measurements for a single test, but not for the overall score.
category: test
ticket: none

test: fix test performance flaky test

---

cmd/createdkg_internal_test.go
cmd/version.go
cmd/version_internal_test.go

Changed `charon version --verbose` to print available consensus protocols in the order defined by the implementation.
Added internal tests.
ticket: #3305

cmd: print consensus protocols

---

.github/workflows/release.yml

Ensure all charon repositories Reflects Current Charon Version
ticket: none

*: create automate pr for release

---

testutil/compose/smoke/smoke_test.go
testutil/compose/static/lodestar/run.sh

This addresses two issues:
1. The broken Smoke Test with lodestar, it refuses accepting network config for dev network.
2. Re-enabled previously disabled compatibility test.
category: test
ticket: #3004

testutil: fixed smoke test

---

.github/actions/setup-go/action.yml
.golangci.yml

Instead of having to bump golang version on each patch release, use latest patch. That's what we already do in `go.mod`.
category: misc
ticket: none

github: use minor go versions in pipelines

---

testutil/integration/nightly_dkg_test.go

Instead of passing errors around with channels, which in this specific test might alter timings, just panic when error is not of "context canceled" kind, during the induced restart phase.
Not ideal, but simple and effective.
category: bug 
ticket: none

testutil/integration: fix nightly test behavior

---

go.mod
go.sum

Recent DKG issues may be due to an issue in bls-eth-go-binary, caused by an upstream bug in their dependencies.
Update to v1.36.1 which solves the issue.
Reference: https://github.com/herumi/bls-eth-go-binary/issues/63
category: bug
ticket: none

*: update bls-eth-go-binary

---

app/obolapi/api.go
app/obolapi/api_internal_test.go
app/obolapi/exit.go
cmd/cmd.go
cmd/exit.go
cmd/exit_broadcast.go
cmd/exit_broadcast_internal_test.go
cmd/exit_fetch.go
cmd/exit_fetch_internal_test.go
cmd/exit_list.go
cmd/exit_list_internal_test.go
cmd/exit_sign.go
cmd/exit_sign_internal_test.go
testutil/obolapimock/obolapi_exit.go

Add more logging and more detailed errors for exits. Given that the exits are fire and forget operation and not a long running process, we can afford more details without the issue of polluting with too much.
ticket: #3136

*: improve logging and error handling for exits

---

cmd/exit.go

In our docs we promote publish timeout set to 5 minutes. We might as well just update it in the CLI 5 min to be the default...
category: misc
ticket: none

cmd: increase Obol API timeout for exits

---

docs/dkg.md
docs/goguidelines.md
docs/structure.md

This pull request fixes several typographical errors found in the documentation files, specifically in the following:
- `dkg.md`
- `goguidelines.md`
- `structure.md`
category: docs
ticket: none

docs: fix typos in documentation files

---

cmd/markdown_internal_test.go
docs/branching.md
docs/contributing.md
docs/dkg.md
docs/metrics.md

This PR addresses minor typos, formatting issues, and enhances clarity in the following documentation files:
- **branching.md**: Fixed typographical errors and improved clarity in descriptions of branching and release models.
- **contributing.md**: Corrected link formatting issues, spelling mistakes, and clarified language in contributing guidelines.
- **dkg.md**: Fixed typographical errors and improved sentence structure for better readability.
- **metrics.md**: Corrected typo in metric label name.
These changes improve the overall readability and accuracy of the documentation, ensuring that users and contributors have clearer instructions and information.
category: docs
ticket: none

docs: fix typos and improve clarity in documentation files

---

cmd/testpeers.go
cmd/testpeers_internal_test.go

Sometimes users find it easier to test with already created `cluster-definition.json` or `cluster-lock.json` files. It saves copying and pasting ENRs and potentially making a mistake.
ticket: none

cmd: add cluster lock and cluster definition to test peers

---

cmd/testbeacon.go
cmd/testmev.go
cmd/testpeers.go
cmd/testperformance.go
cmd/testvalidator.go

Simple refactoring and grouping of the functions in the `charon test` files. They grew quite a lot and thought some grouping would help. There is nothing new introduced (except comments), despite git's assumption of many additions and deletions.
ticket: none

cmd: group and move functions in test command

---

docs/README.md

In the "Go Guidelines" section, the word "principals" corrected to "**principles**" (the correct spelling).
category: docs
ticket: none

docs: typo in README.md

---

cmd/ascii.go
cmd/cmd.go
cmd/test.go
cmd/testall.go
cmd/testbeacon.go
cmd/testmev.go
cmd/testpeers.go
cmd/testpeers_internal_test.go
cmd/testperformance.go
cmd/testvalidator.go

Multiple changes to improve UX of the test command:
1. Add `charon test all` that runs all 5 test commands
2. Shorten the ENRs and MEV relays URLs hashes when outputting results
3. Sort the targets of the tests (so that it's easier to follow consecutive re-ran tests)
Also do some refactoring of the functions.
ticket: none

cmd: test command UX

---

cmd/test.go
cmd/testbeacon.go
cmd/testmev.go
cmd/testmev_internal_test.go
go.mod
go.sum

We have had tests to test latency towards MEV relay, however, it was a simple ping. Those tests add creation of real block headers.
ticket: none

cmd: charon test mev create block tests

---

.github/workflows/golangci-lint.yml
.golangci.yml
.pre-commit/run_linter.sh
app/obolapi/api_internal_test.go
cmd/addvalidators_internal_test.go
core/priority/component.go

- bump linter to v1.62
- disable `recvcheck` linter (showed only false positives...)
- fixed requires in tests
- removed `coreConsensus` interface after discussion wtih @pinebit 
category: misc
ticket: none

*: bump linter v1.62

---

Dockerfile

`chown /opt/charon` was removed previously, but it's required by the test command.
category: bug
ticket: none

Dockerfile: add back chown

---

cmd/testall.go
cmd/testpeers.go
cmd/testpeers_internal_test.go

Change after a [comment from oisin under this PR](https://github.com/ObolNetwork/obol-docs/pull/451#discussion_r1862303738).
ticket: none

cmd: use private key file flag, instead of data dir flag

---

testutil/compose/docker-compose.template
testutil/compose/static/loki/loki.yml
testutil/compose/testdata/TestDockerCompose_run_yml.golden

The problem was that our *compose* tool could not start a cluster: `compose new && compose auto`.
Our *compose* tool used `latest` selector in docker compose and this made the provided config files incompatible. I copied loki config from CDVN and set explicit Grafana stack versions from CDVN as well.
This seems fixed the problem.
category: bug
ticket: none

testutil: fixed compose files

---

testutil/compose/static/lighthouse/Dockerfile
testutil/compose/static/lodestar/Dockerfile
testutil/compose/static/vouch/Dockerfile

Bumped `compose` tool components.
category: misc
ticket: none

testutil: bumped compose tool components

---

core/consensus/utils/instance_io.go
core/consensus/utils/instance_io_test.go
testutil/compose/static/vouch/Dockerfile

Observed a bug in our consensus object `instance_io` where we have the race condition: `panic: close of closed channel`
Fixed the race condition using atomic operations instead of channels.
category: bug
ticket: none

core/consensus: fixed instance_io race

---

.github/workflows/release.yml

add condition to trigger dispatch only for specific tags
ticket: none

*: add condition to trigger dispatch only for specific tags

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/fallback.go
app/eth2wrap/fallback_internal_test.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/multi.go
app/eth2wrap/multi_test.go

Implement a way to provide eth2wrap with two classes of beacon nodes addresses: standard and fallback beacon nodes.
When one of the multi BN calls fails, eth2wrap wrappers will try to get an available fallback BN from a list and re-do the call on that.
If no fallback BNs is specified, return the original error.
If the fallback BN call fails, return fallback error instead.
This PR firstly introduces concepts and code, will introduce CLI parameters and initialization code later.
ticket: #3328

app/eth2wrap: fallback beacon nodes

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/multi.go

Adding logs for some beacon node calls RTT. In order to help tracking issues with underperforming beacon nodes, caused either by slow infrastructure/networking or issues from the beacon node itself.
Currently logs have been added only on the calls for:
- Proposal (GET /eth/v3/validator/blocks/{slot}) - fetches a proposal for signing and is known to be the bottleneck call to the BNs on proposals.
- Validators (POST /eth/v1/beacon/states/{state_id}/validators) - on some BNs this call is taking long time and is blocking the whole BN reachability and any calls to it.
I'm open to including more endpoints.
Fixing linter on one place.
ticket: none

app: eth2wrap latency logging

---

.pre-commit/run_linter.sh

Sometimes golangci-lint fails with `Parallel golangci-lint is running`, even if the previous run finished.
category: misc
ticket: none

build: allow golangci-lint parallel on .pre-commit

---

testutil/compose/auto.go

fix: chown -R runner:docker 001 folder

---

app/peerinfo/peerinfo.go

Fix failing `peerinfo` test due to race condition on storing nickname mappings
category: bug
ticket: none

app/peerinfo: fix race condition on storing nicknames

---

app/eth2wrap/eth2wrap_test.go
app/eth2wrap/synthproposer.go
app/eth2wrap/synthproposer_test.go
core/fetcher/fetcher_internal_test.go
core/parsigex/parsigex_test.go
core/signeddata_test.go
core/ssz_test.go
core/tracker/inclusion_internal_test.go
core/unsigneddata_test.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
eth2util/types_test.go
testutil/random.go
testutil/validatormock/propose_test.go

On first look it seems like a big PR, but it consists of 2 main things:
1. Adding electra version support to all switch cases throughout the codebase.
2. Adding tests for electra + improving the test coverage of already existing versions.
ticket: none

*: support electra in existing codebase; tests

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_test.go
app/obolapi/api.go
cmd/exit_broadcast.go
cmd/exit_broadcast_internal_test.go
cmd/exit_fetch.go
cmd/exit_fetch_internal_test.go

In the scenario where not all keys are activated, fetching and broadcasting from the obol API wasn't possible. This PR fixes this and only throws an error if a key hasn't exited.
category: bug
ticket: none

cmd: fetch and broadcast all when not all are activated

---

app/app.go
app/eth2wrap/valcache.go
app/eth2wrap/valcache_test.go

Add method `GetBySlot` to fetch active/complete validator by slot.
In cases where the beacon node is slow, fetching validators by `head` would lead to outdated information (specifically regarding its active status). By fetching by slot we guarantee to get the up-to-date information.
The downside here is that this request is slower because it might take multiple requests until the beacon node has the information regarding the slot. 
category: bug
ticket: none

fix: refresh validator by slot instead of by head

---

app/eth2wrap/eth2wrap_test.go
core/dutydb/memory.go
core/dutydb/memory_test.go
core/signeddata.go
core/testdata/TestJSONSerialisation_VersionedAggregatedAttestation.json.golden
core/testdata/TestJSONSerialisation_VersionedAttestation.json.golden
core/unsigneddata.go
core/validatorapi/eth2types.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
core/validatorapi/validatorapi.go
go.mod
go.sum
testutil/random.go
testutil/validatormock/testdata/TestAttest_0_attestations.golden
testutil/validatormock/testdata/TestAttest_1_attestations.golden

Previously we have had `Attestation` object sent to the `/eth/v1/beacon/pool/attestations`, however, now in electra, those are `SingleAttestation`s. [Link to the BN API](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/submitPoolAttestationsV2). This required some changes...
Change of the key used for recognising attestations in our memory. Previously part of the key was the **validator's index inside the committee**, however, now as it is `SingleAttestation` there are no aggregation bits from which we can derive that. We use now the new field inside the `VersionedAttestation` - `ValidatorIndex`. This allows us to uniquely identify the validator alongside with the other keys. Note that the current changes **are not** compatible with deneb. There are multiple places …

*: bump go-eth2-client and update atts and aggs

---

.golangci.yml
app/errors/errors.go
app/errors/go113.go

Update golangci-lint name rule from `imports-blacklist` to `imports-blocklist` following the change from [this](https://github.com/mgechev/revive/pull/969) PR.
category: misc
ticket: none

ci: update golangci-lint name rule

---

app/peerinfo/peerinfo.go

Peerinfo protocol was logging nickname mappings every tick (1 minute) which leads to too much repeated information in logs.
Updated logic to only log when nicknames change.
ticket: none

app/peerinfo: reduce nickname mapping logs

---

eth2util/helpers.go
eth2util/helpers_test.go

Beacon node headers parsing would fail to parse a value containing equal sign, for example `Authorization=Basic bmljZXRyeQ==`.
Fixed validation and parsing logic to accept values with equal signs.
category: bug
ticket: none

eth2util: fix beacon node headers validation/parsing

---

cmd/createcluster.go

In `create cluster` using `--split-keys` charon loads keystores in unordered fashion. In other places we apply `SequencedKeys()` that sorts the keys by index. Applied the same logic to `create cluster` implementation.
category: bug
ticket: none

cmd: fixed loaded keys ordering

---

core/dutydb/memory.go
core/tracing.go
core/validatorapi/validatorapi.go

We have experienced issues with Prysm VC v5.3.0 running on Deneb. In comparison to the other 4 VCs tested, Prysm v5.3.0 was sending Deneb data to Electra-enabled v2 endpoints. Those v2 endpoints allow, by spec, deneb data, so it's not an issue per se supporting that. It required some fiddling on our end though.
category: bug
ticket: none

*: support v2 calls for deneb fork

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_test.go
app/eth2wrap/valcache_test.go
docs/metrics.md

Add `app_eth2_using_fallback` gauge metric to track how often nodes rely on fallback  beacon nodes.  This can be queried, for example, using promql `min_over_time(app_eth2_using_fallback[30s]) == 1` to see if any node has been only using the fallback beacon node for the last 30 seconds.
ticket: none

feat: add fallback beacon node metric

---

app/app.go
app/peerinfo/metrics.go
docs/metrics.md

Add `nickname` label to Prometheus metrics.
ticket: none

app: add nickname label to metrics

---

app/version/version.go

v1.3-rc release
category: misc
ticket: none

app: bump to v1.4-dev

---

core/validatorapi/router.go

Some VCs can force SSZ on all requests, even though they are not officially in the spec (i.e.: /eth/v1/validator/duties/attester/{epoch}). On 415 they fallback to JSON. However, those 415 fallbacks fail on our end because we officially support SSZ, but then on parsing the payload to SSZ we return 500.
category: bug
ticket: none

vapi: return 415 on ssz unmarshaling failures

---

app/eth2wrap/lazy.go
core/signeddata.go
core/unsigneddata.go

Since err != nil has been judged before, nil is returned directly here, which is more obvious, readable and less error-prone.
category: misc
ticket: none

refactor: return nil when error has already been checked

---

testutil/genchangelog/main.go

Two commits were crashing our parsing logic in `genchangelog`:
- https://github.com/ObolNetwork/charon/commit/82c9ee4135442aacb07a9dded5ffc104e560edc0 - body contains a character which was our field separator leading to broken parsing.
- https://github.com/ObolNetwork/charon/commit/c3caee9a38e90d7734c83db5ec65b82a31b2a724 - body contains a sequence of characters which our logic didn't correctly escape, specifically the sequence `\[!WARNING]\` contains a `\[` which must be escaped to `\\[` 
category: bug
ticket: none

*: fix PRs parsing

---

app/app.go
cmd/run.go
core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
core/fetcher/graffiti.go
core/fetcher/graffiti_internal_test.go
docs/configuration.md
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go
testutil/random.go

Allow users to set a global or per validator public key custom graffiti to their beacon block proposals.
Add two new CLI flags:
- `graffiti`: a comma-separated list of graffiti to add to beacon block proposals
- `graffiti-disable-client-append`: a boolean value to disable appending obol signature to custom graffiti.
ticket: #3608

app/fetcher: add custom graffiti

---

app/retry/retry.go
core/consensus/qbft/qbft.go
core/parsigdb/memory.go
core/sigagg/sigagg.go
core/tracing.go

Improved tracing spans data: added status codes, recording errors, etc. This is in particular useful with spanmetrics connector and raw traces rendering with grafana, as it gives more context. This barely increases network traffic, because we only track spans for Propose duty.
Fixed a bug in QBFT that prevented QBFT instance to stop promptly upon Decide. The instance was eventually terminating after the timeout - 60s, but this retained unnecessary memory and system handles. Now this finished QBFT protocol as soon as Decided is triggered. Also, this resulted in proper tracing span duration evaluation.
ticket: none

*: improving spans

---

app/app.go
app/eth2wrap/valcache.go
app/eth2wrap/valcache_test.go
app/vmock.go

Validator cache is refreshed at the start of the epoch. Previous behavior would request too many times causing issues with beacon node and had no fallback in case of complete failure.
This PR fixes this behavior according to what's described in ticket.
category: bug
ticket: #3636

*: fix validator cache behavior

---

app/app.go
app/tracer/trace.go

Tempo does not support indexing on `service.namespace` attribute which we use to reflect the cluster hash.
Therefore, Grafana Explore does not render a filter for this attribute.
To improve usability and querying performance, we combine 7-characters cluster hash and service name (node name): `{resource.service.name="fc7fc15/kurtosis-node1"}`. Such the combined service name would be pretty unique across all clusters and will simplify the search.
category: misc
ticket: none

app: combined service.name

---

app/eth2wrap/eth2wrap_test.go
app/eth2wrap/httpwrap.go

Before pectra we've checked if v2 endpoint exist or not. We expect post-pectra this endpoint to always exist and we default only to non-existing block, as before.
category: misc
ticket: none

app: remove check for unexisting v2 endpoint

---

core/tracker/inclusion.go
core/tracker/inclusion_internal_test.go

Check attestation inclusion in an easier way, by validator index, instead of aggregation bits, which was throwing false positives before.
category: bug
ticket: none

tracker: check inclusion by validx, instead of agg bits

---

core/ssz.go
core/ssz_test.go

Previously I've introduced SSZ marshaling of the validator index. In the rush, I didn't take into consideration that adding the marshaling to the new version will break compatibility with the previous version.
category: bug
ticket: none

core: fix incompatibility between v1.3/4.1 and v1.3/4.2

---

app/app.go

The tracer client has been created even though it was not configured by the client, which resulted in unwanted error messages:
```
traces export: failed to exit idle mode: dns resolver: missing address
```
This fix avoids tracing initialization if OTLP address it not configured.
category: bug
ticket: none

app: create tracer only when configured

---

core/tracker/inclusion.go

As now it is possible validator indices to be nil, because of previously introduced bug, double check if it is nil or not.
Validator index can be nil only if charon has received a partially signed attestation object from a peer on version v1.3.0, v1.3.1, v1.4.0 and v1.4.1, before it received it from its own VC.
This will result in charon not being able to check for inclusion.
category: bug
ticket: none

tracker: check for available validator index in inclusions

---

core/ssz.go
core/ssz_test.go
core/tracker/inclusion.go

Previously I've introduced SSZ marshaling of the validator index. In the rush, I didn't take into consideration that adding the marshaling to the new version will break compatibility with the previous version.
category: bug
ticket: none

core: fix incompatibility between v1.3.1 and v1.3.2

---

core/ssz.go
core/ssz_test.go
core/tracker/inclusion.go

Previously I've introduced SSZ marshaling of the validator index. In the rush, I didn't take into consideration that adding the marshaling to the new version will break compatibility with the previous version.
category: bug
ticket: none

core: validx incompatibility fix v1.4

---

.github/workflows/build-release-binaries.yml

The previous condition failed to run this action during v1.4.0 release. Now copied the trigger `on` rule from another job that is known to run properly during a release.
ticket: none

*: fixed build-release-binaries.xml

---

testutil/verifypr/verify.go

There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
ticket: none

testutil: use slices.Contains to simplify code

---

cluster/definition.go
testutil/verifypr/verify.go

We have hardcoded fork version inside `NewForT` utility function used to create lock and definition for testing.
A useful option to adjust that.
ticket: none

cluster: add WithForkVersion to definition

---

app/retry/retry.go
app/retry/retry_internal_test.go
app/retry/retry_test.go
core/deadline.go
core/deadline_test.go
testutil/integration/infosync_test.go

New custom duty deadlines in according with the design doc (proposal):
```
{
duty:             core.NewProposerDuty(currentSlot),
expectedDuration: slotDuration/3 + margin,
},
{
duty:             core.NewAttesterDuty(currentSlot),
expectedDuration: 2*slotDuration + margin,
},
{
duty:             core.NewAggregatorDuty(currentSlot),
expectedDuration: 2*slotDuration + margin,
},
{
duty:             core.NewPrepareAggregatorDuty(currentSlot),
expectedDuration: 2*slotDuration + margin,
},
{
duty:             core.NewSyncMessageDuty(currentSlot),
expectedDuration: 2*slotDuration/3 + margin,
},
{
duty:             core.NewSyncContributionDuty(currentSlot),
expectedDuration: slotDuration + margin,
},
{
duty:             core.NewRandaoDuty(currentSlot),
expectedDuration: slotDuration/3 + margin, …
```

*: custom duty deadlines

---

core/scheduler/scheduler.go
core/scheduler/scheduler_internal_test.go
core/scheduler/scheduler_test.go

Bugfix is to address the following edge case:
- Scheduler is fetching/resolving duties for a slot.
- GetDutyDefinition is called for the same slot at the same time (from VAPI).
- This resulted in failed VAPI request, because the epoch in question did not appear "resolved".
The fix will cause GetDutyDefinition to wait if Scheduler is in process of resolving duties for the requested epoch. This would prevent VAPI request to fail, but apparently it will delay the request by the time needed to complete all duties resolution.
category: bug
ticket: none

core/scheduler: bugfix

---

app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/httpwrap.go
app/eth2wrap/lazy.go
app/eth2wrap/mocks/client.go
app/eth2wrap/multi.go
app/featureset/featureset.go
app/featureset/featureset_internal_test.go
core/bcast/bcast.go
core/bcast/metrics.go
core/tracker/inclusion.go
core/tracker/inclusion_internal_test.go
core/tracker/metrics.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go
docs/metrics.md
testutil/beaconmock/beaconmock.go
testutil/beaconmock/beaconmock_fuzz.go
testutil/beaconmock/options.go

Previously was checked only the slot of the first attestation in a block, which caused some attestations submitted wrongly deemed as not included on-chain.
~TODO: Still to be tested on a Hoodi cluster before merging.~
After testing on Hoodi this seems to add A LOT of load on the beacon node. I have introduced caching of the state, but even that is putting a lot of stress. Calling for state on each slot is expensive. Sometimes those requests timeout and we again fail to check the attestation, as we don't have the data from the BN.
~I personally am in favour of removing the attestations for the on-chain inclusion tracking or delegating the whole on-chain inclusion tracking to a separate BN.~
It has been agreed to change the default scenario to not tracking attestations and aggregations, but …

*: check for attestation inclusion only under feature flag

---

.github/workflows/build-release-binaries.yml

This sets proper write permissions to the workflow to unblock creating release binaries.
ticket: none

*: set permissions to release script

---

app/eth1wrap/eth1wrap_test.go

Fix wait for client to initialize in tests using `defer close(clientCreatedCh)` instead of just `close(clientCreatedCh)` to ensure channel is only closed after returning the client.
category: bug
ticket: none

app/eth1wrap_test: fix flaky tests

---

.github/workflows/build-release-binaries.yml

Fixing dist folder ownership after the docker runs.
ticket: none

*: run chown after docker

---

core/deadline.go
core/deadline_test.go

For Teku VC we observed all duties were timed out due to insufficient duty timeout.
This change increases duty timeout margin from 0.5s to 1s (marginFactor=12) for Ethereum spec.
Having tested this change with Kurtosis, all duties appear to be working fine.
Note that Teku VC is the only VC type that needed this adjustment.
category: bug
ticket: none

core: increased duty timeout margin

---

cmd/test.go

For `alpha test` command, when `--publish` is specified and there is no private key present at `.charon/charon-enr-private-key`, the implementation will auto generate temporary private key that will not be matching any of real nodes on the backend, but still allows to proceed and publish.
ticket: none

cmd: test publish using temp enr key

---

core/scheduler/scheduler.go
core/signeddata.go
core/validatorapi/router_internal_test.go

Fixed some function names in comment.
ticket: none

core: fix some function names in comment

---

app/obolapi/api.go
app/obolapi/api_internal_test.go
app/obolapi/exit.go
cmd/cmd.go
cmd/exit_delete.go
cmd/exit_delete_internal_test.go
core/fetcher/fetcher.go
testutil/obolapimock/obolapi_exit.go

Delete partial exits from Obol API.
N.B.: The endpoint is `/exp/exit/{lockHash}/{shareIndex}/{valPubkey}`, while it should be `/exp/partial_exits/{lockHash}/{shareIndex}/{valPubkey}`. I've talked with Launchpad to change it, but in the meantime I submit the PR as it is currently.
ticket: #3798

*: delete partial exits

---

core/validatorapi/router.go

Endpoints with `404` handlers had empty encoding arrays leading to unsupported media type (`415`) status response instead of not found (`404`).
category: bug
ticket: none

core/validatorapi: add missing encoding types

---

core/consensus/qbft/transport.go
core/validatorapi/validatorapi.go
dkg/exchanger.go
testutil/beaconmock/server.go

There is a [new function](https://pkg.go.dev/maps@go1.21.1#Copy) added in the go1.21 standard library, which can make the code more concise and easy to read.
ticket: none

*: use maps.Copy for cleaner map handling

---

core/tracker/inclusion.go

Merged #3862 and forgot to rebase. #3867 renamed one of the variables which I forgot to update in #3862.
category: bug
ticket: none

core/tracker: fix tracker inclusion after PR clash

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_test.go

Restrict fallback beacon node calls to timeout or syncing issues instead of retrying on any error.
Prevent `usingFallback` metric flickering by setting gauge according to request response from primary beacon node.
ticket: #3869

app/eth2wrap: improve fallback logic and metric

---

cmd/run.go
cmd/run_internal_test.go
go.mod

Add external hostname verification to prevent users from passing `--p2p-external-hostname` with empty value followed by another flag.
ticket: none

cmd: add hostname verification

---

cmd/addvalidators.go
cmd/addvalidators_internal_test.go

Changed the `src-dir` and `dst-dir` flag names, description, default values and the description of the `unverified` flag.
ticket: none

cmd: renamed add-validators flags

---

dkg/dkg_test.go
testutil/compose/smoke/smoke_test.go

Checking outdated tests removal => compose tests shall succeed.
Also, disabled the annoying TestSyncFlow flakey test that must be reworked one day.
ticket: none

testutil: removed outdated smoke tests

---

app/app.go
app/featureset/featureset.go
core/fetcher/fetcher.go
core/fetcher/fetcher_test.go

Add feature flag to query the BN only for committee index 0 on attestation data request.
Charon nodes with VC versions greater or equal to the ones mentioned in the issue here can add it to reduce load to their BNs and potentially improve their cluster performance.
ticket: #3980 
feature_flag: fetch_only_commidx_0

*: attestations data fetch only committee index 0

---

app/eth2wrap/eth2wrap_test.go
tbls/tbls.go
testutil/obolapimock/obolapi_exit.go

Fix typos in `app/eth2wrap/eth2wrap_test.go`, `tbls/tbls.go`, `testutil/obolapimock/obolapi_exit.go` and improves language.
category: docs
ticket: none

docs: fix some a/an issues
