docs/dkg.md
Documenting charon taking over the DKG responsibilities. 
category:  docs
ticket: none
=> docs: draft DKG protocol

core/interfaces.go, core/validatorapi/eth2types.go, core/validatorapi/validatorapi.go, core/validatorapi/validatorapi_test.go, docs/architecture.md, testutil/validatormock/validatormock.go
Adds support to propose block to mock validator.
ticket: none
=> testutil/validatormock: add propose block to vmock

core/scheduler/scheduler_test.go, go.mod, go.sum
Had to manually bump #434 since the Clock interface changed so had to update a test.
category: misc
ticket: none
=> gomod: bump github.com/jonboulle/clockwork

docs/architecture.md
Documents the remote signer architecture and how it fits into the current core workflow.
category: docs
ticket: none
=> docs: spec remote signer architecture

app/app_test.go, app/manifest.go, app/manifest_test.go, app/simnet_test.go, testutil/beaconmock/options.go
Fixes manifest unmarshalling bug introduced with addition of bootnode relays.
category: bug
ticket: #449
=> app: fix manifest unmarshal

app/app.go, app/simnet_test.go, core/fetcher/fetcher_test.go, core/validatorapi/router.go, testutil/beaconmock/options.go
Adds block proposer integration test with teku.
category: test
ticket: none
=> app: add proposer test for teku

README.md
Fixes broken links and adds badges to readme.
category: docs
ticket: none
=> readme: fix and add badges

README.md, docs/README.md
Proposal to center title and tags: 
Before:
After:
category: docs
ticket: #000
=> docs: center title and tags

app/log/log.go
Fixes copy-paste bug introduced in #468.
ticket: none
=> app/log: fix counter

core/bcast/bcast.go, core/scheduler/scheduler.go
Adds logs for successful and failed broadcast in bcast component and improves logs in scheduler from debug to info
ticket: #000
featureset: stable
=> core: add logs for bcast and scheduler

dkg/dkg.go, dkg/forst.go, dkg/frost.go, dkg/frost_internal_test.go, dkg/keycast.go, dkg/keycast_internal_test.go
Implements a parallel Frost DKG using kryptology library and following example in `github.com/coinbase/kryptology/test/frost_dkg/bls/main.go`.
ticket: none
=> dkg: implement frost dkg

Dockerfile
Adds some more opencontainer metadata tags to Dockerfile
category: misc
ticket: #462
=> dockerfile: add more metadata tags

docs/structure.md
Adds ethutil package to the project structure documentation.
category: docs
ticket: none
=> docs: add eth2util to project structure

core/qbft/qbft_test.go, docs/contributing.md, testutil/validatormock/validatormock.go
Fixes build and pre-commit update instructions to contributing.md
ticket: none
=> docs: fix build and add pre-commit update to contributing

testutil/verifypr/verifypr.go
=> testutil/verifypr: fix lint

.github/pull_request_template.md, app/version/version.go, docs/branching.md
Updating charon version to `v0.4.0`. 
category: misc
ticket: none
=> app/version: cut v0.4.0

core/consensus/component.go, core/qbft/qbft.go
Fixes two small issue in qbft:
- Since we now do MsgDecided, MsgCommit is only applicable to the current round.
- Use more specific libp2p protocol for qbft to support others down the line.
category: misc
ticket: none
=> core/qbft: small tweaks

core/consensus/component.go, core/qbft/qbft.go, core/qbft/qbft_test.go
Refactors buffering to FIFO per peer to prevent DDoS of future round messages.
ticket: #524
=> core/qbft: refactor buffering to fifo

cmd/createcluster.go, core/qbft/qbft.go
Fixes build on main by improving cognitive complexity of runCreateCluster of createcluster.go
ticket: none
=> cmd: fix build on main

dkg/dkg.go
Add support for relays to charon dkg command.
ticket: none
=> dkg: add support for relays

core/consensus/transport.go, dkg/dkg.go, dkg/frost.go, dkg/frostp2p.go, dkg/transport.go
Fix wait and relay issues with DKG.
category: bug
ticket: none
=> dkg: fix some issues

testutil/compose/README.md
Adds a readme to compose
category: docs
ticket: #568
=> testutil/compose: add readme

cmd/createdkg.go
Adds a validation for withdrawal address for create dkg command.
category: bug
ticket: #582
=> cmd: validate withdrawal address for create dkg command

app/app.go, dkg/keycast.go, testutil/compose/config.go
Fix golang-ci lint issues.
ticket: none
=> golangci: fix build

app/version/version.go
Release version v0.5.0
category: misc
ticket: none
=> app/version: release v0.5.0

app/app.go, app/simnet_test.go
Enables deterministic block proposer duties for simnet. This allows compose (and all other cases of simnet) to trigger block proposal.
ticket: none
=> app: enable proposer duties for simnet

core/qbft/qbft.go
After adding a sanity check to the `isDuplicatedRule` function, I discovered that there was one case where the `changRound` function wasn't used.
category: bug
ticket: none
=> core/qbft: fix round change issue

core/bcast/bcast.go, core/leadercast/leadercast.go, core/leadercast/transport.go, core/parsigex/parsigex.go, core/scheduler/scheduler.go, testutil/beaconmock/options.go
Improve logging in core workflow. Add proper topics. Remove duplicate beacon mock logs.
ticket: none
=> core: improve logging

dkg/dkg.go
Add more debug/info logs to dkg ceremony
ticket: #587
=> log: add logs to dkg

.bulldozer.yml
Adds a separate merge method to handle dependabot PRs.
category: misc
ticket: #653
=> bulldozer: update bulldozer config to handle dependabot

.bulldozer.yml
Reverting bulldozer config.
category: misc
ticket: #653
=> bulldozer: reverting changes

app/simnet_test.go, core/deadline.go, core/parsigdb/memory.go, core/validatorapi/router.go, core/validatorapi/validatorapi.go, testutil/beaconmock/options.go, testutil/beaconmock/server.go
Adds a no-network Teku VC integration test for exit duties.
category: test
ticket: #553
=> app: add exit test

app/version/version.go
Release charon version v0.6.0 🚀
category: misc
ticket: none
=> app/version: charon v0.6.0

.github/workflows/release.yml, docs/branching.md
Auto-generates changelog in github action. Also simplify by removing usage of docker image and just use local code.
category: misc
ticket: #320
=> github/workflows: auto generate changelog

dkg/dkg.go, p2p/sender.go
Improve DKG networking
ticket: none
=> dkg: improve networking

core/scheduler/scheduler.go
Logs if attester duties missing when fetching duties for epoch.
category: misc
ticket: #664
=> core/scheduler: log missing attester duties

core/validatorapi/router.go
Fixes 400 vs 500 logic bug by removing logic.
category: bug 
ticket: none
=> core/validatorapi: fix 400 vs 500 errors

p2p/ping.go
Adds rtt to ping success/restored logs.
category: misc
ticket: none
=> p2p: add rtt to ping logs

app/app.go, core/bcast/bcast.go, core/bcast/bcast_test.go, core/bcast/metrics.go, core/consensus/component.go, core/leadercast/leadercast.go, core/parsigdb/memory.go, core/parsigex/parsigex.go, core/sigagg/sigagg.go, core/validatorapi/validatorapi.go
Instruments duty broadcast delay after slot start.
Also fix logging contexts.
category: misc
ticket: none
=> core/bcast: instrument broadcast delay

cmd/bootnode.go
=> cmd: fixbuild

app/featureset/config_test.go, app/featureset/featureset.go, app/simnet_test.go
Upgrade `qbft_consensus` to stable release.
ticket: #714 
feature_flag: qbft_consensus
=> featureset: upgrade qbft_consensus to stable

.github/workflows/build.yml
Reverts ObolNetwork/charon#723
I will revert this PR until Oisin adds the token or allows access between charon and charon-k8s repos, otherwise, the workflow fails.
@xenowits ^^
category: misc
ticket: none
=> build: revert PR #723

dkg/sync/server.go
Fixes flapping sync test. 
Ref: https://github.com/ObolNetwork/charon/runs/6949467484?check_suite_focus=true
ticket: #684
=> dkg: fix flapping sync test

dkg/sync/client.go, dkg/sync/server.go, dkg/sync/sync_internal_test.go, dkg/sync/sync_test.go
Implements AwaitConnected method of sync.Client
ticket: #684
=> dkg/sync: implement client.AwaitConnected

dkg/sync/server.go
Fixes golangci-lint build on main.
ticket: none
=> build: fix golangci-lint

dkg/sync/client.go, dkg/sync/server.go, dkg/sync/sync_test.go
Implements await shutdown methods on sync.Client and sync.Server
ticket: #684
=> dkg/sync: implement await shutdown

core/scheduler/clocksync.go
Fixes linter issue.
ticket: none
=> core/scheduler: fix lint

dkg/dkg.go
Fix golangci-lint build on main
ticket: none
=> build: fix build on main

docs/architecture.md
Add data flow indication, push vs pull.
category: docs
ticket: none
=> docs: improve architecture diagram

README.md
Add block proposal ✅ to README.
category: misc
ticket: none
=> readme: add block proposal to README

core/deadline.go, core/deadline_test.go
Adds implementation for deadliner interface
ticket: #768
=> core/deadline: add deadline implementation

core/deadline.go, core/deadline_test.go
Addresses comments on earlier PR: #805 
ticket: #768
=> core/deadline: cleanup deadline.go

core/types.go, core/types_test.go
- Addition of the DutyBuilderProposer in types.go 
- Updated related tests in types_test.go
Unsure of team preference on feature flag.
ticket: #809
=> core: addition of the DutyBuilderProposer in types.go

core/aggsigdb/memory.go
Rename db.closedCh to db.quit and refactor Run method.
ticket: none
=> core/aggsigdb: refactor aggsigdb

cluster/cluster_test.go, cluster/definition.go, cluster/testdata/TestEncode_definition_json.golden, cluster/testdata/TestEncode_definition_yaml.golden, cluster/testdata/TestEncode_lock_json.golden, cluster/testdata/TestEncode_lock_yaml.golden, cluster/testdata/definition_v1_0_0.json, cluster/testdata/definition_v1_1_0.json, cluster/testdata/lock_v1_1_0.json
Fixes the latest cluster definition version, it should be v1.1.0 as per feedback in previous PR.
category: bug
ticket: #710
=> cluster: fix definition version

core/bcast/bcast.go, core/bcast/bcast_test.go
-  broadcast implementation for builder proposer
- relevant test added
ticket: #809
=> core/bcast: add support for duty builder proposer

docs/architecture.md
- Architecture document update
ticket: #809
=> docs: architecture md update for builder proposer

core/signeddata.go, core/signeddata_test.go, go.mod, go.sum, testutil/random.go
- addition of signeddata implementation
- added test case
- added SignedValidatorRegistration to testutils random
- update of go-eth2-version
ticket: #849
=> core: signeddata implementation for builder registration

.github/workflows/test.yml, app/app.go, app/lifecycle/order.go, app/lifecycle/orderstart_string.go, app/simnet_test.go, core/deadline.go, core/deadline_test.go, core/tracker/metrics.go, core/tracker/tracker.go, core/tracker/tracker_internal_test.go
Wire tracker in core workflow. Implement failed duty reporter.
Also fix concurrency deadlock between Tracker and Deadliner.
ticket: #768
=> app: wire tracker

app/eth2wrap/eth2wrap_gen.go, core/validatorapi/router.go, core/validatorapi/router_internal_test.go, core/validatorapi/validatorapi.go, core/validatorapi/validatorapi_test.go, eth2util/signing/signing.go, go.sum, testutil/random.go, testutil/validatormock/validatormock.go
**WORK IN PROGRESS**
- Updates to router
- Updates to vapi
ticket: #849
=> core/validatorapi: validatorapi implementation builder registration

p2p/relay.go
This reduces libp2p circuit relay reservations to the required minimum. Previously, we re-reserved on "client connection timeout" of 2s which is not required since server-side reservations remain open when client-side connections are recycled. This resulted in multiple open reservations which quickly results in "reservation-rejected" errors. 
category: bug
ticket: none
=> p2p: decrease circuit relay reservation frequency

eth2util/signing/signing.go, eth2util/signing/signing_test.go, testutil/random.go
Adds NewVerifyFunc in eth2util/signing.
ticket: #217
=> eth2util/signing: add NewVerifyFunc

app/app.go, app/simnet_test.go, core/validatorapi/validatorapi.go, core/validatorapi/validatorapi_test.go, eth2util/signing/signing.go, testutil/random.go, testutil/validatormock/validatormock.go
Adds builder registration to simnet tests.
category: test
ticket: #849
=> app: add registration simnet test

core/validatorapi/validatorapi.go, core/validatorapi/validatorapi_test.go, eth2util/signing/signing.go, eth2util/signing/signing_test.go, testutil/validatormock/validatormock.go
Adds verifyFunc to Validatorapi component and removes old methods.
ticket: #217
=> core/validatorapi: add verifyFunc to validatorapi

core/validatorapi/validatorapi.go
=> core/validatorapi: fix lint

core/parsigdb/memory.go, core/parsigdb/metrics.go, core/scheduler/metrics.go, core/scheduler/scheduler.go, testutil/compose/static/grafana/dash_simnet.json
Count number of partial voluntary exits received per validator. Also count number of active validators.
ticket: #907
=> core/parsigex: instrument voluntary exits

cmd/createcluster.go, cmd/createdkg.go, dkg/dkg.go, eth2util/deposit/deposit.go
- add ropstent to  create cluster / create dkg commands
see https://github.com/eth-clients/merge-testnets/blob/main/ropsten-beacon-chain/README.md for the source of ropsten GENESIS_FORK_VERSION: 0x80000069
ticket: #849
=> cmd: add ropsten to the create cluster / create dkg commands

app/forkjoin/forkjoin.go, app/forkjoin/forkjoin_test.go
Implements a generic forkjoin package.
ticket: none
=> app/forkjoin: implement generic forkjoin

app/app.go
=> app: fix lint

cluster/helpers.go, cmd/createcluster.go, cmd/createcluster_internal_test.go, cmd/createdkg.go, cmd/createdkg_internal_test.go, testutil/compose/compose/smoke_internal_test.go
Refactors `--threshold` flag to default to safe value if zero. Add logging if unsafe override provided.
ticket: #894
=> cmd: safe default threshold

app/monitoringapi.go, app/monitoringapi_internal_test.go
Fixes flapy test in monitoringapi_internal_test.
category: test
ticket: #886
=> app: fix flapy test in monitoringapi_internal_test

app/app.go, app/lifecycle/order.go, app/lifecycle/orderstart_string.go, p2p/metrics.go, p2p/p2p.go, testutil/compose/static/grafana/dash_simnet.json
Adds autonat reachability metrics. Also add panel to simnet dash,
ticket: none
=> p2p: autonat status

app/errors/errors.go, app/eth2wrap/eth2wrap.go, app/forkjoin/forkjoin.go, app/lifecycle/manager.go, app/log/log.go, app/retry/retry.go, cluster/doc.go, core/priority/calculate.go, core/priority/prioritiser.go, core/types.go, testutil/beaconmock/beaconmock.go, testutil/compose/compose/main.go, testutil/genchangelog/main.go
Fixes golangci-lint.
ticket: none
=> app: fix golangci-lint

go.mod
Remove unused replace directive in go.mod. 
category: misc
ticket: none
=> gomod: remove unused replace directive

.github/workflows/golangci-lint.yml, .golangci.yml, app/errors/errors.go, app/eth2wrap/eth2wrap.go, app/forkjoin/forkjoin.go, app/lifecycle/manager.go, app/log/log.go, app/retry/retry.go, cluster/doc.go, core/priority/calculate.go, core/priority/prioritiser.go, core/types.go, testutil/beaconmock/beaconmock.go, testutil/compose/compose/main.go, testutil/genchangelog/main.go
Reverts ObolNetwork/charon#948
ticket: none
=> app: reverts fix golangci-lint

p2p/metrics.go, p2p/relay.go, testutil/compose/static/grafana/dash_simnet.json
Instrument relay connectedness, also re-reserve if connection lost.
ticket: none
=> p2p: instrument relay connections

app/simnet_test.go
Adds a builder proposer simnet test using teku VC.
ticket: #809
=> app: add teku builder proposer test

app/app.go, core/parsigex/parsigex.go, core/parsigex/parsigex_test.go, dkg/dkg.go, dkg/exchanger.go, dkg/exchanger_internal_test.go, testutil/random.go
Adds verification function to parsigex and related constructors for verifyFunc: NewEth2Verifier and newDKGVerifier.
ticket: #217
=> core/parsigex: add verification function to parsigex

dkg/dkg.go, dkg/dkg_internal_test.go
Adds partial signature verification before aggregation.
ticket: #217
=> dkg: add verification of partial signature

app/app.go, core/dutydb/memory.go, core/dutydb/memory_test.go
Trim expired duties in dutydb.
ticket: #974
=> core/dutydb: trim expired duties

core/consensus/component.go
Improve "receive buffer ..." logging.
category: misc
ticket: none
=> core/consensus: improve p2p receive logging

README.md
Mark BlindedBeaconBlock complete with Teku VC
category: docs
ticket: none
=> readme: mark blinded-beacon-block duty successful with teku

README.md
Update lighthouse to mark BlindedBeaconBlock complete. Also list the progress on the rest of the clients
category: docs
ticket: none
=> readme: list all of the rest of the clients we need to support

app/app.go, app/eth2wrap/eth2wrap.go, p2p/discovery.go, p2p/p2p.go
Log named p2p addresses where applicable. Also add missing ctx cancel to eth2wrap.
category: misc
ticket: none
=> p2p: log named addresses

app/forkjoin/forkjoin.go, app/version/version.go, docs/configuration.md
- Bumps version to v0.10.0
- Document definition changes for v1.2
- Improve forkjoin docs.
category: misc
ticket: none
=> app/version: prep for release v0.10.0

testutil/genchangelog/main.go
Running `genchangelog` with the unauthenticated Github API can easily result in rate-limited errors. Providing a `GITHUB_TOKEN` switches the authenticated API which mitigates this.
Errors were:
```
API rate limit exceeded for 102.132.225.76. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
category: misc
ticket: none
=> testutil/genchangelog: support optional authenticated API

p2p/bootnode.go, p2p/discovery_internal_test.go
Improve resolving bootnode ENR backoff.
ticket: none
=> p2p: improve resolving bootnode backoff

testutil/compose/static/grafana/dash_simnet.json
Refactor rate intervals to recommended `$__rate_interval` and update some single value panels to `instant`.
No significant changes to UI.
category: misc
ticket: none
=> testnet/compose: clean simnet dash

app/app.go, core/scheduler/metrics.go, core/scheduler/scheduler.go, testutil/compose/static/grafana/dash_simnet.json
Adds validator balance metric in scheduler.
category: misc
ticket: #981
=> core/scheduler: add validator balance

.github/workflows/track-pr.yml, testutil/trackpr/main.go, testutil/trackpr/track.go
Only track PRs when merged.
category: misc
ticket: none
=> testutil/trackpr: fix pr tracker

dkg/disk_internal_test.go
Refactor `dkg/disk_internal_test.go`.
category: test
ticket: none
=> dkg: refactor tests

core/bcast/bcast.go, core/bcast/bcast_test.go, core/types.go, testutil/random.go
Add `DutyPrepareAggregator` to bcast component.
ticket: #1068
=> core/bcast: add DutyPrepareAggregator to bcast

tbls/tss_test.go
Adds a bls signature verification benchmark test.
category: test
ticket: none
=> tbls: add signatures verification benchmark test

cluster/helpers.go, cluster/ssz.go, cmd/createcluster.go
Fix lint and improve ssz errors.
ticket: none
=> *: fixlint

testutil/compose/lock.go, testutil/compose/run.go, testutil/compose/static/grafana/dash_simnet.json, testutil/compose/testdata/TestDockerCompose_lock_dkg_template.golden, testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden, testutil/compose/testdata/TestDockerCompose_run_template.golden, testutil/compose/testdata/TestDockerCompose_run_yml.golden
Also update simnet dashboard.
category: misc
ticket: none
=> testutil/compose: remove deprecated flag

eth2util/eth2exp/attagg_internal_test.go, eth2util/eth2exp/attagg_test.go
Refactor eth2exp tests.
category: test
ticket: none
=> eth2exp: refactor tests

core/dutydefinition.go, core/interfaces.go, core/scheduler/offset.go, core/scheduler/scheduler.go, core/scheduler/scheduler_test.go, core/scheduler/testdata/TestSchedulerDuties_grouped.golden, core/scheduler/testdata/TestSchedulerDuties_spread.golden, core/scheduler/testdata/TestSchedulerDuties_spread_errors.golden
Add support for `DutyAggregator` to package `scheduler`.
ticket: #1075
=> core/scheduler: add support for DutyAggregator

testutil/compose/compose/smoke_internal_test.go, testutil/compose/config.go, testutil/compose/docker-compose.template, testutil/compose/run.go, testutil/compose/static/grafana/datasource.yml, testutil/compose/static/loki/loki.yml, testutil/compose/template.go, testutil/compose/testdata/TestDockerCompose_define_create_template.golden, testutil/compose/testdata/TestDockerCompose_define_create_yml.golden, testutil/compose/testdata/TestDockerCompose_define_dkg_template.golden, testutil/compose/testdata/TestDockerCompose_define_dkg_yml.golden, testutil/compose/testdata/TestDockerCompose_lock_create_template.golden, testutil/compose/testdata/TestDockerCompose_lock_create_yml.golden, testutil/compose/testdata/TestDockerCompose_lock_dkg_template.golden, testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden, testutil/compose/testdata/TestDockerCompose_run_template.golden, testutil/compose/testdata/TestDockerCompose_run_yml.golden, testutil/compose/testdata/TestNewDefaultConfig.golden
Add loki logging driver support to compose.
ticket: none
=> testutil/compose: add loki logging driver

core/dutydb/memory.go, core/dutydb/memory_test.go, core/interfaces.go, core/unsigneddata.go, core/validatorapi/validatorapi.go
Adds support for duty aggregator to dutydb.
ticket: #1115
=> core/dutydb: add aggregator duty

core/unsigneddata_test.go
Adds table tests for unsigned data implementations.
category: test
ticket: none
=> core: add table tests for unsigned data

core/fetcher/fetcher.go, core/fetcher/fetcher_test.go, core/interfaces.go
Query DutyDB for attestation data to fetch aggregated attestation for DutyAggregator.
ticket: #1146
=> core/fetcher: query dutydb for attestation data

app/app.go, app/metrics.go, dkg/dkg.go, testutil/compose/static/grafana/dash_simnet.json
Add metric for current `network`/`chain`. Also, add updated simnet dashboard.
ticket: none
=> cluster: add metric for current network

app/app.go, app/metrics.go, testutil/compose/static/grafana/dash_simnet.json
Add updated simnet dashboard.
category: misc
ticket: none
=> cluster: updated simnet dashboard

app/metrics.go
Set initial network gauge to 1.
category: misc
ticket: none
=> cluster: set network gauge to 1

cluster/helpers_internal_test.go
Add tests for `cluster.verifySig` function.
category: test
ticket: none
=> cluster: add tests for verifySig function

core/tracker/tracker.go, core/unsigneddata.go, dkg/dkg.go
Fix linter by extracting `analyseFetcherFailed` function.
ticket: none
=> core/tracker: fix lint

core/tracker/metrics.go, core/tracker/tracker.go, testutil/compose/compose/main.go, testutil/compose/config.go, testutil/compose/static/grafana/dash_simnet.json
Adds participation counter metric.
Fixes unexpected event logic for `DutyPrepareAggreagtor`.
Updates simnet dashboard.
ticket: #1109
=> core/tracker: add participation counter

app/retry/retry.go
Integration tests are flapping due to timeout during shutdown in retryer. Add logging to see which action is causing this.
category: misc
ticket: none
=> app/retryer: add logging to debug shutdown timeout flapper

core/tracker/tracker.go
Remove nested if/else from `tracker.analyseFetcherFailed`
ticket: none
=> tracker: remove nested if/else from `tracker.analyseFetcherFailed()`

core/bcast/bcast_test.go
Refactor `bcast_test.go` into table tests.
ticket: #921
=> core/bcast: refactor tests

.github/workflows/codeql-analysis.yml
Create codeql analysis pipeline for security scanning. https://github.com/ObolNetwork/charon/issues/1195
category: misc
ticket: #1195
=> security: create codeql-analysis pipeline

app/version/version.go
Bump version to v0.10.1. 
category: misc
ticket: none
=> app/version: bump to v0.10.1

core/priority/prioritiser.go, core/priority/prioritiser_test.go, p2p/receive.go, p2p/receive_test.go, p2p/sender.go
Fixes the priority protocol basic implementation and unit test.
category: test
ticket: #1207
=> core/priority: implement basic unit test

app/app.go, app/lifecycle/order.go, app/lifecycle/orderstart_string.go, app/peerinfo/peerinfo.go, testutil/compose/static/grafana/dash_simnet.json
Wires the peerinfo protocol, also adds the clockoffset to the simnet dash.
ticket: #1224
=> app: wire peerinfo protocol

core/parsigex/parsigex.go
Fix `gocognit` linter issue.
ticket: none
=> core/parsigex: fix lint

cmd/run.go
Adds `wrapPreRunE` function to `cmd/run.go`.
category: misc
ticket: none
=> cmd: add `wrapPreRunE` function

core/priority/prioritiser.go, dkg/sync/server.go
=> dkg: fix lint

app/log/config.go, core/fetcher/fetcher_test.go, eth2util/eth2exp/attagg_test.go
Fix lint and missed PR comments.
ticket: none
=> *: fix lint

core/parsigdb/memory.go, core/parsigdb/memory_internal_test.go
Ensure all partially signed data matches before aggregating (not just `SyncCommMsg`). This mitigates against an attack where byzantine peers send correct partial signatures, but incorrect data resulting in undefined behaviour.
category: bug
ticket: none
=> core/parsigex: check all partial signed data before aggregating

app/lifecycle/hook.go
Includes a stack dump in the error when lifecycle times out on shutdown. This is to figure out why tests are flapping due to shutdown timeout.
category: misc
ticket: none
=> app/lifecycle: include stackdump on shutdown timeout

app/retry/retry.go, app/retry/retry_test.go, core/deadline_test.go, core/retry.go
Improve logging of retry component:
- Use topic of component being retried
- Do not log on shutdown
ticket: #959
=> app/retry: improve logging

core/validatorapi/eth2types.go, core/validatorapi/router.go
Adds a stub `execution_optimistic` field as false to the relevant endpoints.
category: misc
ticket: none
=> core/validatorapi: add stub execution_optimistic field

core/tracker/tracker.go, core/tracker/tracker_internal_test.go, core/types.go
Adds sync committee duties support to tracker.
ticket: #1298
=> core/tracker: add sync duties to tracker

testutil/compose/static/grafana/dash_charon_overview.json
Updates overview dashboard, improving completed and failed duty panels to "status history" graphs instead of timeseries.
category: misc
ticket: none
=> testutil/compose: update overview dashboard

testutil/compose/static/grafana/dash_charon_overview.json
Improves overview dashboard:
- add data links to navigate to log explorer for errors and failed duties
- group failed duties by type
category: misc
ticket: none
=> testutil/compose: improve overview dashboard

core/tracker/tracker.go, core/tracker/tracker_internal_test.go, testutil/compose/static/grafana/dash_charon_overview.json
Do not mark sync message as unexpected since we do not schedule SyncContribution yet.
category: bug
ticket: none
=> core/tracker: sync message never unexpected

p2p/relay.go
Improves relay refreshing logic.
category: misc
ticket: none
=> p2p: improve relay refreshing

testutil/compose/static/grafana/dash_charon_overview.json
Adds `uptime` to overview dashboard.
category: misc
ticket: none
=> testutil/compose: add uptime to overview dash

app/app.go, app/retry/retry.go, core/deadline.go, core/tracker/tracker.go, core/tracker/tracker_internal_test.go, testutil/compose/static/grafana/dash_charon_overview.json
Adds a minimum deadline of 30s. This is mostly for local simnet which had warnings and errors due to super fast slots combined with high CPU usage due to new duties which slows things down.
Also improve overview dash:
- fix data link
- Remove sync message time column
category: misc
ticket: none
=> core: add minimum deadline

cluster/cluster_internal_test.go, cluster/cluster_test.go, cluster/definition.go, cluster/distvalidator.go, cluster/helpers.go, cluster/lock.go, cluster/operator.go, cluster/ssz.go, cluster/testdata/cluster_definition_v1_4_0.json, cluster/testdata/cluster_lock_v1_4_0.json, cluster/version.go, docs/configuration.md
Adds cluster creator to new draft definition v1.4.
ticket: #1360
=> cluster: add creator to draft v1.4

core/parsigex/parsigex.go, core/parsigex/parsigex_test.go, core/signeddata.go, core/types.go, core/validatorapi/validatorapi.go, core/validatorapi/validatorapi_test.go, eth2util/helpers.go, eth2util/signing/signing.go, eth2util/signing/signing_test.go, testutil/beaconmock/attestation.go, testutil/random.go, testutil/validatormock/attest.go, testutil/validatormock/synccomm.go, testutil/validatormock/synccontributionflow_test.go, testutil/validatormock/validatormock.go
Refactors signature verification logic to simplify for each signed data.
ticket: #920
=> eth2util/signing: refactor signature verification

core/bcast/bcast.go, core/bcast/bcast_test.go, core/signeddata.go, core/signeddata_test.go, testutil/random.go
Broadcast signed sync committee contribution.
ticket: #1269
=> core/bcast: broadcast sync committee contribution

core/validatorapi/eth2types.go, core/validatorapi/router.go, core/validatorapi/router_internal_test.go, core/validatorapi/validatorapi.go, core/validatorapi/validatorapi_test.go, testutil/beaconmock/options.go
Adds support for DutyPrepareSyncContribution to validatorapi.
ticket: #1260
=> core/validatorapi: add support for PrepareSyncContribution to vapi

README.md
Updates project status to indicate successful sync committee message on ropsten with teku.
category: docs
ticket: none
=> readme: update project status

.github/workflows/build-push-deploy.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/track-pr.yml, .github/workflows/verify-pr.yml
Updates github actions for `actions/setup-go@v3`, `actions/cache@v3` and `docker/build-push-action@v3`.
ticket: none
=> github: update workflows

app/app.go, app/app_test.go, core/priority/component.go, core/priority/prioritiser.go, core/priority/prioritiser_test.go
Wires the priority protocol and add integration test.
ticket: #1380
=> app: wire prioritise

app/eth2wrap/eth2wrap_test.go, app/eth2wrap/httpwrap.go
Revert validator cache that is causing problems.
ticket: #1396
=> app/eth2wrap: revert validator cache

app/app.go, app/simnet_test.go, core/scheduler/scheduler_test.go, testutil/beaconmock/options.go, testutil/compose/static/grafana/dash_charon_overview.json
Decrease simnet sync committee duties from "100%" to "2 out of 16".
category: test
ticket: none
=> testutil/beaconmock: decrease simnet sync committee duties

app/app.go, app/app_test.go, cluster/definition.go, cluster/operator.go, cluster/operator_internal_test.go, p2p/peer.go
Explicitly adds peer addresses for testing to improve connectively during tests.
category: test
ticket: none
=> app: improve p2p connections in test

p2p/metrics.go, p2p/p2p.go
Instrument connection duration to debug high connection rate in gcp clusters.
category: misc
ticket: none
=> p2p: intstrument connection duration

core/priority/prioritiser.go
=> core/priority: fix lint

core/priority/prioritiser_test.go
Fixes flapping test. Not sure why this passes at all.
ticket: none
=> core/priority: fix flapping test

app/app_test.go, cluster/cluster_test.go, cluster/definition.go, cluster/operator.go, cluster/operator_internal_test.go
Fix zero peer index 😱 introduced by #1411
category: bug
ticket: none
=> cluster: fix peer index

.github/workflows/test.yml, testutil/compose/auto.go, testutil/compose/compose/main.go, testutil/compose/smoke/smoke_test.go
Adds log file flag to compose auto command to upload logs to github action artefacts.
category: misc
ticket: #992
=> testutil/compose: upload smoke test logs to github action artefacts

app/peerinfo/metrics.go, app/peerinfo/peerinfo.go, testutil/compose/static/grafana/dash_charon_overview.json
Adds the `app_peerinfo_index` gauge to peerifnfo package and the overview dashboard.
ticket: none
=> app/peerinfo: instrument peer index

README.md
Marks attestation duty as completed for vouch ✅ .
category: docs
ticket: none
=> readme: mark attestation duty as completed for vouch

app/app.go, core/tracker/incldelay.go
Wire inclusion delay tracker
ticket: #1446
=> app: wire inclusion delay tracker

app/eth2wrap/synthproposer_test.go, core/validatorapi/router.go, testutil/beaconmock/options.go
Adds a unit test for synthetic proposals.
category: test
ticket: #1486
=> app/eth2wrap: add synthetic blocks unit test

core/validatorapi/router.go, core/validatorapi/router_internal_test.go
Improves query parameter handling in `validatorapi.Router` and adds a few tests.
category: misc
ticket: none
=> core/validatorapi: improve query param handling and errors

testutil/validatormock/validatormock.go
Adds context to http GET request in validatormock to get blocks.
category: bug
ticket: #1527
=> testutil/validatormock: add context to validatormock httpGet

dkg/dkg.go, dkg/dkg_internal_test.go, dkg/dkg_test.go, dkg/sync/client.go, dkg/sync/server.go, dkg/sync/sync_test.go
Refactors dkg sync protocol to reconnect in connecting to peers phase.
ticket: #1475
=> dkg: refactor dkg to reconnect to connecting phase

core/consensus/component.go, p2p/metrics.go, p2p/receive.go, p2p/sender.go
Adds counter for p2p network rx and tx bytes per peer and protocol.
ticket: none
=> p2p: instrument network throughput

.github/workflows/test.yml
Upload smoke test artefacts always.
category: test
ticket: none
=> workflows: upload artefacts always

dkg/sync/client.go, dkg/sync/server.go
Add peer disconnected log to server.
category: misc
ticket: none
=> dkg/sync: add disconnect log to server

core/consensus/component.go
Improves consensus component logging:
- Fix incorrect wrapping of nil errors
- Improve "timeout" logs
- Fix incorrect select statement that never actually waited.
ticket: none
=> core/consensus: improve logging

app/monitoringapi.go, testutil/promrated/prometheus.go
Fixes golangci-lint.
ticket: none
=> app/monitoringapi: fix lint on main

app/metrics.go, app/monitoringapi.go
Fixing again.  Golangci-lint really doesn't like commented out code as it thinks it is comments, best is to remove completely.
ticket: none
=> app: fix lint again

testutil/promrated/Dockerfile
Fixes location for binary
category: bug
ticket: https://github.com/ObolNetwork/charon/issues/1540
=> testutil/promrated: fix promrated dockerfile

app/eth2wrap/synthproposer.go, app/eth2wrap/synthproposer_test.go, core/bcast/bcast_test.go, core/dutydb/memory_test.go, core/eth2signeddata_test.go, core/fetcher/fetcher.go, core/fetcher/fetcher_test.go, core/parsigex/parsigex_test.go, core/proto_test.go, core/sigagg/sigagg_test.go, core/signeddata.go, core/signeddata_test.go, core/tracker/tracker_internal_test.go, core/unsigneddata.go, core/unsigneddata_test.go, core/validatorapi/eth2types.go, core/validatorapi/router.go, core/validatorapi/router_internal_test.go, core/validatorapi/validatorapi_test.go, testutil/beaconmock/options.go, testutil/random.go, testutil/validatormock/validatormock.go
Adds support for capella blocks.
ticket: #1464
=> core: add support for capella blocks

testutil/beaconmock/options.go, testutil/validatormock/synccomm.go, testutil/validatormock/synccomm_internal_test.go
Fixes bug in getSubcommittees function which led to missing sync contribution duties.
category: bug
ticket: none
=> testutil/validatormock: fix getSubcommittees bug

core/aggsigdb/memory_internal_test.go
Fixes flapping [test](https://github.com/ObolNetwork/charon/actions/runs/3873088789/jobs/6602699504) due to race condition between context cancel and storing data.
category: test
ticket: none
=> core/aggsigdb: fix flapping test

core/scheduler/scheduler_test.go
Fixes flapping [test](https://github.com/ObolNetwork/charon/actions/runs/3884037130/jobs/6626068205).
ticket: none
=> core/scheduler: fix flapping test

eth2util/enr/enr.go, eth2util/enr/enr_test.go, go.mod
Adds minimal ENR implementation.
ticket: #1608
=> eth2util/enr: port minimal implementation

app/version/version.go
Bumps version to v0.13
category: misc
ticket: none
=> app/version: bump to v0.13

.github/workflows/label-issues.yml
Adds "protocol" labels to issues in this repo.
category: misc
ticket: none
=> github/workflows: auto label issues

eth2util/keymanager/keymanager_test.go
Improves keymanager tests.
category: test
ticket: #1502
=> keymanager: improve tests

app/eth2wrap/eth2wrap.go, app/eth2wrap/eth2wrap_gen.go, app/eth2wrap/genwrap/genwrap.go, app/eth2wrap/httpwrap.go, app/metrics.go, app/monitoringapi.go, testutil/beaconmock/beaconmock.go, testutil/beaconmock/options.go, testutil/compose/static/grafana/dash_charon_overview.json
Adds beacon node peer count metric gauge.
ticket: #1603
=> app: add beacon node peer count metric

cluster/cluster_test.go
=> cluster: add nolint and godoc

core/fetcher/fetcher_test.go
Fixes golangci-lint on main: https://github.com/ObolNetwork/charon/actions/runs/4006805729/jobs/6878803352
ticket: none
=> core/fetcher: fix golangci-lint in fetcher_test

.github/workflows/golangci-lint.yml, .golangci.yml, .pre-commit-config.yaml, cmd/enr_internal_test.go
Fixes failing lint in main and updates linter to latest version.
ticket: none
=> golangci: fix lint and updater linter

.golangci.yml, app/app.go, app/errors/errors.go, app/eth2wrap/httpwrap.go, app/eth2wrap/synthproposer.go, cluster/definition.go, cmd/relay/p2p.go, core/deadline.go, core/infosync/infosync.go, core/qbft/qbft.go, core/tracker/tracker.go, core/tracker/tracker_internal_test.go, dkg/dkg.go, eth2util/keymanager/keymanager.go, p2p/p2p.go, testutil/genchangelog/main_internal_test.go, testutil/validatormock/validatormock.go
Fixes lints raised by upgraded golangci-lint, also improves lint config.
ticket: none
=> *: fix multiple lints

cmd/createcluster.go, dkg/disk.go, eth2util/hash.go, eth2util/keymanager/keymanager_test.go, testutil/random.go
Remove randomHex from testutil and add to eth2util package.
ticket: none
=> eth2util: remove randomHex from testutil

cluster/cluster_internal_test.go, cluster/helpers.go, cluster/helpers_internal_test.go, cluster/test_cluster.go, cmd/createcluster.go, cmd/createcluster_internal_test.go, cmd/createdkg.go, core/consensus/msg_internal_test.go, core/fetcher/fetcher_test.go, dkg/disk.go, dkg/dkg.go, dkg/sync/sync_test.go, eth2util/deposit/deposit.go, eth2util/helpers.go, testutil/random.go
Port over uses of geth crypto packages.
ticket: #1626
=> *: migrate uses of geth code

cluster/helpers.go, cluster/helpers_internal_test.go
=> cluster: fix lint

cluster/eip712sigs.go, eth2util/eip712/eip712.go, eth2util/eip712/eip712_test.go, go.mod, go.sum
Implements a basic EIP712 structured type data signing.
ticket: #1698
=> eth2util: implement basic eip712 package

cmd/relay.go, p2p/k1.go, testutil/compose/define.go, testutil/random.go
Replace references of ecdsa with k1.
category: misc
ticket: none
=> *: remove referenced to ecdsa

app/promauto/promauto_test.go, eth2util/eth2exp/attagg_old.go, go.mod
Removes two unneeded direct dependencies.
ticket: none
=> gomod: remove unneeded direct dependencies

core/priority/prioritiser.go
This (future) version of charon (v0.14) will only be compatible with v0.13 which already supports priority protocol. So this removes the "opt-in" type behaviour that checks if peers support it or not. This aims to solve flapping tests that fail due to protocol detection races.
ticket: none
=> core/priority: default prioritise to enabled

app/app.go
Fail startup if BN connected to wrong network, as it is identical to not being connected to a BN. 
ticket: none
=> app: fail startup if BN on wrong fork/network

app/app.go, app/featureset/featureset.go, core/interfaces.go, core/tracker/tracker2/tracker.go, core/tracker/tracker2/tracker_internal_test.go, core/tracking.go
Adds tests for tracker2 and featureflag with status alpha.
ticket: #1478 
feature_flag: tracker_v2
=> tracker/tracker2: add tests and featureflag

core/validatorapi/eth2types.go, core/validatorapi/router.go, core/validatorapi/router_internal_test.go, core/validatorapi/validatorapi.go
Adds node version endpoint to validatorapi.
ticket: #1747
=> validatorapi: add node version

core/validatorapi/router_internal_test.go
=> validatorapi: refactor tests

p2p/p2p.go
Improve debug logs
category: bug
ticket: https://github.com/ObolNetwork/charon/issues/1790
=> p2p: improve debug logs

app/app.go, app/simnet_test.go, app/vmock.go, cmd/cmd_internal_test.go, cmd/run.go, core/scheduler/testdata/TestSchedulerDuties_grouped.golden, core/scheduler/testdata/TestSchedulerDuties_spread.golden, core/scheduler/testdata/TestSchedulerDuties_spread_errors.golden, core/validatorapi/validatorapi_test.go, docs/configuration.md, testutil/beaconmock/beaconmock.go, testutil/beaconmock/options.go, testutil/beaconmock/testdata/TestDeterministicAttesterDuties.golden, testutil/beaconmock/testdata/TestDeterministicProposerDuties.golden, testutil/compose/compose/main.go, testutil/compose/config.go, testutil/compose/lock.go, testutil/compose/new_test.go, testutil/compose/smoke/smoke_test.go, testutil/compose/testdata/TestDockerCompose_run_template.golden, testutil/compose/testdata/TestDockerCompose_run_yml.golden, testutil/compose/testdata/TestNewDefaultConfig.golden, testutil/random.go, testutil/validatormock/testdata/TestAttest_0_aggregations.golden, testutil/validatormock/testdata/TestAttest_0_attestations.golden, testutil/validatormock/testdata/TestAttest_1_aggregations.golden, testutil/validatormock/testdata/TestAttest_1_attestations.golden, testutil/validatormock/validatormock.go, testutil/validatormock/validatormock_test.go
Enables very large smoke test with 7 of 10 cluster and 100 validators.
category: test
ticket: #1471
=> compose: fix very large smoke test

app/app_test.go, cmd/relay/p2p.go
Adds a test/script to test remote relay connection count.
category: test
ticket: none
=> app: add a test for remote relay connections

LICENSE
Changes license from GPL v3 to BSL.
category: misc
ticket: #1753
=> *: change license to BSL

.github/workflows/golangci-lint.yml, .pre-commit-config.yaml, cmd/createdkg.go, core/consensus/sniffed_internal_test.go, core/consensus/transport.go, dkg/disk.go, eth2util/keystore/keystore.go
Fixes small `golangci-lint` issues in various packages.
ticket: none
=> *: fix `golangci-lint` issues

app/version/version.go
Bump to version v0.14.0.
category: misc
ticket: none
=> app/version: bump to version v0.14.0

core/consensus/msg.go, core/consensus/msg_internal_test.go
Fixes copy/paste parsing issue in `core/consensus` package
category: bug
ticket: none
=> core/consensus: fix msg parsing issue

README.md
Update nimbus attestation status to ✅  in project status section of readme.
category: docs
ticket: none
=> readme: update nimbus attestation status

p2p/receive.go
Improve libp2p read timeout handling by using `SetReadDeadline`.  Also include duration and read bytes to debug throughput issues.
Will improve confusing `LibP2P handle stream error: receive cancelled during verification: context deadline exceeded` logs which are actually due to read timeouts.
category: misc
ticket: none
=> p2p: improve read timeout errors

p2p/receive.go
Improve libp2p read timeout logs by checking whether the partially read content is actually a valid protobuf. This would indicate we could move to proper length delimited encoding instead of relying on end-of-stream to indicate end-of-message.
category: misc
ticket: none
=> p2p: improve read timeout logs

app/version/version.go
Bump version to v0.14.1.
category: misc
ticket: none
=> app/version: bump to v0.14.1

cmd/relay/p2p.go
Fix relay stream limit
category: bug
ticket: #1892
=> relay: add streams outbound limit

app/peerinfo/adhoc.go, app/peerinfo/peerinfo.go, core/consensus/component.go, core/consensus/transport.go, core/parsigex/parsigex.go, core/priority/prioritiser.go
Enables delimited versions of all libp2p protocols.
ticket: #1885
=> *: enable delimited wire protocol upgrade

dkg/frost_internal_test.go
Revert unintentional debugging change.
category: test
ticket: none
=> dkg: revert test debugging change

app/obolapi/api.go, eth2util/keymanager/keymanager.go
Fix style issue
category: misc
ticket: #1906
=> dkg: remove backticks

app/version/version.go
Bumps version to v0.14.4
category: misc
ticket: none
=> app/version: bump v0.14.4

cluster/version.go
Releases v1.6 of cluster definition.
category: misc
ticket: none
=> cluster: release v1.6 of cluster definition

p2p/ping.go
Fix race in p2p ping service by creating a new delay callback per remote peer.
category: bug
ticket: #1867
=> p2p: fix ping service race condition

core/scheduler/scheduler_test.go
Place `c.now` behind a mutex.
category: bug
ticket: #1867
=> core/scheduler: fix data race in tests

dkg/sync/client.go
Explicitly handle `errInvalidVersion` errors on dkg sync client side. Also add peer name to errors.
category: misc
ticket: none
=> dkg/sync: improve client version mismatch errors

testutil/validatormock/attest.go
Fixes concurrent access issue in validatormock.
category: bug
ticket: #1867
=> testutil/validatormock: fix concurrent access issue

app/app.go
What the title says
category: bug 
ticket: none
=> app: fix data race in `setFeeRecipient`

.github/workflows/test.yml
Updates `codecov` to latest version, v3.1.1.
category: misc
ticket: none
=> github/workflows: update codecov version

.github/workflows/build-push-deploy-promrated.yaml
Adds a tag variable so that the latest promrated gets deployed without manual update.
category: misc
ticket: #1964
=> testutil/promrated: set tag var correctly for deployment

dkg/dkg.go, dkg/sync/sync_test.go, p2p/relay.go
Fix issues in tests
category: test
ticket: none
=> *: fix more test issues

dkg/dkg_test.go
Fixes the following race condition in the sync test that caused it to flap:
- 3 peers are connected to each other (0,1,3)
- stop 1 peer (3)
- start remaining peers (2,3)
- There is a race in peers that remain up (0,1)
- between detecting 3 went down and 2 came up.
- If it detects that 2 is up, BEFORE it detects 3 is down, 
- Then it thinks it is connected to all peers
- And stops retrying to connect
- Then it detects 3 is down
- Then it fails. 
ticket: none
=> dkg: fix race in sync test

testutil/integration/simnet_test.go
It might happen that the beaconmock goroutine gets scheduled much after the teku startup one, leading to Teku exiting with error, and the test failing.
Ensure this doesn't happen by checking that beaconmock is up before running the teku container: if it doesn't become available in 10s (that is, HTTP requests to it doesn't error), error the test.
category: test
ticket: none
=> integration: wait for beaconmock to be up before starting teku

dkg/dkg.go, dkg/dkg_test.go, dkg/sync/server.go, testutil/helpers.go, testutil/integration/infosync_test.go, testutil/validatormock/synccomm.go
Fix concurrent access race issue in validator mock.
category: bug
ticket: none
=> testutil/validatormock: fix concurrent access race

app/forkjoin/forkjoin_test.go
Fixes race in `TestPanic` test.
category: misc
ticket: none
=> app/forkjoin: fix race in test

p2p/p2p.go
Fixes missing libp2p new connection/disconnect logs by moving the `close(quit)` command into the goroutine. 
category: misc
ticket: none
=> p2p: fix missing connection logs

.github/workflows/govulncheck.yml
Run `govulncheck` on releases as well, not just PRs and `main` commits.
category: misc
ticket: none
=> workflows: run govulncheck on releases

.golangci.yml, core/validatorapi/router.go, core/validatorapi/router_internal_test.go, testutil/integration/simnet_test.go, testutil/random.go
Enable support for ssz encoding in validatorapi.
ticket: #1537
cherry-pick: #2063
=> core/validatorapi: support ssz encoded request bodies

.github/workflows/codeql-analysis.yml, .github/workflows/golangci-lint.yml, .github/workflows/govulncheck.yml, .github/workflows/pre-commit.yml, .github/workflows/test.yml
Run github actions on release branch commits.
category: misc
ticket: none
=> github/workflows: run actions on release branch commits

core/consensus/component.go, core/consensus/component_internal_test.go
Fixes OBOL-07.
category: bug
ticket: #1923 
Closes #1923
=> core/consensus: verify wire justification duties

app/monitoringapi_internal_test.go, testutil/beaconmock/options.go, testutil/compose/static/grafana/dash_charon_overview.json
Updates compose dashboard to align with central monitoring.
category: misc
ticket: none
=> compose: update compose dashboard

app/version/version.go
Aligns main branch version with "release v2" process.
category: misc
ticket: none
=> app/version: fix main branch version

core/consensus/strategysim_internal_test.go
Speed up simulator matrix test by parallelising it, since most time is actually spent sleeping. It previously took 1min, now it runs in 5s.
category: test
ticket: none
=> core/consensus: speed up simulator

core/consensus/component.go
Include timer log parameter in consensus logs.
category: misc
ticket: none
=> core/consensus: include timer type in logs

core/qbft/qbft.go, core/qbft/qbft_internal_test.go
Fixes issue in qbft when input value not present for leader in subsequent rounds.
category: bug
ticket: #928
=> core/qbft: fix lazy value issue

core/consensus/strategysim_internal_test.go
Improve simulator, adding eager timers and better logging and better summaries.
category: test
ticket: none
=> core/consensus: improve simulator

core/parsigdb/memory.go, dkg/keycast.go, docs/structure.md, p2p/peer.go
Fixes miscellaneous comments from sigp audit.
category: misc
ticket: none
=> *: misc audit fixes

.github/workflows/deploy-relay-prod.yml
Add the new AWS relay-2 to the relays deployment workflow
ticket: https://github.com/ObolNetwork/obol-infrastructure/issues/491
=> github/workflows: add relay-2 to deploy action

app/version/version.go, app/version/version_test.go, core/tracker/inclusion.go
Fix minor version calculation for rc and dev branches. Also address some TODOs.
category: misc
ticket: none
=> app/version: fix minor func

core/tracker/metrics.go, core/tracker/reason.go, core/tracker/tracker.go, core/tracker/tracker_internal_test.go, docs/metrics.md
Refactors tracker failed reasons into structured data and add metric to track failed reason codes.
ticket: #1382
=> core/tracker: instrument structured reasons

cluster/definition.go, cluster/lock.go, cluster/state/testdata/TestAddValidators_json.golden, cluster/state/testdata/TestNodeApprovals_json.golden, cluster/test_cluster.go
Verify pre-generate registrations in lock.VerifySignatures.
category: misc
ticket: none
=> cluster: verify registrations

cmd/markdown_internal_test.go, core/tracker/reason.go, docs/reasons.md
Adds the auto-generated reasons.md document.
category: misc
ticket: none
=> cmd: auto-generate failure reason doc

core/consensus/component.go
Consensus has two "start" methods, `Participate` and `Propose` either of which can run the instance (depending on timer type). This causes problems with tracker since it doens't know which method to track and the fact that `Participate` is called independent of fetcher, means it breaks tracker step ordering logic.
Refactor consensus to always return the instance error from `Propose`, regardless of whether it was started from `Participate` or `Propose`. `Participate` doesn't need to be instrumented, and the order of events in tracker remain consistent.
category: bug
ticket: none
=> core/consensus: propose returns instance errors

docs/README.md, docs/goguidelines.md
Improve the go guidelines adding best practices around errors and logging.
category: misc
ticket: none
=> doc: improve go guidelines

app/version/version.go
Add v0.16.0-rc to app/version.Version.
category: misc
ticket: none
=> app/version: add rc tag to v0.16.0

eth2util/keystore/keystore.go
Cherry-pick fix (#2265)
category: bug 
ticket: none
=> eth2util/keystore: cherry pick bug fix #2265

Dockerfile
Convert build args into env vars.
category: misc
ticket: #2270
=> dockerfile: fix build args

app/app.go, app/featureset/featureset.go, testutil/integration/simnet_test.go
Adds a `PreGenRegistration` in order to disable pre-generated registrations if required. Only used in testing at this point.
category: misc
ticket: #2282
=> app: add a PreGenRegistration feature flag

testutil/integration/simnet_test.go
Improve simnet test to assert duties from all peers explicitly.
category: test
ticket: none
=> testutil/integration: improve simnet assertions

cluster/definition.go, cluster/state/cluster.go, cluster/state/cluster_test.go
Error in charon run and DKG if duplicate ENRs detected.
category: bug
ticket: #2296
=> cluster: ensure unique operator ENRs

.github/workflows/golangci-lint.yml, .github/workflows/govulncheck.yml, .github/workflows/nightly-tests.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/track-pr.yml, .github/workflows/verify-pr.yml, .golangci.yml, Dockerfile, testutil/promrated/Dockerfile
Update all workflows to Go 1.20.5.
category: misc
ticket: none
=> workflows: update to Go 1.20.5

.github/workflows/build-push-deploy.yml
Fixes github workflow.
category: bug 
ticket: none
=> github: fix detected version

core/validatorapi/validatorapi.go, core/validatorapi/validatorapi_test.go
Swallow incorrect non-dv validator registrations. This is a known limitation. Most VCs do not support valid dv-middleware validator registrations (only teku does at this point). But with pre-generated registrations, we do enable builder-api on VCs to enable mev-boost, so that results in these invalid registration being submitted which results in a lot of `unknown public key` errors in both charon as well as errors the VC logs. These errors are just noise, resulting in operators worrying unnecessarily. 
The risk is that we do not identify actual bugs, but that is why we do the debug log (with log filtering).
category: misc
ticket: none
=> core/validatorapi: swallow non-dv registrations

core/bcast/metrics.go, core/bcast/recast.go, docs/metrics.md
Adds registration recasting metrics per source.
category: misc
ticket: none
=> core/recast: add registration metrics

.github/workflows/build-push-deploy-promrated.yaml, .github/workflows/build-push-deploy.yml
Fix image sha for deployments
category: bug
ticket: #2367
=> workflows: add length to shorten command

cmd/addvalidators.go, cmd/addvalidators_internal_test.go
Adds `--cluster-dir` flag to `add-validators-solo` command. 
Also writes cluster manifest and backup files to each node directory.
ticket: #2379
=> cmd: add `--cluster-dir` flag

app/health/checker.go, app/health/checks.go, app/health/metrics.go, app/health/reducers.go, app/health/select.go, go.mod
PoC of Health Checks V2. See `checks.go`
ticket: none
=> app/health: implement health checks

app/health/check_internal_test.go, app/health/checker.go, app/health/checks.go, app/health/reducers.go
Add tests for first and second checks. More to follow in subsequent PRs.
category: test
ticket: none
=> app/health: add some check tests

app/monitoringapi.go, docs/metrics.md
Wires health checker.
ticket: none
=> app: wire health checker

cmd/addvalidators.go, cmd/addvalidators_internal_test.go
Write keystores for new validators to disk.
ticket: #2382
=> cmd: write keystores

app/health/checker.go, app/health/checks.go, app/health/checks_internal_test.go
Fixes error and warning log checks to sum labels, since these logs are actually labeled by topic.
category: bug
ticket: none
=> app/health: fix log checks

core/consensus/component.go, core/consensus/component_internal_test.go
Add debug logs to troubleshoot goroutine leak.
category: misc
ticket: none
=> core/consensus: add leak debug logs

.github/workflows/test.yml, testutil/compose/fuzz/beacon_fuzz_test.go
Adds beacon fuzz test to our CI/CD workflows.
category: misc
ticket: #2180
=> github: add beacon fuzz test to CI/CD

app/app.go, core/consensus/component.go, core/consensus/component_internal_test.go, core/consensus/component_test.go, core/gater.go, core/gater_test.go, core/parsigex/parsigex.go, core/parsigex/parsigex_test.go, dkg/exchanger.go
Wire duty gater. Improve it to also check duty types.
ticket: #2506
=> app: wire duty gater

cmd/createcluster.go, cmd/createdkg.go, eth2util/network.go, eth2util/network_test.go
Add `holesky` to the list of supported networks.
ticket: #2399
=> eth2util: add holesky

core/tracker/inclusion.go
Fixes inclusion checker bug which was reporting false negatives about the inclusion blinded blocks. This happened because of misconfiguration between deadline of a duty and inclusion checker lag. Duty deadline of `builder_proposer` is 5 slots while inclusion lag is 4 slots. Inclusion checker should start checking after duty deadline is hit to avoid getting any submissions after that.
Which is why even the blinded block was _actually_ proposed successfully, inclusion checker marked it failed as duty was still active and retryer was busy retrying `blinded_block` submission request.
category: bug
ticket: #2661
=> core/tracker: fix inclusion checker bug

LICENSE
Updates license ahead of upcoming release
category: misc
ticket: none
=> *: update license

app/version/version.go
Bump to rc.
category: misc
ticket: none
=> app/version: bump to v0.18-rc

.github/workflows/golangci-lint.yml, .github/workflows/govulncheck.yml, .github/workflows/nightly-tests.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/verify-pr.yml, .golangci.yml, Dockerfile, testutil/promrated/Dockerfile
Fixes latest Go security vulns.
category: misc
ticket: none
=> *: update to Go v1.21.4

app/version/version.go
Update version support matrix as well.
category: misc
ticket: none
=> app/version: bump to v0.19-rc

core/validatorapi/router.go, core/validatorapi/router_internal_test.go
Cherrypick of #2849.
Needed to avoid serializing the whole validator list on POST `get_validator` requests.
--
Implemented POST get validators endpoint.
ticket: #2840
=> validatorapi: supporting getValidators with post

app/app.go, core/interfaces.go
Reverts ObolNetwork/charon#2752 as it was not working as expected and was blocking registrations health checks changes.
category: misc
ticket: #2669
=> core: revert wire recaster component changes

core/validatorapi/router_internal_test.go
Fixes router test which might incur in flapping due to CPU usage.
category: test
ticket: none
=> core/validatorapi: fix flappy test

testutil/compose/static/lighthouse/Dockerfile
Supporting arm64 arch for `compose` tool.
ticket: #2886
=> testutil/compose: supporting arm64

dkg/disk.go, dkg/sync/client.go
Removes TODOs in the `dkg` package.
category: misc
ticket: none
=> dkg: remove todos

eth2util/eth2exp/attagg.go, testutil/beaconmock/attestation.go, testutil/beaconmock/server.go, testutil/compose/smoke/smoke_test.go, testutil/integration/simnet_test.go, testutil/validatormock/attest.go, testutil/validatormock/propose.go
Remove todos in the `testutil` package.
category: misc
ticket: none
=> testutil: remove todos

README.md
Add section in the `README.md` detailing how Charon versioning works, and how versions are compatible between themselves.
category: docs
ticket: none
=> *: version compatibility notes

docs/architecture.md
Update architecture docs starting from new duty types.
ticket: none
=> docs: update architecture doc

LICENSE, cmd/combine.go, cmd/dkg.go, cmd/enr.go, cmd/relay.go, cmd/run.go, docs/configuration.md
Started with me adding a missing `the`, then I refined a few commands as part of the exit PRD. 
category: docs
ticket: none
=> cmd: update copy

testutil/compose/docker-compose.template, testutil/compose/static/lighthouse/run.sh
Attempt to fix the failing smoke tests.
ticket: none
=> testutil/compose: fixed compose smoke test

app/app.go, core/validatorapi/validatorapi.go, core/validatorapi/validatorapi_test.go
- #3123 
category: misc
ticket: none
=> *: cherrypick for v1.0-rc3

cmd/exit_broadcast.go, cmd/exit_fetch.go, cmd/exit_sign.go
- #3127
category: misc
ticket: none
=> *: cherrypick for v1.0-rc4

LICENSE
- #3140
category: misc
ticket: none
=> *: cherrypick for v1.0.0

LICENSE
- #3151 
category: misc
ticket: none
=> *: cherrypick for v1.0-rc6

.github/actions/setup-go/action.yml, .golangci.yml, Dockerfile, testutil/promrated/Dockerfile
Fixes https://pkg.go.dev/vuln/GO-2024-2963.
ticket: none
=> *: update to Go v1.22.5

go.mod, go.sum
Upgraded eth2client.
category: misc
ticket: none
=> *: bumped go-eth2-client to 0.21.7

docs/architecture.md, docs/configuration.md, docs/dkg.md, docs/goguidelines.md
docs typos
category: docs
ticket: none
=> docs: fix typos

docs/architecture.md, docs/branching.md, docs/contributing.md, docs/dkg.md
Hello
While looking into your docs I found several spelling errors.
Br,Elias.
category: misc
ticket: none
=> docs: fix spelling issues

README.md
Link the changelog page for news about charon compatibility with validator clients and beacon nodes.
category: docs
ticket: none
=> *: update project status

app/version/version.go
Change version of branch `main-v1.1` from `v1.1-dev` to `v1.1-rc`.
category: misc
ticket: none
=> app/version: v1.1 from dev to rc

app/version/version.go
Bump version to v1.2-dev.
category: misc
ticket: none
=> app/version: bump version to v1.2-dev

.github/actions/setup-go/action.yml, .golangci.yml, Dockerfile, testutil/promrated/Dockerfile
Security fixes...
category: misc
ticket: none
=> *: bump golang to 1.23.1

.github/workflows/release.yml
Add needs to trigger
ticket: none
=> *: add needs to trigger

.github/workflows/build-push-deploy.yml
fix trigger dispatch repo
ticket: none
=> *: fix trigger dispatch repo

.github/workflows/release.yml
automate PR for release CDVN and CDVC
ticket: none
=> *: automate PR for release CDVN and CDVC

.github/workflows/golangci-lint.yml, .golangci.yml, .pre-commit/run_linter.sh, cluster/definition.go, cluster/lock.go
=> *: bump linter v1.62.2

.github/workflows/golangci-lint.yml, .pre-commit/run_linter.sh, cmd/test.go, cmd/testbeacon.go, cmd/testinfra.go, cmd/testmev.go, cmd/testpeers.go, cmd/testpeers_internal_test.go, cmd/testvalidator.go, core/validatorapi/validatorapi_test.go, go.mod, testutil/compose/fuzz/fuzz_test.go, testutil/integration/simnet_test.go
Bump linter version...
category: misc
ticket: none
=> *: bump linter to 1.63.4

docs/contributing.md
Change discord channel for contributing.
category: docs
ticket: none
=> docs: contributing discord channel

.github/workflows/release.yml
trigger dispatch for LCDVN and Launchpad
ticket: none
=> *: trigger dispatch for LCDVN and Launchpad

.github/workflows/label-pr.yml, .github/workflows/nightly-tests.yml, .github/workflows/test.yml
Fixed label-pr action to skip electra branch.
ticket: none
=> *: label PRs to electra branch

.github/workflows/build-push-deploy-promrated.yaml, .github/workflows/build-push-deploy.yml, .github/workflows/codeql-analysis.yml, .github/workflows/golangci-lint.yml, .github/workflows/govulncheck.yml, .github/workflows/nightly-tests.yml, .github/workflows/pre-commit.yml, .github/workflows/test.yml, .github/workflows/verify-pr.yml
update github actions
ticket: none
=> *: update github actions

.github/workflows/build-push-deploy.yml
fix tag latest with strict rule
category: bug
ticket: none
=> *: fix tag latest with strict rule

.github/workflows/build-push-deploy.yml
fix: tag latest with startsWith
category: bug
ticket: none
=> fix: tag latest with startsWith

.github/workflows/build-push-deploy.yml
fix: change type raw to semver to tag latest
category: bug
ticket: none
=> fix: change type raw to semver to tag latest

.github/workflows/build-push-deploy.yml
fix: latest with startsWith and github.ref 
category: bug
ticket: none
=> fix: latest with startsWith and github.ref

app/eth2wrap/eth2wrap.go, app/eth2wrap/eth2wrap_test.go, app/eth2wrap/httpwrap.go, app/obolapi/exit_test.go, app/vmock.go, core/validatorapi/router_internal_test.go
Add HTTP headers to our HTTP calls as well.
category: bug
ticket: none
=> app: add headers to httpwrap

app/eth2wrap/eth2wrap_test.go
Faulty fallback unit test.
Test expects every client to be called when in reality if one client responds quickly the other might never be evoked.
category: bug 
ticket: none
=> app/eth2wrap: fix faulty fallback test

app/version/version.go
v1.3-rc1 release
category: misc
ticket: none
=> app: v1.3-rc1

Dockerfile, LICENSE, app/eth2wrap/eth2wrap.go, core/consensus/metrics/metrics.go
v1.3-rc2
category: misc
ticket: none
=> *: v1.3 rc2

cmd/createcluster.go, cmd/createdkg.go, eth2util/network.go
Add the new LTS Hoodi testnet.
ticket: none
=> *: add Hoodi testnet

Dockerfile, LICENSE, app/eth2wrap/eth2wrap.go, cmd/createcluster.go, cmd/createdkg.go, core/consensus/metrics/metrics.go, eth2util/network.go
v1.3.0-rc3
category: misc
ticket: none
=> *: v1.3.0-rc3

cmd/testinfra.go, cmd/testinfra_internal_test.go, testutil/fuzz.go
Those 2 limitations were missed beforehand...
category: test
ticket: none
=> *: fix testing fuzzer attestations limit

.github/renovate.json
chore(renovate): disable Dependency Dashboard
ticket: none
=> chore: disable Dependency Dashboard

core/tracker/tracker.go, eth2util/helpers.go
make function comment match function name
category: misc
ticket: none
=> *: make function comment match function name

testutil/genchangelog/main.go, testutil/genchangelog/template.md
- Add compatibility matrix to the template.
- Add TODOs to the template for the manually populated parts.
- Remove renovate bot's PRs from changelog (in a similar fashion as dependabot's PRs are removed).
category: misc
ticket: #3575
=> testutil: update release notes changelog

app/obolapi/test.go, cmd/test.go, cmd/testbeacon.go, cmd/testinfra.go, cmd/testmev.go, cmd/testpeers.go, cmd/testpeers_internal_test.go, cmd/testvalidator.go
Add publish option for test commands.
ticket: #3350
=> *: add test command publish

app/obolapi/test.go
Somehow missed the `+`...
category: bug
ticket: none
=> app: test publish typo

docs/architecture.md
Delete non-existing interface.
category: docs
ticket: #2956
=> docs: remove Signer from architecture.md

app/health/checks.go, app/health/checks_internal_test.go, app/health/reducers.go
Add health check which monitor increase in usage of fallback beacon nodes.
ticket: #3328
=> app/health: add fallback beacon node usage health check

app/version/version.go
Bump to version `v1.4`
category: misc
ticket: none
=> app/version: bump to v1.4

core/dutydb/memory.go
Fix aggregations storing keys clash.
category: bug
ticket: none
=> dutydb: electra aggregation hotfix

core/dutydb/memory.go
Fix aggregations storing keys clash.
category: bug
ticket: none
=> dutydb: electra aggregation hotfix v1.3

core/dutydb/memory.go
Relax checks and always overwrite with incoming agg.
category: bug
ticket: none
=> dutydb: electra aggregation hotfix v1.4

core/tracker/inclusion.go
Something that completely slipped in the previous PR...
category: bug
ticket: none
=> tracker: fix inclusion attester duty check

core/tracker/inclusion.go
Something that completely slipped in the previous PR...
category: bug
ticket: none
=> tracker: fix no attester duties v1.3

app/app.go, core/bcast/bcast.go, core/sigagg/sigagg.go, tbls/herumi.go
Fix for unrecoverable validator index.
category: bug
ticket: none
=> *: recover from missing validator index

app/eth2wrap/version.go, app/eth2wrap/version_internal_test.go, app/monitoringapi.go
Add warning log for connect beacon clients running below supported version
ticket: #2922
=> *: add beacon node minimum version verification

app/stacksnipe/stacksnipe.go, testutil/genchangelog/template.md
Add Grandine and Vouch to release template and Vouch to `stacksnipe`
ticket: none
=> *: add missing entries to release template and stacksnipe

app/app.go, app/featureset/featureset.go, app/featureset/featureset_internal_test.go, core/scheduler/scheduler.go, core/scheduler/scheduler_test.go
Scheduler to refresh all duties in case of a previous epoch reorg reported by sse component.
ticket: #3580
feature_flag: sse_reorg_duties
=> *: scheduler handling reorgs

core/scheduler/scheduler.go, core/scheduler/scheduler_test.go
Fixed reorg flakey test.
ticket: none
=> core/scheduler: reorg flakey test

README.md
replaced broken link intro
category: docs
ticket: none
=> docs: replaced broken link intro

.github/workflows/build-release-binaries.yml
More improvements to the build commands.
ticket: none
=> *: fixed build-release-binaries.xml

.github/workflows/build-release-binaries.yml, core/scheduler/scheduler_test.go
Even more fixes after thorough review with GPT.
ticket: none
=> *: more fixes to building bins script

.github/workflows/build-release-binaries.yml
Added `sudo chmod -R u+w dist` as it is not permitted to change folder permissions otherwise.
ticket: none
=> *: added sudo for chmod

core/scheduler/scheduler_test.go
Fixed flakey `TestHandleChainReorgEvent`.
ticket: none
=> core: fixed flakey reorg test

.github/workflows/build-release-binaries.yml, app/sse/listener.go, app/sse/listener_internal_test.go, app/sse/metrics.go
Added explicit buckets to `sse_head_delay` histogram.
ticket: none
=> app: added sse_head_delay buckets

.github/workflows/build-release-binaries.yml, app/sse/listener.go, app/sse/listener_internal_test.go, app/sse/metrics.go, core/scheduler/scheduler_test.go, docs/metrics.md
Cherry picked:
* https://github.com/ObolNetwork/charon/pull/3794
* https://github.com/ObolNetwork/charon/pull/3795
* https://github.com/ObolNetwork/charon/pull/3796
category: misc
ticket: none
=> *: v1.5-rc2

app/version/version.go
As per the title.
To be merged after v1.5.0 is officially released
category: misc
ticket: none
=> app: bump to v1.6-dev

go.mod, go.sum
Bump go-eth2-client in v1.5
category: misc
ticket: none
=> deps: bump go-eth2-client

scripts/README.md, scripts/cluster_merge.sh, scripts/node_merge.sh
Added `node_merge.sh` and `cluster_merge.sh` scripts. See `README.md` for essential details.
ticket: #3825
=> *: added cluster merge scripts

cmd/createdkg.go, cmd/createdkg_internal_test.go
Log launchpad link per network
ticket: none
=> cmd: launchpad link per network

app/eth1wrap/eth1wrap_test.go
Fix flaky test on `app/eth1wrap`
category: bug
ticket: none
=> app/eth1wrap: fix flaky test

.github/actions/setup-go/action.yml, .github/workflows/codeql-analysis.yml, .github/workflows/golangci-lint.yml, .golangci.yml, .pre-commit/run_linter.sh, Dockerfile, go.mod, testutil/promrated/Dockerfile
Bump go to v1.25.0.
Bump golangci-lint to v2.4.0.
category: misc
ticket: none
=> *: bump go to v1.25

app/app.go, app/sse/listener.go, app/tracer/trace.go, cmd/exit_broadcast.go, cmd/exit_list.go, cmd/exit_sign.go, cmd/run.go, cmd/run_internal_test.go, dkg/dkg_test.go, docs/configuration.md, eth2util/helpers.go, eth2util/helpers_test.go
Added `--otlp-headers` flag.
ticket: none
=> *: added otlp headers

.github/actions/setup-go/action.yml, .github/workflows/codeql-analysis.yml, .github/workflows/golangci-lint.yml, .golangci.yml, .pre-commit/run_linter.sh, Dockerfile, app/app.go, app/sse/listener.go, app/tracer/trace.go, cmd/exit_broadcast.go, cmd/exit_list.go, cmd/exit_sign.go, cmd/run.go, cmd/run_internal_test.go, core/aggsigdb/memory_internal_test.go, core/aggsigdb/memory_test.go, core/aggsigdb/memory_v2_internal_test.go, core/bcast/bcast_test.go, core/parsigdb/memory_internal_test.go, dkg/dkg_test.go, docs/configuration.md, eth2util/helpers.go, eth2util/helpers_test.go, go.mod, go.sum, p2p/sender.go, testutil/promrated/Dockerfile
Cherry-picking for v1.6.0-rc3.
category: misc
ticket: none
=> *: v1.6.0-rc3 cherry-picking

app/version/version.go
Cherry-picking for v1.6.0-rc5.
category: misc
ticket: none
=> *: v1.6.0-rc5 cherry-picking

app/version/version.go
Bump version from `v1.6-rc` to `v1.6`
category: misc
ticket: none
=> app/version: bump to v1.6

app/featureset/featureset.go, app/metrics.go, docs/metrics.md
As per the title. The ticket explains the reasoning.
ticket: #3979
=> app: add metric for enabled feature flags

app/version/version.go
Prepare for v1.7 release candidate 1.
category: misc
ticket: none
=> app: bump version from dev to rc
