ObolNetwork/charon

core/interfaces.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
docs/architecture.md

Wires GetDuty in validatorapi alongwith other stuff required for block proposer and improve architecture docs.
ticket: none

core: wire getduty in validatorapi

---

app/app.go
app/app_test.go
app/lifecycle/order.go
app/lifecycle/orderstart_string.go
app/lifecycle/orderstop_string.go
app/manifest_test.go
cmd/bootnode.go
cmd/run.go
core/leadercast/transport.go
core/parsigex/parsigex.go
docs/configuration.md
p2p/config.go
p2p/discovery.go
p2p/gater.go
p2p/gater_internal_test.go
p2p/p2p.go
p2p/peer.go
p2p/relay.go

Adds support for libp2p circuit relay via bootnodes. Allows clusters with non-publicly accessible charon nodes.
ticket: #413

p2p: support circuit relay via bootnodes

---

dkg/keycastjoin.go
dkg/keycastlead.go

Implements a stub non-production key generation ceremony called keycast. The leader generates the keys and shares and broadcasts them to the participants. This allows us to wire and configure the dkg without an actual implementation. Unblocking multiple streams of works.
ticket: none

dkg: implement keycast

---

docs/configuration.md

Documents and spec V1 cluster config which formalises ideas introduced in dkg doc. 
DKG doc needs to be updated to aligned with this.
ticket: none

docs: document cluster config V1

---

cmd/cmd.go
cmd/dkg.go
dkg/disk.go
dkg/join.go
dkg/keycastjoin.go
dkg/keycastlead.go
dkg/lead.go

Wires a stub dkg into the charon cli, starts lbp2p tcp nodes, and runs stub algorithms, and writes output to disk.
This is a starting point for DKG integration, something to build on, extend, and improve.
ticket: #439

cmd: wire dkg stub

---

app/app.go
app/lifecycle/order.go
app/lifecycle/orderstop_string.go
core/dutydb/memory.go
core/dutydb/memory_test.go
core/interfaces.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
testutil/verifypr/verifypr_internal_test.go

Add Shutdown to DutyDB so ValidatorAPI doesn't timeout on shutdown due to blocked DutyDB.Await* requests.
Also remove PubKey from AwaitBlockProposer as per previous TODO. 
Also reorder stop hooks in order of dependency tree.
ticket: none

dutydb: add shutdown and clean api

---

.github/workflows/build.yml

Replaces CONTAINER_REGISTRY_SECRET with GITHUB_TOKEN. It seems that @OisinKyne has configured his Personal Access Token for CONTAINER_REGISTRY_SECRET which is not a good practice for security.
ticket: none

github/workflows: add GITHUB_TOKEN to build

---

.gitignore
cmd/cmd_internal_test.go
cmd/createcluster.go
cmd/run.go
docs/configuration.md

When running commands like `./charon gen-p2pkey` or `./charon create-cluster`, users including me got an error:
`Error: mkdir ./charon: not a directory`
This could happen as the default directory name starts with the prefix `./charon`, for example, `./charon/data` for `create-cluster`. Removing the prefix solves this. Directories are always created off of `charon` root.
category: bug
ticket: #427

app: fix error mkdir ./charon: not a directory

---

app/app.go
app/featureset/config.go
app/log/log.go
app/log/log_test.go
app/log/testdata/TestErrorWrap.golden
app/retry/retry.go
core/leadercast/leadercast.go
core/leadercast/transport.go
core/parsigex/parsigex.go
core/scheduler/scheduler.go
dkg/transport.go
p2p/bootnode.go
p2p/ping.go
p2p/relay.go
testutil/beaconmock/server.go

Aligns `log.Warn` and `log.Error` APIs. Since warn and error are mostly related to logging errors, just at different level, the API should be the same. Using `z.Err(err)` also resulted in inconsistent logging, which is now mitigated by aligned APIs. Also support `nil` errors for both `log.Warn` and `log.Error` that just does logging.
ticket: none

app/log: align warn and error APIs

---

cluster/test_cluster.go
dkg/dkg.go
dkg/dkg_test.go
dkg/keycast_internal_test.go
dkg/transport.go
docs/structure.md

Adds a blackbox dkg test (that should work for any DKG algorithm).
Also adds `cluster.NewForT` which is a port of `app.NewClusterForT` using new cluster types.
This code isn't integrated yet.
category: test
ticket: none

dkg: add blackbox test

---

core/validatorapi/validatorapi.go

Ignore the error for proposer duties as they are the rare ones. It is spamming in logs since it is being checked in every epoch.
category: bug
ticket: #000

core/validatorapi: ignore proposer duties error

---

cluster/distvalidator.go
dkg/disk.go
dkg/dkg.go
dkg/dkg_test.go
dkg/frost.go
dkg/keycast.go
tbls/tblsconv/tblsconv.go
tbls/tss.go

Adds frost algo to the dkg command test.
- Add public shares to cluster lock file.
category: test
ticket: #478 

dkg: add frost command test

---

cmd/cmd.go
cmd/dkg.go

Wires the dkg command to the cli
ticket: #478 

cmd: wire dkg command

---

cmd/cmd.go
cmd/create.go
cmd/createdkg.go

Adds the `charon create dkg` command that generates a cluster definition file.
ticket: #442

cmd: add create dkg command

---

app/log/config.go
app/log/testdata/TestCopyFields.golden
app/log/testdata/TestErrorWrap.golden
app/log/testdata/TestErrorWrapOther.golden
app/log/testdata/TestWithContext.golden

Removes the `{"caller": "dkg.go:121"}` field from console logs.
Reasoning:
- The `caller` field present in ALL console logs adds more noise than signal.
- Removing it reduces noise and focusses the logging on the message.
- Console logs already include a "topic", so the general caller package/scope is already known.
- Since we do structured logging, finding the source/caller is as easy as grepping the code base for the message.
- Proposer production deployments should use JSON log format in any case.
ticket: none

app/log: remove caller from console logs

---

cmd/bootnode.go
cmd/bootnode_internal_test.go
cmd/cmd.go
cmd/cmd_internal_test.go
cmd/create.go
cmd/createcluster.go
cmd/createdkg.go
cmd/createenr.go
cmd/createenr_internal_test.go
cmd/dkg.go
cmd/enr.go
cmd/run.go

Refactor `genp2pkey` and `create-cluster` commands to `create enr` and `create cluster` commands, i.e, subcommands of create command.
ticket: #442 

cmd: refactor to use create command

---

cmd/cmd.go
cmd/createcluster.go
cmd/genp2pkey.go

Make commands backwards compatible until charon-docker-compose and docs are updated.
ticket: #000

cmd: make commands backwards compatible

---

app/z/zapfield.go

This fixes a panic when using `logfmt` formatter and logging slices (which is doesn't support) by convertng any non-standard values to string first.
category: bug
ticket: none

app/log: fix logfmt bug

---

cmd/createdkg.go
dkg/disk.go
dkg/dkg.go

Waits for all peers to connect before starting Frost DKG. This isn't required for keycast since it has retries built-in.
Also:
- Improve logging
- Make configuration files read-only
- Add `DKGAlgo` to `charon create dkg` command.
- Don't error when making folders (since this doesn't work in docker)
ticket: #478 

dkg: wait for peers to connect

---

cmd/enr.go
cmd/enr_internal_test.go
p2p/k1.go

Assist users running `charon enr` in creating their ENRs. See ticket for more details. 
Probably may also need to do more than just a helpful message. Thoughts are welcome!
ticket: #490 

refactor: modify enr error message

---

core/qbft/README.md
core/qbft/clock_test.go
core/qbft/qbft.go
core/qbft/qbft_test.go
core/qbft/uponrule_string.go

Refactors QBFT to explicit justifications.
Also:
- Do not exit when decided, keep running until context cancelled
- Send Qcommit to others after decided
- Jump ahead when receiving justified messages
- Trim old round messages from buffer
- Add constant period tests
- Make instance type bytes (to support "any" instance type)
ticket: #445 

core/qbft: refactor to explicit justifications

---

.pre-commit-config.yaml
core/qbft/qbft.go
core/qbft/qbft_test.go

Refactors qbft to use generics. This simplified the integration significantly since an external buffer isn't required and casting and conversion and (errors) isn't required.
ticket: #445 

core/qbft: refactor to use generics

---

core/qbft/qbft.go
core/qbft/qbft_test.go

Calculates `Quorum` and `Faulty` from `Nodes` as per Roberto suggestion. Also using his paper for the formulas.
Also rename `justify` to `justification`
ticket: #445 

core/qbft: calculate q and f

---

core/qbft/qbft.go
core/qbft/qbft_test.go

Add the 10% dropped message test, which found some bugs:
- Condition J2 doesn't require quorum identical `preparedValue`, only a single RC with that value (confirmed this with GoQuorum `quorum/consensus/istanbul/qbft/core/justification.go:79`).
- Typo on line 652.
- Trimming older rounds removes required PREPARE message. Disable for now.
- Adds a fail fast if quorum round changes are not justified.
category: bug
ticket: #445 

core/qbft: add drop tests and fix bugs

---

core/qbft/qbft_test.go

Fixes failing golangci-lint on main.
ticket: none

qbft: fix build on main

---

core/qbft/qbft.go
core/qbft/qbft_test.go

Fixes buffer trimming issue:
- There is only a few uses for Justification messages: 
- a) Check if a received PRE-PREPARE is justified (only use justifications of that single message)
- b) Check if a received ROUND-CHANGE is justified  (only use justifications of that single message)
- c) Generate justification of a quorum ROUND-CHANGEs (select from all buffered messages and their justifications)
- We only need previously received justifications for (c), and we can get that by `flattening` the buffer.
- Since we do not add old justifications to the buffer anymore
- We can trim all old messages again.
Also make code a bit more explicit and readable.
Also ensure that send-to-self in the test is always first and never drops or jitters.
category: bug
ticket: #445

core/qbft: fix trimming issue

---

.github/pull_request_template.md
docs/contributing.md
testutil/verifypr/verifypr.go
testutil/verifypr/verifypr_internal_test.go

- Removes `feature_set: alpha/beta/stable` PR tag
- Replaces with `feature_flag: foo/bar/qbft_consensus` PR tag
- So instead of linking the PR to the "status" of the feature, rather link the PR to a specific "feature" itself (regardless of status)
- When we generate the change log, we can check what the status of the feature is, and then put the PR in that section (alpha/beta/stable).
- Since the PR (for some feature=foo) might be in alpha now, but when we release, it might be stable
- The status of the feature is defined in the code, in `featureset` package. The status changes over time.
- It is more important to know WHAT feature the code is linked to, rather than the STATUS_AT_PR_TIME.
- The status can then be calculated at ANY point in time.
- It is also much easier to explain when to …

github: add feature_flag tag to PR template

---

core/qbft/msgtype_string.go
core/qbft/qbft.go
core/qbft/qbft_test.go
core/qbft/uponrule_string.go

Broadcasting individual COMMIT messages after Decided can result in some being dropped. This can postpone finality in lossy networks. 
Rather batch `Qcommit` as justification of a new message type `MsgDecided`. This ensures that if a valid justified `MsgDecided` is received, that any process will decide. This also makes sending Qcommit explicit and aligns the API with that other messages, mitigating requirement of special case handling.
Also ensure that when filtering/counting messages, that only unique sources/processes are included. Generalise this via `uniq := uniqSource` helper function.
ticket: #445

core/qbft: send qcommit as decided message

---

core/qbft/qbft.go
core/qbft/qbft_test.go

Simplify and standardise qbft generic `Value` to built-in `comparable`.
This aligns the implementation with `GoQuorum` that uses hashes of the actual values in the algo. This makes the algo simpler and probably more performant. Actual values will need to "hidden" in the `Msg` implementation.
ticket: #445

core/qbft: refactor value to generic comparable

---

core/qbft/qbft.go
core/qbft/qbft_test.go

Adds `ctx` and `err` to the `Transport.Broadcast` function. This allows for tracing and shutdown on fatal errors.
ticket: #445 
feature_flag: qbft_consensus

core/qbft: add ctx and error to broadcast interface

---

core/scheduler/offset.go
core/scheduler/scheduler.go
core/scheduler/scheduler_test.go
core/scheduler/testdata/TestSchedulerDuties_grouped.golden
core/scheduler/testdata/TestSchedulerDuties_spread.golden
core/scheduler/testdata/TestSchedulerDuties_spread_errors.golden

Trigger duties at an offset within each slot.
ticket: #515

core/scheduler: trigger duty at slot offset

---

dkg/dkg.go
tbls/tss.go

Adds the general steps to create an aggregate signature of the lock hash by all validators.
ticket: #478

dkg: add aggregate lock hash signing skeleton

---

dkg/dkg.go

Implement signing and aggregation functions.
ticket: #478

dkg: implement signing todos

---

core/scheduler/scheduler.go

Fixes the linter, previous PR removed `instrumentDuty`.
ticket: none

core/scheduler: fix build

---

.github/pull_request_template.md
testutil/genchangelog/main.go
testutil/genchangelog/main_internal_test.go

Some commit point to invalid issues (#000). This handles that gracefully. Not that the `verify_pr` github action has been updated recently to block #000 tickets.
Also fix PR template issue.
category: bug
ticket: none

testutil/genchangelog: handle invalid issue numbers

---

.github/workflows/build.yml
docs/branching.md
testutil/genchangelog/main.go

Removes github token authentication from genchangelog since charon is now open source.
ticket: none

testutil/genchangelog: remove api auth

---

core/qbft/qbft.go

The QBFT paper states that each upon rules should only be triggered once per round (with the exception of uponJustifiedDecided.
The current implementation allows for rules to be triggered multiple times.
Note this isn't such a big problem, since the algorithm is idempotent, the only affect is that more messages are sent over the wire then necessary.
ticket: #523

core/qbft: only trigger each upon rule once per round

---

core/qbft/qbft.go
core/qbft/uponrule_string.go

The current QBFT implementation is buffering ALL messages.
A valid message may however be unjust.
This is either due to a bug in the code, or due to Byzantine behaviour
To err on the side of caution, it should be assumed the be Byzantine, and those messages should not be buffered.
ticket: #525

core/qbft: do not buffer unjust messages

---

core/qbft/clock_internal_test.go
core/qbft/qbft.go
core/qbft/qbft_internal_test.go

Fixes two related issues with justified preprepare messages:
- it comes down to `highestPrepared` that didn't support multiple pvs at the highest round (see test message).
- When getting pv to send with preprepare, we cannot just get it by only looking at qrc in the justification, since it might contain different pvs at the highest round. We should get it from the prepares included (or not) in the justification.
- The same issue also triggered `unjust preprepare`, so refactored isJustifiedPreprepare to also use prepares to get pv to check, not qrc. 
This issue was triggered by running the test suite thousands of times.
category: bug
ticket: none

core/qbft: fix justified preprepare issue

---

core/qbft/qbft.go

Delete deadcode in qbft. Fixes golangci-lint builds.
ticket: none

refactor: remove dead code

---

docs/contributing.md

`pre-commit autoupdate` updates all the hooks to the latest version. However, `golangci-lint` throws errors and there is an open issue [here](https://github.com/golangci/golangci-lint/issues/2649). So, until the linter is stable enough, it's best not to update it.
category: docs
ticket: none

docs: update contributing doc

---

cmd/createcluster.go

Update `split-validator-keys` to `split-existing-keys`. 
category: bug 
ticket: none

cmd: updating flag inconsistency

---

cmd/createcluster.go
cmd/createcluster_internal_test.go
eth2util/deposit/deposit.go
eth2util/deposit/deposit_test.go
eth2util/deposit/testdata/deposit-data.json

Small cleanups of deposit data integration in create cluster.
ticket: #549

cmd: clean up create cluster deposit data

---

cmd/cmd_internal_test.go
cmd/createcluster.go
cmd/run.go
cmd/testdata/TestCreateCluster_simnet_files.golden
cmd/testdata/TestCreateCluster_splitkeys_files.golden
dkg/disk.go
dkg/dkg_test.go
docs/configuration.md

Write a cluster lock file when running charon create cluster.
Rename cluster_lock.json to cluster-lock.json as per suggestion from Oisin.
ticket: #528

cmd: write lock file in create cluster

---

app/app.go
app/app_test.go
app/simnet_test.go

Wraps all prometheus metrics in cluster identifiers.
ticket: #548

app: add cluster identifiers to all metrics

---

testutil/compose/compose/main.go
testutil/compose/config.go
testutil/compose/define.go
testutil/compose/define_test.go
testutil/compose/testdata/TestDefine.golden

Implements the first iteration of the `compose define` command. It just uses default configuration for now and outputs the `compose.yml` file. Adding webui can be done later.
ticket: #568

testutil/compose: implement v0 define command

---

testutil/compose/compose/main.go
testutil/compose/config.go
testutil/compose/define.go
testutil/compose/docker-compose.template
testutil/compose/lock.go
testutil/compose/lock_internal_test.go
testutil/compose/template.go
testutil/compose/testdata/TestDefine.golden
testutil/compose/testdata/TestLockCompose.golden

Adds the first version of the lock command that creates a docker-compose file to run `charon create cluster` to generate keys and cluster lock file.
ticket: #568

testutil/compose: add lock command

---

testutil/compose/compose/main.go
testutil/compose/docker-compose.template
testutil/compose/lock.go
testutil/compose/run.go
testutil/compose/run_internal_test.go
testutil/compose/template.go
testutil/compose/testdata/TestLockCompose.golden
testutil/compose/testdata/TestRunCompose.golden

Implements the `compose run` command that generates a docker-compose.yml for running a cluster.
ticket: #568

testutil/compose: add run command

---

testutil/compose/compose/main.go
testutil/compose/define.go
testutil/compose/define_test.go
testutil/compose/lock.go

Adds support for DKG key generation to compose lock command.
ticket: #568

testutil/compose: add dkg lock

---

README.md
docs/README.md

Adds the pronunciation of charon to the two READMEs. Got `kharon` from https://en.wikipedia.org/wiki/Charon and the idea from https://github.com/google/guice: `Guice (pronounced 'juice') is a ...`.
ticket: none

docs: add pronunciation

---

testutil/compose/compose/main.go
testutil/compose/define.go

Add automatically calling of docker-compose up after each command. Adding support for chaining commands: `compose define && compose lock && compose run`
ticket: #568

testutil/compose: add auto up

---

testutil/compose/compose/main.go
testutil/compose/config.go
testutil/compose/define.go
testutil/compose/lock.go
testutil/compose/run.go
testutil/compose/testdata/TestDefineCompose.golden

Adds support for locally built binaries via `compose define --build-local`. Thereby adding support for changing the source code inside the container. This is required for proper debugging. 
Note this requires the `CHARON_REPO` env var to be set. Developers are advised to put this in their bash profile.
ticket: #568

testutil/compose: add support for locally built binaries

---

cluster/test_cluster.go
cmd/createdkg.go
dkg/dkg.go

Ensures valid network during create dkg using network flag which is then used to get fork version to create cluster definition.
category: bug
ticket: #583

cmd: ensures valid network during create dkg

---

testutil/compose/config.go
testutil/compose/define.go
testutil/compose/new.go

Make `compose clean` safe, by checking if config.json is present (and double check that no go files are present).
Note: I deleted my whole charon repo by running `compose clean` in the wrong folder  🤦 
Also pull latest docker image in define step.
category: bug 
ticket: #568

testutil/compose: safe clean

---

testutil/compose/README.md

Add splitting public testnet keys to readme.
category: docs
ticket: #568

testutil/compose: add splitting to readme

---

testutil/compose/compose/main.go
testutil/compose/config.go
testutil/compose/define.go
testutil/compose/lock.go
testutil/compose/run.go
testutil/compose/testdata/TestNewDefaultConfig.golden
testutil/compose/testdata/TestRunCompose.golden

Adds the ability to enable different feature sets to compose.
Also fix issue with teku vc config.
ticket: #568

testutil/compose: add feature set flags

---

cluster/cluster_test.go
cluster/distvalidator.go
cluster/testdata/TestEncode_lock_json.golden
cluster/testdata/TestEncode_lock_yaml.golden
dkg/dkg_test.go
dkg/keycast.go
docs/configuration.md
docs/dkg.md
docs/structure.md
tbls/tss.go

Remaining cleanup to replace verifiers with public shares based on the comments on https://github.com/ObolNetwork/charon/pull/604 
ticket: none

tbls: cleanup to remove verifiers

---

go.mod
go.sum
p2p/p2p.go

Removes redundant and deprecated go-libp2p-noise package.
ticket: none

gomod: remove deprecated go-libp2p-noise package

---

testutil/compose/compose/alert.go
testutil/compose/compose/main.go

Add support for `--alert-timeout` to `compose auto` that starts a webhook server that collects alerts and stops docker-compose after the timeout and reports any received alerts.
This add supports for grafana alerts based smoke test evaluators.
ticket: #609

testutil/compose: support alerts and timeout

---

app/retry/retry.go

QBFT blocks until the context is cancelled and therefore always returns a `context.DeadlineExceeded` error. This is expected, so should not result in errors. So only log "Timeout retrying" on second to third attempts.
category: bug
ticket: none

app/retryer: remove error on expected timeout

---

app/retry/retry.go
core/consensus/component.go

Refactors how context deadline errors are handled in retryer:
- The previous change #625 removed error logs on context timeout during first attempt.
- But this isn't correct since other blocking use-cases SHOULD error if they block and then timeout (like fetcher DutyPropser).
- Revert that change, logging all timeout errors.
- Instead refactor qbft consensus to not return an error on timeout, since that is expected behaviour.
ticket: none

app/retryer: refactor context error log

---

app/app_test.go
cmd/bootnode.go

Adds flags to modify max reservations per peer and relay timeout.
category: bug
ticket: #580

cmd/bootnode: fixes circuit reservation resource issues

---

.github/workflows/golangci-lint.yml
.github/workflows/pre-commit.yml
.github/workflows/test.yml

Add discord notifications when main branch actions fail. Only do this for `pre-commit` and `golangci` for now since they fail the most.
category: misc
ticket: none

github/workflows: notify main branch failures

---

tools.go

Installs latest version of `compose` when running `go generate tools.go`.
category: misc
ticket: none

tools: install compose

---

cmd/cmd_internal_test.go
cmd/run.go
docs/configuration.md
p2p/config.go
p2p/discovery.go

Remove `--p2p-peerdb` flag, so `peerDB` now defaults to a new in-memory database.
ticket: #644

flags: remove peerdb flag

---

dkg/frostp2p.go

Disables dupl lint for newFrostP2P.
ticket: none

dkg: fixbuild

---

app/app_test.go
cmd/run.go
docs/configuration.md
p2p/bootnode.go
p2p/config.go
p2p/relay.go

Rename `--p2p-bootmanifest` flag to `--p2p-bootlock`.
ticket: #642

flags: rename bootmanifest to bootlock

---

cmd/cmd_internal_test.go
cmd/run.go
docs/configuration.md

1. Add explanation for different enr variants in `--p2p-bootnodes` flag.
2. Add `http://bootnode.gcp.obol.tech:16000/enr` as the default bootnode in charon run and charon dkg.
ticket: #643

flags: add enr type explanations in p2p-bootnodes flag

---

cmd/run.go
docs/configuration.md

Rrename `--p2p-bootlock` to `--p2p-bootnodes-from-lockfile` as the former is less meaningful to understand
ticket: none

flags: rename p2p-bootlock to p2p-bootnodes-from-lockfile

---

core/parsigex/parsigex.go
p2p/sender.go
testutil/compose/compose/smoke_internal_test.go

Implement v0 of the p2p sender. It doesn't do log filtering yet. This does however solve the issue of one node being down.
ticket: #635

p2p: implement naive p2p sender

---

core/consensus/msg.go
core/validatorapi/eth2types.go
core/validatorapi/validatorapi.go
eth2util/hash.go
eth2util/hash_test.go
testutil/validatormock/validatormock.go

Move `EpochMerkle` to `eth2util` since it is used by different packages. Also simplify it to a function `EpochHashRoot`.
ticket: none

eth2util: move and refactor epoch hash root

---

core/encode.go
core/scheduler/scheduler.go

Split out separate methods for resolving `attester` and `proposer` duties.
ticket: #347

scheduler: refactor resolve duties into separate methods

---

dkg/dkg.go

Cancels context if unable to connect to any peer.
category: bug
ticket: #586

dkg: cancel context to wait peers

---

dkg/dkg.go

Fixes `waitPeer` issue where ping is closed as soon as connected.
category: bug 
ticket: #586

dkg: fix wait peer issue

---

dkg/dkg.go

Moves writing of files like keystores, cluster-lock and deposit-data at the end of p2p exchange, so that we won't get files written to the disk if any peer drops in between
category: bug
ticket: none

dkg: move writing of files at the end

---

core/parsigdb/memory.go

Fixes issue where parsigdb mutex was locked while calling downstream subscribers. 
This aligns with best practice of decreasing locking scope to absolute minimum. 
ticket: none

core/parsigdb: fix mutex issue

---

.github/workflows/release.yml

Add go 1.18 so go commands do not fail.
category: misc
ticket: #320

github/workflows: fix release action

---

app/app.go
core/consensus/component.go
core/consensus/component_test.go
core/consensus/transport.go
core/parsigex/parsigex.go
core/parsigex/parsigex_test.go
dkg/exchanger.go
p2p/sender.go
p2p/sender_internal_test.go

Implement `p2p.Sender` that filters p2p sending logs per peer based on state changes.
Still need to wire and refactor other components to also use `p2p.Sender.`
ticket: #635

p2p: implement sender log filter

---

core/parsigex/parsigex.go
core/parsigex/parsigex_test.go
dkg/exchanger.go
p2p/sender.go

Make the interface `p2p.SendFunc` and the implementations `p2p.Sender.Send` and `p2p.Sender.SendAsync` more explicit.
ticket: #635

p2p: refactor send function interface

---

dkg/dkg.go

Decrease "not connected yet errors" to debug.
Add periodic "connected to M of N peers" info logs.
ticket: #635

dkg: improve connection logging

---

tbls/tss.go
tbls/tss_test.go
testutil/combine/main.go
testutil/combine/main_internal_test.go

Simple CLI tool to combine secret shares into a root secret. That can then be used by `create cluster -split-keys` to "reshare" a cluster. 
Note this is only for local dev testing purposes.
category: test
ticket: none

testutil/combine: implement BLS secret share combine tool

---

core/consensus/component.go
core/qbft/qbft.go
core/qbft/qbft_internal_test.go

Incremental improvements after testnet dry run. 
- Add round to upon rule debug logging
- Add round timeout debug logging
- Increase round timeout by 250ms per round to support slow networks.  
ticket: none
feature_flag: qbft_consensus

core/qbft: improve logging and slowly increase round timeouts

---

.golangci.yml
.pre-commit-config.yaml
.pre-commit/run_regexp.sh
cmd/enr.go
cmd/enr_internal_test.go
core/parsigex/parsigex.go
core/scheduler/scheduler.go
testutil/beaconmock/options.go
testutil/compose/compose/main.go
testutil/validatormock/validatormock.go

Adds pre-commit hooks that checks:
- log messages are capitalised
- error messages are not capitalised
category: misc
ticket: none

precommit: check log and error capitalisation

---

core/validatorapi/router.go

Fix event stream proxy issue. Since we wrapped the response writer in our own type, it didn't implement http.Flusher, so streaming responses were not proxied/flushed to the client.
category: bug
ticket: #688

core/validatorapi: fix proxy response flushing

---

app/app_test.go
cmd/bootnode.go
go.mod

Fixes bootnode "reservation refused" issue. Turns out, `ReservationTTL` doesn't control how long reservations are valid for, instead `validity = 30min` is hardcoded in `github.com/libp2p/go-libp2p/p2p/protocol/circuitv2/relay/constraints.go:14`.
So remove `reservation-ttl` flag and increase the default `max-reservations` to 30 (1/min). 
Also add default info relay logs for more visibility.
category: bug
ticket: none

cmd: fix bootnode reservation issue

---

core/proto.go
core/proto_test.go
core/signeddata.go
core/types.go

Step 1 of N: Adds the new interface and implementations and helper functions. Nothing wired or integrated yet.
ticket: #698

core: add new SignedData interface and impls

---

testutil/compose/docker-compose.template
testutil/compose/static/prometheus/prometheus.yml
testutil/compose/static/prometheus/rules.yml
testutil/compose/testdata/TestDockerCompose_run_yml.golden

Adds a few basic alerts to compose prometheus. Note this is pure prometheus alerts, `alertmanager` hasn't been configured since it isn't required to group or silence or manage alerts over time.
category: test
ticket: #631

testutil/compose: add basic prometheus alerts

---

core/consensus/component.go

Fixes consensus tracing span by cancelling the parent span instead.
category: bug
ticket: none

core/consensus: fix tracing span

---

app/app.go
core/dutydefinition.go
core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
core/interfaces.go
core/retry.go
core/scheduler/metrics.go
core/scheduler/scheduler.go
core/scheduler/scheduler_test.go
core/scheduler/testdata/TestSchedulerDuties_grouped.golden
core/scheduler/testdata/TestSchedulerDuties_spread.golden
core/scheduler/testdata/TestSchedulerDuties_spread_errors.golden
core/tracing.go
core/types.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
docs/architecture.md
docs/structure.md

Renames `FetchArgs` to `DutyDefinition` and update docs.
ticket: #698

core: rename fetch args and update docs

---

.github/workflows/test.yml
testutil/compose/compose/alert.go
testutil/compose/compose/main.go
testutil/compose/docker-compose.template
testutil/compose/static/prometheus/rules.yml
testutil/compose/testdata/TestDockerCompose_run_yml.golden

Polls prometheus alerts during `compose auto`.
category: test
ticket: #631

testutil/compose: poll prometheus alerts

---

testutil/compose/compose/smoke_internal_test.go

Runs smoke tests in parallel for faster feedback.
category: test
ticket: #631

testutil/compose: run smoke tests in parallel

---

.github/workflows/build-push-deploy.yml

Add a step to the build workflow to trigger/dispatch the Charon cluster deployment workflow in the Charon-k8s repository. This will deploy/update the long-lived Charon clusters running on the GKE dev env.
This step dispatches a package published event each time a new Charon image is pushed to the Github registry. The actual deployment workflow is in the charon-k8s repo.
category: misc
ticket: none

build: charon cluster deployment workflow

---

dkg/sync/client.go
dkg/sync/server.go
dkg/sync/sync_internal_test.go
dkg/sync/sync_test.go

Implements AwaitAllConnected method for sync.Server.
ticket: #684

dkg/sync: add AwaitAllConnected for server

---

cmd/cmd_internal_test.go
cmd/run.go
docs/configuration.md

Change default bootnode from `http://bootnode.gcp.obol.tech:16000` to `http://bootnode.gcp.obol.tech:3640`
ticket: none

refactor: update default bootnode ports

---

dkg/dkg.go

Replace hex string to base64 string for definition_hash in dkg logs.
ticket: #753

dkg: replace hex with base64 for definition_hash

---

cmd/createdkg.go
cmd/createdkg_internal_test.go
dkg/dkg.go
p2p/enr.go

Verifies operator ENRs to be in standard form at the start of create dkg. Also make frost dkg as the default one.
ticket: #752

cmd/createdkg: verify enr in create dkg

---

testutil/compose/compose/main.go

Fixes default external bootnode flag, it should be empty.
category: test
ticket: none

testutil/compose: fix default external bootnode flag

---

app/featureset/featureset.go
core/scheduler/clocksync.go
core/scheduler/clocksync_internal_test.go
core/scheduler/metrics.go
core/scheduler/scheduler.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go

Implements a beacon node clock sync feature in alpha. It uses median offset of 10 last head events slots. 
ticket: #764 
feature_flag: beacon_clock_sync

core/schedule: implement beacon node clock sync

---

dkg/sync/server.go

Fails server if client sends wrong definition hash signature by flipping errResponse shared variable.
category: bug
ticket: #761

dkg/sync: fail server side if client sends wrong hash_sig

---

app/app.go
cluster/definition.go
dkg/dkg.go

Improves the error if the provided p2pkey isn't included in the cluster definition.
category: misc
ticket: none

cluster: improve error when p2pkey doesn't match definition

---

app/app.go
app/metrics.go
app/monitoringapi.go

Add `livez` and `readyz` monitoring endpoints to `prometheus`
ticket: none

feat: add livez monitoring api to prometheus

---

core/scheduler/clocksync.go
core/scheduler/clocksync_internal_test.go
core/scheduler/metrics.go
core/scheduler/scheduler.go
testutil/compose/define.go
testutil/compose/static/grafana/dash_simnet.json

Few small tweaks to beacon node clock sync:
- Remove waiting for minimum 10 samples.
- Fix logging issue (mod vs div)
- Update metric name
- Add sync offset panel to Grafana dashboard
category: misc
ticket: #764 
feature_flag: beacon_clock_sync

core/scheduler: tweak clock sync

---

Dockerfile

Right now charon's user ID is 12345 and group ID is 23456, neither of which are ever present on a host. Instead, defaulting to 1000:1000 seems to be what unix defaults its first user account to. That way, although charon still not running as root, it should have the ability to write to the host folder without it, provided the linux user is using the first user on their machine (ids start at 1000 and work up)
category: bug
ticket: none

dockerfile: try and collide docker uid+gid with host uid+gid to reduce permission denied errors

---

core/scheduler/clocksync.go
core/scheduler/clocksync_internal_test.go
core/scheduler/metrics.go
core/scheduler/scheduler.go

Improve sync offset by subtracting the time it takes to send messages over the wire (rtt/2).
category: misc
ticket: #764 
feature_flag: beacon_clock_sync

core/scheduler: subtract half rtt from sync offset

---

.github/workflows/build-push-deploy.yml

Pushes the charon image to docker hub after ghcr. Needs to be tested by being merged. Potentially we don't want to send dev builds here too and might want to split this to only run on tags not commits to main. 
category: misc
ticket: #781

github: push charon to official docker hub registry

---

dkg/dkg.go

Removes unnecessary switch case in DKG logic which caused a bug since it didn't contain "default".
category: bug 
ticket: none

dkg: fix switch case bug

---

cmd/createenr.go

Add backup key warning in `create enr` command.
category: misc
ticket: #785

enr: add warning to create enr command

---

app/app.go
dkg/dkg.go
p2p/bootnode.go
p2p/discovery_internal_test.go

Add the "Charon-Cluster" header to the http request when resolving bootnode ENR on startup.
ticket: #786

p2p: add charon cluster header when resolving bootnode enr

---

core/bcast/bcast.go
core/bcast/bcast_test.go

Catch and ignore lighthouse non-idempotent error. This follows the example set inside goeth2client (but only used for failover in multi-client setup).
category: bug 
ticket: #777

core/bcast: make lighthouse submit attestations idempotent

---

core/unsigneddata.go
core/unsigneddata_test.go
testutil/random.go

- unsigned data implementation of blinded blocker proposer
- implementation of clone test
- Addition to random.go to generate random blinded block body and blinded block (required for clone test)
This touches core & testutil not sure on convention for PR header when this is the case - have gone with core for now
ticket: #809

core: unsigned data implementation for duty builder proposer

---

.golangci.yml
core/sigagg/sigagg_test.go
core/signeddata.go

- signed data implementation of blinded blocker proposer
- implementation of sigagg test
An issue with pre commit check specifically golangci-lint "dupl", appeared to be giving a false positive
`core/sigagg/sigagg_test.go:346: 346-400 lines are duplicate of `core/sigagg/sigagg_test.go:261-315` (dupl)`
This issue https://github.com/golangci/golangci-lint/issues/1372 discussed updating the dupl threshold in the config which I've done. Not sure if I'm missing something and this is a legitimate dupl or if this has happened to you guys before and you have a better solution. 
ticket: #809

core: add changes for signed data for builder proposer

---

.golangci.yml
core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go

- fetcher implementation for builder api
- relevant tests and changes to mocks
ticket: #809

core: fetcher implementation for builder api

---

core/deadline.go
core/deadline_test.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go
core/tracker/tracker_test.go

- Add unit tests for tracker component.
- Add `reportDutyFunc` to `NewTracker`.
It will be followed by a PR for wiring tracker along with the integration tests.
category: test
ticket: #768

core/tracker: add tests for tracker component

---

core/deadline.go
core/deadline_test.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go

- Modify `Deadliner` to ignore deadlined duties.
- Modify `Add(duty)` to return true if a duty is added successfully.
- Fix deadline tests.
ticket: #814

core/deadline: ignore deadlined duties

---

app/app.go
app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
cmd/cmd_internal_test.go
cmd/run.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
docs/configuration.md
testutil/beaconmock/beaconmock.go

Adds support for multiple beacon nodes via eth2 multi client. Adds the `--beacon-node-endpoints` flags and deprecates `--beacon-node-endpoint` flag. Updates validatorapi proxy to use active eth2client address.
ticket: #552

cmd: support multiple beacon nodes

---

core/dutydb/memory.go
core/dutydb/memory_test.go

- dutydb memory implementation for builder proposer
- relevant tests
ticket: #809

core/dutydb: add support for duty builder proposer

---

core/scheduler/scheduler.go

- scheduler implementation for builder proposer
ticket: #809

core/scheduler: add support for duty builder proposer

---

app/app.go
cmd/run.go
docs/configuration.md

- skeleton of the builder-api flag for cmd and app (nothing wired up or any functionality)
ticket: #809

cmd: builderAPI flag in the cli for builder proposer

---

app/version/version.go

Bumps the version to v0.9.0 for release.
category: misc
ticket: none

app/version: bump to v0.9.0

---

.github/workflows/build-push-deploy.yml

Fix automatic changelog generation by doing a deep checkout so full git history is available to `genchangelog`. 
category: misc
ticket: none

github: fix changelog generation

---

app/app.go
app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go

Only use eth2multi is multiple beacon nodes configured. This mitigates an open issue in eth2multi when only a single node is configured, see https://github.com/attestantio/go-eth2-client/issues/20.
category: bug
ticket: #552

app/eth2wrap: only use eth2multi if required

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go

Fixes interface issue by removing `SlotFromStateID` which isn't supported by eth2multi. Also add interface assertions to avoid this in future.
category: bug
ticket: none

app/eth2wrap: fix interface issue

---

app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go

Adds Submitter suffixed interfaces to eth2Provider in eth2wrap.
category: bug
ticket: none

app/eth2wrap: add Submitter interfaces to eth2wrap

---

app/app.go
app/eth2wrap/eth2wrap.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/missing.go

Wraps beaconmock in eth2wrap to get better metrics and runtime safety.
category: misc
ticket: none

testutil/beaconmock: wrap mock

---

testutil/compose/compose/main.go

Compose tests are failing sporadically (but often) due to failure polling alerts from prometheus. This might be due to prometheus image or docker-compose or some other issue. This just ignores these for now to improve flapping.
category: test
ticket: none

testutil/compose: ignore alert polling issue

---

core/tracker/metrics.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go
p2p/peer.go

Implements analyse cluster participation and participation reporter to calculate cluster participation based on partial signatures exchanged and instruments the results.
ticket: #821

core/tracker: implement analyse cluster participation

---

core/validatorapi/eth2types.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
testutil/validatormock/validatormock.go

- Additional changes for validator api
- Router changes for blinded routes
ticket: #809

core/validatorapi: validator api builder proposer 

---

core/types.go
core/types_test.go

Jim has merged in the builder registration PR https://github.com/attestantio/go-eth2-client/pull/19 so we are unblocked on that flow now
- Add DutyBuilderRegistration
- Update tests to include the registration duty 
ticket: #849

core: add builder registration duty type

---

app/app.go
app/simnet_test.go
core/scheduler/scheduler.go
core/scheduler/scheduler_test.go
core/validatorapi/validatorapi.go
testutil/validatormock/validatormock.go

Add unit test for builder proposer and fix few integration issues.
ticket: #809

app: add simnet builder proposer unit test

---

cmd/createenr.go
p2p/discovery.go

Improve error message when `p2p_external_hostname` flag cannot be resolved to an IP.
Previous: `failed to open peer DB: could not resolve p2p external host: lookup charon on 192.168.65.5:53: no such host
`
New: `failed to open enode: resolve IP of p2p external host flag: lookup charon on 192.168.65.5:53: no such host {"p2p_external_hostname":"charon"}
`
category: misc
ticket: none

p2p: improve external hostname error message

---

README.md

Removing lodestar VC from compatibility matrix since it has integration issues, see #473
category: docs
ticket: none

readme: remove lodestar VC

---

app/app.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go

Remove fallback workaround for eth2multi and trigger newly added refresh logic when no clients are active.
ticket: none

core/validator: leverage eth2multi refresh when no active peers

---

cluster/definition.go
cluster/distvalidator.go
cluster/helpers.go
cluster/lock.go
cluster/testdata/definition_v1_2_0.json
cluster/testdata/lock_v1_2_0.json
cluster/version.go
docs/configuration.md
go.mod

Refactors v1.2.0 to hex instead of base58 since that is standard ETH format for bytes.
ticket: #848

cluster: refactor v1.2.0 to hex

---

cmd/createcluster.go

Adds `--num-validators` flag to create cluster command which would facilitate in creation of clusters with multiple DVs.
ticket: none

cmd/createcluster: add `--num-validators` flag

---

.golangci.yml
core/deadline.go
core/deadline_test.go
core/tracker/tracker.go

Fix deadliner constructor issue which was due to having multiple different constructors.
category: bug
ticket: none

core: fix deadliner constructor bug

---

p2p/discovery.go

When `--p2p-allowlist` is not defined, it should default to "allow all". But an empty string results in a empty netlist which results in "allow none". This is only now a problem since geth's discv5 previously ignored `NetRestrict`. 
category: bug
ticket: none

p2p: fix empty allow list

---

core/signeddata.go

- Add missing functions required for vapi implementation
ticket: #849

core: missing functions signeddata builder registration

---

testutil/random.go

- Add random function for incoming vapi PR
ticket: #849

testutil: random function for builder registration needed for vapi

---

app/app.go
app/monitoringapi.go
app/monitoringapi_internal_test.go

This change pushed readyz metrics every 1 second. Earlier we were pushing this metric only when someone calls readyz endpoint. If no-one calls that endpoint it will show inactive on readyz grafana panel.
category: bug
ticket: #880

app: push readyz in background

---

cmd/createcluster.go

Adds fee recipient and name flags and use withdrawal address, fee recipient address and name in cluster lock creation. This will be useful for those who want to create a cluster without going through dkg process preferably centralised stakers.
ticket: #879

cmd/createcluster: add fee-recipient and name flags

---

dkg/disk.go
dkg/dkg.go

Replaces writing keystores, cluster-lock and deposit-data with just a sample.txt in checkWrites before starting DKG. This is done to avoid errors if number of operators are less than threshold in cluster-definition.
ref: https://discord.com/channels/849256203614945310/936387516251127838/1001384008715882576
category: bug
ticket: none

dkg: write sample file in checkWrites

---

dkg/sync/server.go

Mitigate against broken connections during DKG sync protocol shutdown. Only mark client as shutdown after successfully sending the response from the server. Note this still doesn't guarantee that the client will always receive it (the connection can break en-route), but this does reduce the scope of the race condition.
category: bug
ticket: none

dkg/sync: only shutdown server once response written

---

docs/goguidelines.md

Make our style more explicit and add examples.
ticket: none

docs: add more examples and details to tradeoffs

---

core/sigagg/sigagg_test.go

- Test for builder registration
- builder proposer typo on duty - was DutyProposer should be DutyBuilderProposer
can split these into 2 separate PR if needed
ticket: #849

core/sigagg: test for builder registration

---

p2p/p2p.go

Enables libp2p.Autonat feature by default on both Charon and BootNodes. This is required for holepunching but should not affect current networking in any negative way.
ticket: none

p2p: enable autonat

---

core/bcast/bcast.go
core/bcast/bcast_test.go

- bcast implementation for builder registration
- relevant test case
ticket: #849

core/bcast: implementation for builder registration

---

core/tracker/tracker.go

Fixes high cardinality label issue by using duty type instead of duty+slot.
category: bug 
ticket: none

core/tracker: fix metric label issue

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_flag.md
.github/ISSUE_TEMPLATE/feature_ticket.md
.github/workflows/add-issue-to-project.yml

Also adds a github action that auto assigns issues to the new board, saving us all precious moments of our day 😇 
Should really have split this into two PRs, let me know if that would be preferred.
category: misc
ticket: none

github: add issue templates

---

core/tracker/tracker.go

Fix high cardinality issue in tracker's failed duty counter.
category: bug
ticket: none

core/tracker: fix failed duty counter

---

cmd/createenr.go
cmd/enr.go
cmd/enr_internal_test.go

- `charon create enr` now errors when `charon-enr-private-key` already exists.
- `charon enr` now also outputs`secp256k1 pubkey`, `signature` and `seq` in addition to the `enr` when the `--verbose` flag is provided.
ticket: #893

cmd: write expanded form of enr in charon enr

---

dkg/dkg.go

Improves DKG sync protocol failure error logging:
- prefix `context cancelled` errors with `p2p connection failed, please retry DKG`
- Do not log redundant `context cancelled` errors for other peers.
ticket: none

dkg: improve sync failure errors

---

p2p/ping.go

Do not log `dial backoff` when ping fails since it isn't informative, rather log previous actual error.
category: bug
ticket: none

p2p: improve ping failing messages

---

app/app.go
core/validatorapi/validatorapi_test.go
testutil/compose/static/grafana/dash_simnet.json
testutil/validatormock/validatormock.go
testutil/validatormock/validatormock_test.go

Allows testing validator mock with external beacon node. Going to need this for E2E testing.
category: test
ticket: none

app: allow testing vmock with external beacon node

---

app/monitoringapi_internal_test.go

Disables flapping monitoring API test until it is fixed. This isn't a critical test either.
category: test
ticket: #910

app: disable flapping monitoringapi test

---

cmd/bootnode.go
p2p/p2p.go

Bootnode logs number of connected libp2p nodes and connections. Makes existing log UDP discv5 explicit.
category: misc
ticket: none

cmd: improve bootnode logging

---

app/app.go
cmd/bootnode.go
p2p/p2p.go
testutil/validatormock/validatormock.go
testutil/validatormock/validatormock_test.go

Removes `--p2p-relay-loglevel` default, so global libp2p log level default is used, which is error. 
Also sneak in cached validator mock eth2client.
ticket: none

cmd: remove bootnode relay log default

---

cmd/bootnode.go

Allow bootnodes to scale horizontally by increase max reservation limit by 10x.
category: misc
ticket: none

cmd: increase bootnode max reservations

---

testutil/validatormock/validatormock.go

Similar to `scheduler` mitigate against `eth2http: failed to obtain validators` errors which happen when beacon node sync is behind by querying active validators by "head" instead of explicit "slot".
category: test
ticket: none

testutil/validatormock: mitigate future slot issues

---

core/validatorapi/validatorapi.go
eth2util/signing/signing.go
eth2util/signing/signing_test.go

Adds verification functions for each duty in eth2util/signing and use them in validatorapi.
ticket: #217

core/validatorapi: add verification functions to validatorapi

---

app/app_test.go
cmd/bootnode.go
dkg/dkg_test.go
go.mod
p2p/p2p.go

Increases bootnode max connections from 256 inbound to 1024 in and out.
category: misc
ticket: none

cmd: increase bootnode max connection limits

---

app/simnet_test.go
core/deadline.go
core/sigagg/sigagg_test.go
core/validatorapi/router.go
core/validatorapi/teku.go
core/validatorapi/validatorapi.go
eth2util/signing/signing.go
eth2util/signing/signing_test.go
testutil/beaconmock/options.go
testutil/beaconmock/server.go
testutil/beaconmock/static.json
testutil/validatormock/validatormock.go

- Fixes issue with builder registration domain calculation. 
- Also adds teku proposer config endpoint
- Also fixes registration deadline issue
- Adds integration test using teku/develop image.
ticket: #849

app: fix builder registration and add teku integration test

---

dkg/dkg.go
dkg/exchanger.go
dkg/exchanger_internal_test.go

Partial signature roots not known before DKG starts, but we need to register parsigex early to receive exchanged signatures.
Verifying partial signatures in parsigex in DKG is therefore difficult, so skip it, by reverting recent change that added it.
Added TODOs to verify signatures before aggregation rather.
ticket: none

dkg: revert parsigex signature verification

---

app/retry/retry.go

Catch and retry `Attestations must be from the current or previous epoch` errors when broadcasting.
ticket: none

app/retry: add another temporary error string

---

app/monitoringapi.go
app/monitoringapi_internal_test.go
app/simnet_test.go

Simplify readyz monitoring endpoint ready checker. 
Instead of actually pinging, just check if we have existing connections. If we do not have enough connections for 3 rounds, then assume connection issues. Since temporary blips should be ignored.
That also addresses the issue of dial error reasons being swallowed by this logic which resulted in logs only showing `Dial Backoff` which is not informative. This therefore removes a source of swallowed real reasons.
ticket: none

app: simplify monitoring ready checker

---

app/monitoringapi.go
app/monitoringapi_internal_test.go

Corrects calculation of charon status where it needs to exclude self when comparing the number of connected peers with threshold. Also updates tests.
category: bug
ticket: none

app: correct charon status calculation

---

core/validatorapi/teku.go

- omit if empty on propser config overrides currently getting -,"builder":{"enabled":false,"registration_overrides":null} 
ticket: #849

core/validatorapi: omit if empty on the proposer config

---

testutil/compose/static/grafana/dash_simnet.json

Adds memory and cpu and goroutine panels to simnet dash. CPU panel isn't working, need to figure out why...
category: test
ticket: none

testutil/compose: add cpu and memory to simnet dashboard

---

app/app.go
core/consensus/component.go
core/consensus/component_test.go

Fixes leaked context in consensus stream handler due to variable shadowing.
Also trim receive channel on duty deadline.
category: bug
ticket: #974

core/consensus: fix memory leak

---

core/parsigex/parsigex.go
eth2util/signing/signing.go
testutil/compose/compose/main.go
testutil/compose/config.go
testutil/compose/run.go
testutil/compose/testdata/TestDockerCompose_run_template.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden

Adds tracing spans to signature verification in parsigex.
- Also increase parsigex handle timeout from 1s to 5s since signature verification takes 200ms per sig...
- Also allow compose to bind to ports to allow pprof on charon.
category: misc
ticket: none

core/parsigex: instrument signature verification

---

core/tracker/tracker.go
testutil/compose/compose/main.go

Fixes golangci-lint on main.
ticket: none

testutil/compose: fix golangci-lint

---

core/scheduler/scheduler.go
core/scheduler/scheduler_test.go

Improve scheduler errors when querying mismatching proposer duties ito builder-api config.
category: misc
ticket: none

core/scheduler: improve builder-api config error

---

app/expbackoff/expbackoff.go
app/expbackoff/expbackoff_test.go

Implements an exponential backoff package based on `google.golang.org/grpc@v1.48.0/backoff`. This is to be used in many places where we have `// TODO(corver): improve backoff`
ticket: none

app/expbackoff: implement exponential backoff package

---

app/app.go
app/app_test.go
app/featureset/featureset.go
app/lifecycle/order.go
app/lifecycle/orderstart_string.go
p2p/discovery.go
p2p/gater_test.go
p2p/p2p.go

Inverts the integration between  discv5 and libp2p from pull to push.
ticket: #985 
feature_flag: invert_discv5

p2p: invert peer discovery integration

---

app/app.go
app/app_test.go
app/featureset/featureset.go
app/lifecycle/order.go
app/lifecycle/orderstart_string.go
p2p/discovery.go
p2p/p2p.go
p2p/relay.go

Inverts relay address routing from pull based to pull based.
ticket: #989 
feature_flag: invert_libp2p_routing

p2p: invert relay address routing

---

app/app.go
app/simnet_test.go
core/validatorapi/teku.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go

- Use fee recipient from cluster lock or withdrawal address if fee recipient not set for builder api registrations
- Add gas limit to proposer config as hardcoded const - while the VC's will default to a value this value may be different between VC clients so between to hardcode it to a known value
ticket: #849

core/validatorapi: teku proposer config updates

---

app/app.go
app/app_test.go
app/featureset/featureset.go
cmd/bootnode.go
core/tracker/tracker.go
dkg/dkg.go
p2p/bootnode.go
p2p/discovery.go
p2p/discovery_internal_test.go
p2p/discovery_test.go
p2p/gater.go
p2p/gater_test.go
p2p/p2p.go
p2p/peer.go
p2p/relay.go
testutil/random.go

Introduces the `p2p.MutablePeer` that can change over time, integrate that with all the logic using relays/bootnodes. Continuously resolve HTTP bootnode ENRs, and update `MutablePeer`.
ticket: #952

p2p: continuously resolve bootnode ENRs

---

.pre-commit/run_tests.sh

Adds timeout flag to pre-commit tests so that they timeout early rather than blocking forever.
category: misc
ticket: none

precommit: add timeout to pre-commit tests

---

app/app.go
app/retry/retry.go
core/deadline.go
core/deadline_test.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go

Adds 2 deadliners in tracker: analyser and deleter. When analyser deadline hits, tracker analyser failures and participation. When deleter deadline hits track trims internal state of duties.
category: bug
ticket: #993

core/tracker: add analyser and deleter

---

cmd/bootnode.go
p2p/name_test.go
p2p/relay.go

Libp2p relay reservation limits are quirky, the act more as "rate-limits" than "active reservation limits", see https://github.com/libp2p/go-libp2p/issues/1713. Remove these limits for now since charon nodes that are crash looping, easily exceed rate limits even though no additional resources are used on the bootnode. 
Also improve reservation backoff to decrease log frequency.
category: misc
ticket: none

cmd: remove bootnode reservation limits

---

testutil/compose/static/grafana/dash_simnet.json

Adds a peer summary table to the simnet dashboard.
category: misc
ticket: none

testutil/compose: add peer table to simnet dash

---

app/app.go
core/bcast/recast.go
core/interfaces.go
core/scheduler/metrics.go
core/scheduler/scheduler.go
core/scheduler/scheduler_test.go
core/types.go

Adds the recaster component to rebroadcast builder registrations every epoch.
ticket: #1009

core/bcast: add recaster to rebroadcast registrations every epoch

---

testutil/compose/compose/smoke_internal_test.go

Fixes golangci-lint by removing deadcode and commented code.
ticket: none

compose: fix golangci-lint

---

.pre-commit-config.yaml
app/app.go
cluster/cluster_internal_test.go
cluster/definition.go
cluster/helpers.go
cluster/lock.go
cluster/lock_test.go
cluster/operator.go
cluster/test_cluster.go
cmd/dkg.go
cmd/run.go
core/consensus/component_test.go
dkg/dkg.go
dkg/dkg_test.go
docs/configuration.md
tbls/tblsconv/tblsconv.go
testutil/compose/lock.go
testutil/compose/testdata/TestDockerCompose_lock_dkg_template.golden
testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_run_template.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden

Adds `--no-verify` flags to `charon run` and `charon dkg`. Verify config otherwise.
Note that `charon create cluster` requires `--no-verify` since it doesn't sign the generated lock file.
ticket: #589

cluster: verify config signatures

---

app/featureset/config.go
app/featureset/featureset.go
app/log/config.go

Fixes concurrent-map-write issue in unit tests that do multiple `app.Run`.
category: misc
ticket: none

app: fix global concurrent write issue

---

.pre-commit-config.yaml

Updates golangci-lint to lateset version which adds support for go1.18 to many linters.
category: misc
ticket: none

precommit: update golangci

---

.golangci.yml
app/app.go
app/app_test.go
app/simnet_test.go
p2p/ping.go

Attempt to fix flapping `TestPing/bootnode_and_stale_enrs` test which is caused by large backoff.
ticket: none

p2p: override ping backoff during testing

---

.golangci.yml
app/app.go
app/monitoringapi.go
core/bcast/bcast.go
core/deadline.go
core/fetcher/fetcher.go
core/parsigex/parsigex.go
core/scheduler/scheduler.go
core/scheduler/scheduler_test.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
eth2util/signing/signing.go
testutil/beaconmock/beaconmock.go
testutil/validatormock/validatormock.go
testutil/validatormock/validatormock_test.go

Use new `eth2wrap.Client` instead of `eth2client.Service` and the many different eth2Providers and casting.
Also fix some linting issues.
ticket: none

app: use eth2wrap client throughout

---

cluster/definition.go
cluster/lock.go
cmd/createcluster.go
cmd/createcluster_internal_test.go
cmd/createdkg.go
testutil/compose/lock.go
testutil/compose/testdata/TestDockerCompose_lock_dkg_template.golden
testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_run_template.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden

Verification of unsigned `charon create cluster` lock files succeed avoiding the need for `--no-verify`.
category: bug
ticket: #1025

cluster: skip verification if locally created

---

.github/workflows/release.yml

Marks the auto-generated release as draft allowing manual editing before publishing the release.
category: misc
ticket: none

github: mark auto-generated release as draft

---

app/eth2wrap/eth2wrap.go
app/forkjoin/forkjoin.go
app/forkjoin/forkjoin_test.go
go.mod
go.sum

Fix goroutine leak in forkjoin by adding a cancel function to cleanup resources.
category: bug
ticket: none

app/forkjoin: add close method to clean resources

---

cmd/cmd_internal_test.go
cmd/run.go
docs/configuration.md

Update/Add the new DNS of the public HA bootnodes
category: misc
ticket: https://github.com/ObolNetwork/charon/issues/895

cmd: update ha bootnode dns

---

cmd/createenr.go
cmd/createenr_internal_test.go
cmd/enr.go

Makes ENR creation deterministic by creating ENRs directly from enr.Record.
ticket: none

cmd/createenr: make ENR creation deteministic

---

testutil/genchangelog/main.go

Fixes golangci-lint workflow on main.
ticket: none

testutil/genchangelog: fix golangci-lint on main

---

testutil/trackpr/track.go

Improve errors and test if `trackpr` works.
category: misc
ticket: none

testutil/trackpr: improve error

---

core/scheduler/metrics.go
testutil/compose/compose/main.go
testutil/compose/lock.go
testutil/compose/static/grafana/dash_simnet.json
testutil/compose/testdata/TestDockerCompose_lock_create_template.golden
testutil/compose/testdata/TestDockerCompose_lock_create_yml.golden

Replaces short pubkey to long hex pubkey and adds beaconcha.in URIs to simnet dashboard. Also configure simnet to take multiple validators.
ref: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/43
category: misc
ticket: none

core/scheduler: add hex pubkey and beaconcha.in URIs

---

app/app.go
app/metrics.go
testutil/compose/static/grafana/dash_simnet.json

Add metric for `threshold`, `num_validators` and `peer_name`.
category: misc
ticket: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/65

app: add metric for threshold and num validators

---

dkg/exchanger.go
testutil/compose/compose/smoke_internal_test.go

Fixes deadlock in dkg and reduce NumValidators in "very large" smoke test which was causing timeout in our github actions.
category: bug
ticket: none

dkg: fix dkg and smoke test

---

app/app.go
app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/eth2wrap_test.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/httpwrap.go
core/scheduler/scheduler_test.go
core/validatorapi/eth2types.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
core/validatorapi/validatorapi.go
eth2util/eth2exp/attagg.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/beaconmock_test.go
testutil/beaconmock/options.go

Adds BeaconCommitteeSubscriptionsSubmitter interface to eth2wrap and beaconmock.
ticket: #1061

app/eth2wrap: add BeaconCommitteeSubscriptionsSubmitter interface to eth2wrap

---

core/signeddata.go
core/signeddata_test.go
core/types.go
core/types_test.go

Adds DutyPrepareAggregator and signed data type for BeaconCommitteeSubscription.
ticket: #1064

core: add signed data type for BeaconCommitteeSubscription

---

core/dutydb/memory.go
core/dutydb/memory_test.go
core/interfaces.go
core/unsigneddata.go
core/unsigneddata_test.go

Adds support for DutyPrepareAggregatir to DutyDB.
ticket: #1064

core/dutydb: add support for DutyPrepareAggregator to DutyDB

---

core/dutydb/memory.go
core/signeddata.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
eth2util/hash.go
eth2util/hash_test.go
eth2util/signing/signing.go
eth2util/signing/signing_test.go

Adds support for DutyPrepareAggregator to validatorapi. Also adds signature verification function as `VerifyBeaconCommitteeSubscription` to eth2util/signing/signing.go.
ticket: #1067

core/validatorapi: add support for DutyPrepareAggregator to vapi

---

core/parsigex/parsigex.go
core/parsigex/parsigex_test.go
core/proto.go
core/proto_test.go
testutil/random.go

Add support for `DutyPrepareAggregator` to `parsigex` component.
ticket: https://github.com/ObolNetwork/charon/issues/1065

core/parsigex: add support for DutyPrepareAggregator to parsigex

---

core/bcast/bcast.go

Fix linter error by adding `gocognit` nolint directive to `Broadcast()` method.
ticket: none

core/bcast: fix linter

---

core/dutydb/memory.go
core/dutydb/memory_test.go
core/interfaces.go
core/unsigneddata.go
core/unsigneddata_test.go

Revert changes in DutyDB for DutyPrepareAggregator as they are no longer required.
ticket: none

core/dutydb: revert changes in DutyDB for DutyPrepareAggregator

---

cluster/definition.go
dkg/disk.go
dkg/disk_internal_test.go

Configure --no-verify for config_hash and definition_hash verifications by adding VerifyHashes method to Definition.
ticket: #1084

dkg: add --no-verify for hash verifications

---

app/app.go
app/simnet_test.go
cluster/cluster_test.go
cluster/definition.go
cluster/distvalidator.go
cluster/lock.go
cluster/operator.go
cluster/ssz.go
cluster/test_cluster.go
cluster/testdata/cluster_lock_v1_3_0.json
cmd/createcluster.go
dkg/disk_internal_test.go
dkg/dkg.go
dkg/dkg_test.go

Aligns lock hash with canonical ssz types.
ticket: #1082

cluster: align lock hash with canonical ssz types

---

tbls/tss_test.go

Use `b.StopTimer` and `b.StartTimer` to exclude benchmark preparations from actual benchmark. 
category: test
ticket: none

tbls: refactor benchmark test

---

cmd/createdkg.go
cmd/createdkg_internal_test.go

Add a check for existing cluster-definition.json file. This will error out and leave the current file intact.
category: bug
ticket: #1062

cmd/createdkg: add existing cluster definition check

---

core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
eth2util/eth2exp/attagg_test.go

Adds CalculateCommitteeSubscriptionResponse for calculating response for an aggregated subscription obtained from aggsigdb in validatorapi.
ticket: #1067

core/validatorapi: add CalculateCommitteeSubscriptionResponse in vapi

---

core/types.go
core/types_test.go
dkg/exchanger.go

Add duty type for `DutyAggregator`.
ticket: #1075

core/types: add duty type for `DutyAggregator`

---

app/app.go
dkg/dkg.go

Use freshly calculated definition hashes when it is empty (`--no-verify` flag is used).
category: bug 
ticket: none

dkg: use calculated definition hash if no verify

---

eth2util/signing/signing.go
eth2util/signing/signing_test.go

Adds signature verification to eth2util/signing for SignedAggregateAndProof.
ticket: #1094

eth2util/signing: add signature verification for SignedAggregateAndProof

---

app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
core/signeddata.go
core/signeddata_test.go
testutil/beaconmock/beaconmock.go

Adds required interfaces to eth2wrap and signed data for SignedAggregateAndProof.
ticket: #1094

core: add interfaces and signed data for attestation aggregation

---

core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
core/signeddata.go
core/unsigneddata.go
eth2util/eth2exp/attagg_test.go
testutil/random.go

Add support for `DutyAggregator` to `fetcher`.
ticket: #1088

core/fetcher: add support for `DutyAggregator`

---

core/interfaces.go
core/validatorapi/validatorapi.go

Add missing methods to `ValidatorAPI` interface.
ticket: none

core: add missing methods to `ValidatorAPI` interface

---

core/parsigex/parsigex.go
core/parsigex/parsigex_test.go

Adds signature verification to parsigex for DutyAggregator.
ticket: #1095

core/parsigex: add signature verification to parsigex for DutyAggregator

---

core/bcast/bcast.go
core/bcast/bcast_test.go
testutil/random.go

Add support for `DutyAggregator` to bcast.
ticket: #1096

core/bcast: add support for `DutyAggregator`

---

cmd/bootnode.go

Also increase max number of connections per peer. Found while trying to create large clusters.
category: misc
ticket: none

cmd: increase bootnode number of connections per peer

---

core/bcast/bcast.go
core/validatorapi/validatorapi_test.go
eth2util/eth2exp/attagg.go

Add the selection proof (and all other related fields) to the `BeaconCommitteeSubscriptionResponse`
ticket: none

eth2util/eth2exp: add selection proof to committee response

---

core/proto.go
core/proto_test.go
core/unsigneddata.go

Adds support for duty aggregator signed data and unsigned data types to proto unmarshal.
ticket: none

core: add support for duty aggregator to proto

---

dkg/disk.go
dkg/dkg.go

Increases GET remote definition timeout to 10s from 5s. Also add logs.
category: misc
ticket: none

dkg: increase GET remote definition timeout

---

app/app.go
app/disk_internal_test.go

Fail fast when p2pkey doesn't match any lock file operator ENRs.
ticket: #937

app: verify p2pkey before starting libp2p

---

app/app.go
cluster/cluster_internal_test.go
cluster/cluster_test.go
cluster/definition.go
cluster/examples/cluster-lock-000.json
cluster/examples/cluster-lock-001.json
cluster/examples/cluster-lock-002.json
cluster/helpers.go
cluster/operator.go
cluster/ssz.go
cluster/test_cluster.go
core/validatorapi/teku.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
dkg/disk.go
dkg/dkg.go

Fixes issue of "invalid lock hash" when older versions of cluster locks contains checksummed addresses.
category: bug
ticket: #1153

cluster: fix hashing of legacy checksummed addresses

---

app/app.go
app/disk_internal_test.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go

Delay tracking on startup to mitigate failed duties due to VC startup delay. 
category: misc
ticket: #983

core/tracker: delay tracking on startup

---

app/app.go
app/metrics.go
core/scheduler/metrics.go
core/scheduler/scheduler.go

Add metric for `num_validators`. This will be used in aggregate dashboard to show the total number of validators across all charon clusters.
ticket: none

app: add metric for num_validators

---

.golangci.yml
app/app.go
app/app_test.go
app/eth2wrap/eth2wrap.go
app/log/metrics.go
app/metrics.go
app/promauto/promauto.go
app/promauto/promauto_test.go
app/simnet_test.go
core/bcast/metrics.go
core/parsigdb/metrics.go
core/scheduler/metrics.go
core/tracker/metrics.go
core/validatorapi/metrics.go
p2p/metrics.go

Workaround the problem of wrapping the `prometheus.DefaultRegisterer` with runtime labels while `promauto` references it during package initialisation.
category: bug
ticket: #1142

app/promauto: workaround to wrap promauto registerer

---

core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
core/tracker/component_string.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go

Adds support for DutyAggregator and DutyPrepareAggregator failures to tracker.
ticket: #1154

core/tracker: update tracker for DutyAggregator

---

app/errors/context.go
app/errors/context_test.go
app/retry/retry.go
app/vmock.go
dkg/dkg.go

Improve logging when duties expire and do not log vmock errors on shutdown.
category: misc
ticket: none

app: improve logging

---

core/fetcher/fetcher.go
core/tracker/tracker.go

Improve tracker participation logging to only log changes to each duty type.
Also log when attester aggregation resolved.
category: misc
ticket: none

tracker: improve participation logging

---

app/app.go
app/disk_internal_test.go
dkg/dkg.go
p2p/peer.go
p2p/peer_test.go

This was only added to `charon run`, also doing this in dkg now.
ticket: #937

dkg: verify private key before p2p setup

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/httpwrap.go
app/eth2wrap/success.go
app/retry/retry.go
app/vmock.go
core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
core/validatorapi/router_internal_test.go
testutil/validatormock/attest.go
testutil/validatormock/validatormock_test.go

Fixes panic in fetcher when `AggregateAttestation` isn't found and go-eth2-client returns `nil,nil`. This can happen when using infura and the `SubmitBeaconCommitteeSubscription` was processed by a different node. Just retry in that case.
Also use proper timeout for eth2exp calls (2s is too short).
category: bug
ticket: none

core/fetcher: support aggregate attestation not found

---

app/app.go
app/metrics.go
testutil/compose/static/grafana/dash_simnet.json

Remove `lockHashGauge` as we now have `cluster_hash` label for all metrics.
category: misc
ticket: none

app: remove lockhash gauge

---

core/bcast/bcast.go
core/consensus/component.go
core/fetcher/fetcher.go
core/parsigdb/memory.go
core/scheduler/scheduler.go
core/sigagg/sigagg.go
core/validatorapi/validatorapi.go

Use common prefix for all logging of each component:
- bcast: "Successfully submitted ..."
- parsigdb: "Partial signed data ..."
- qbft: "QBFT ..."
- sigagg: "Threshold aggregated ..."
Also:
- Sort attester duty logs by slot
- Remove noisy fields
- Remove noisy router debug logs
category: misc
ticket: none

core: improve logging

---

core/dutydefinition.go
core/signeddata.go
core/signeddata_test.go
core/unsigneddata.go
core/unsigneddata_test.go
testutil/random.go

Adds signed and unsigned types for sync committee duties.
ticket: #1177

core: add signed and unsigned types for sync duties

---

.github/workflows/release.yml

Add the GUTHUB_TOKEN env var so `genchangelog` uses authenticated API to avoid rate limits.
category: misc
ticket: #1039

github: add GITHUB_TOKEN env var to genchangelog

---

.github/workflows/pre-commit.yml
.github/workflows/release.yml

Disables shallow checkout for the release action so `genchangelog` can fetch the git commit history.
category: misc
ticket: #1039

github: disable shallow checkout for release action

---

app/retry/retry.go
core/scheduler/scheduler.go

Silences retryer timeout due to duty expiry errors, since `DutyAggregator` will trigger this constantly in all clusters. Rather rely on tracker to analyse and report duty failures.
Also remove noisy `slot` field from context since `duty` field already contains slot.
category: misc
ticket: none

app/retry: silence noisy duty expiry errors

---

eth2util/signing/signing.go
eth2util/signing/signing_test.go

Adds signature verification for sync committee message.
ticket: #1183

eth2util/signing: add sync message verify

---

p2p/receive.go
p2p/receive_test.go
p2p/sender.go

Adds canonical functions to send and receive protos via libp2p. This will be used in priority protocol. We can also refactor a lot of existing code to use these functions.
ticket: #1206

p2p: add canonical sending and receiving logic

---

cluster/cluster_internal_test.go
cluster/cluster_test.go
cluster/definition.go
cluster/helpers.go
cluster/helpers_internal_test.go
cluster/test_cluster.go
cluster/testdata/cluster_definition_v1_0_0.json
cluster/testdata/cluster_definition_v1_1_0.json
cluster/testdata/cluster_definition_v1_2_0.json
cluster/testdata/cluster_definition_v1_3_0.json
cluster/testdata/cluster_lock_v1_0_0.json
cluster/testdata/cluster_lock_v1_1_0.json
cluster/testdata/cluster_lock_v1_2_0.json
cluster/testdata/cluster_lock_v1_3_0.json

Refactor `EIP712 Domain` data to add support for different chains ids.
ticket: https://github.com/ObolNetwork/charon/issues/1203

cluster: refactor EIP712 domain data

---

core/parsigdb/memory.go
core/parsigdb/memory_internal_test.go
core/signeddata.go
core/types.go
testutil/random.go

Adds support for `DutySyncMessage` to parsigdb.
ticket: #1192

core/parsigdb: add support for DutySyncMessage to parsigdb

---

cluster/helpers.go
cluster/testdata/cluster_definition_v1_3_0.json
cluster/testdata/cluster_lock_v1_3_0.json

Fixes copy/paste bug when copying pattern from external reference. See https://github.com/attestantio/go-eth2-client/blob/master/spec/bellatrix/executionpayload_encoding.go#L277-L284.
category: bug 
ticket: none

cluster: fix bug when hashing byte lists

---

cluster/cluster_internal_test.go
cluster/cluster_test.go
cluster/definition.go
cluster/test_cluster.go
cluster/testdata/cluster_definition_v1_0_0.json
cluster/testdata/cluster_definition_v1_1_0.json
cluster/testdata/cluster_definition_v1_2_0.json
cluster/testdata/cluster_lock_v1_0_0.json
cluster/testdata/cluster_lock_v1_1_0.json
cluster/testdata/cluster_lock_v1_2_0.json
cluster/version.go

Skip EIP712 signature verification for versions earlier than v1.3.0.
ticket: #1203

cluster: skip sig verification for versions earlier than v1.3.0

---

cluster/definition.go

Fixes golangci-lint on main.
ticket: none

cluster: fix lint

---

core/bcast/bcast.go
core/bcast/bcast_test.go

Adds support for DutySyncMessage to bcast.
ticket: #1193

core/bcast: add support for DutySyncMessage to bcast

---

core/tracker/tracker.go
core/tracker/tracker_internal_test.go

Skip participation reporting if no peers participated and duty is not failed (like DutyAggregator)
category: misc
ticket: #1213

core/tracker: skip participation reporting

---

cluster/cluster_internal_test.go
cluster/definition.go

Re-adds support for definition signatures for older versions (v1.0-v1.2) using `--no-verify`. 
In other words:
- GIVEN: Users with a launchpad generated cluster definition or lock (version is v1.2 and contains signatures) 
- WHEN: They run either `charon dkg` or `charon run`
- THEN: They MUST use `--no-verify` or the programs will crash.
The bug is that it crashed even if `--no-verify` was used as we decided to drop support for these old signatures all-together since we assumed incorrectly that there were no users with these launchpad generated definitions.
category: bug 
ticket: none

cluster: add support for old definition signature using noverify

---

dkg/dkg.go

Replaces `Waiting to connecting to all peers...` with `Waiting to connect to all peers...`. Also changes a set of ellipses to a colon.
category: bug
ticket: none

dkg: fix grammar issue

---

testutil/compose/compose/main.go
testutil/compose/compose/smoke_internal_test.go
testutil/compose/config.go
testutil/compose/lock.go
testutil/compose/run.go
testutil/compose/static/grafana/dash_simnet.json
testutil/compose/testdata/TestDockerCompose_lock_dkg_template.golden
testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_run_template.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden
testutil/compose/testdata/TestNewDefaultConfig.golden

Changes compose log format to `logfmt` when running with `-loki` which results in new log panels being populated in the simnet dash.
ticket: none

testutil/compose: add loki log panels to simnet dashboard

---

core/validatorapi/router.go
core/validatorapi/router_internal_test.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
eth2util/signing/signing.go

Adds support for `DutySyncMessage` to validatorapi component. Also, adds tests.
ticket: #1188

core/validatorapi: add support for `DutySyncMessage`

---

cmd/enr.go
cmd/enr_internal_test.go

`charon enr --verbose` reports wrong value for decoded k1 public key. This PR fixes it.
category: bug 
ticket: none

cmd: fix `charon enr --verbose` bug

---

app/app.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
cluster/definition.go
core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
core/validatorapi/router.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go

Handles fee recipient address by adding a slot subscriber to scheduler which calls prepare_beacon_proposer endpoint at the start of each epoch.
ticket: #1100

app: handle fee recipient

---

cmd/enr.go
cmd/enr_internal_test.go

Output all information pertaining to a decoded ENR for `charon enr --verbose`.
ticket: #998

cmd: output all info in `charon enr --verbose`

---

p2p/metrics.go
p2p/p2p.go
testutil/compose/static/grafana/dash_simnet.json

Adds the `p2p_peer_connection_types` gauge vector with labels `peer` and `type` that indicates the number of current connections to each peer by type.
Also adds to simnet dashboard.
category: misc
ticket: #1243

p2p: add relayed connection metric

---

app/app.go
cmd/bootnode.go
cmd/cmd_internal_test.go
cmd/createenr.go
cmd/dkg.go
cmd/enr.go
cmd/enr_internal_test.go
cmd/run.go
dkg/dkg.go
docs/configuration.md
p2p/discovery.go
p2p/discovery_test.go
p2p/p2p.go
p2p/peer_test.go

* Removes default values for `p2p-tcp-address` and `p2p-udp-address`. 
* Errors if `--p2p-udp-address==""` and `--p2p-bootnode-relay=false` and `--p2p-bootnodes-from-lockfile==false`.
* Sets`--p2p-bootnode-relay` default value to true.
* Output all information pertaining to a decoded ENR for `charon enr --verbose`.
ticket: #998

cmd: remove default values for `p2p-tcp-address` and `p2p-udp-address`

---

cmd/run.go
docs/configuration.md

Removes deprecated `--beacon-node-endpoint` flag.
category: misc
ticket: none

cmd: remove deprecated `--beacon-node-endpoint` flag

---

core/scheduler/scheduler.go

Emit slot events asynchronously so subscribers do not interfere with each other.
ticket: none

core/scheduler: async slot events

---

core/signeddata.go
core/signeddata_test.go

Refactors `SignedSyncContribution` to `SignedSyncContributionAndProof`. This makes it non-ambiguous since `SyncContribution` and `SyncContributionAndProof` are two different types.
ticket: none

core: rename `SignedSyncContribution` to `SignedSyncContributionAndProof`

---

app/app.go
app/version/version.go
cmd/bootnode.go
cmd/createdkg.go
dkg/dkg.go

Adds a common function to log charon version information on startup.
ticket: #1194

version: log charon version info on startup

---

app/app.go
cmd/bootnode.go
cmd/cmd.go
cmd/dkg.go
cmd/run.go
dkg/dkg.go

Inits logging as soon as log flags are parsed in printFlags function.
category: bug
ticket: #1272

cmd: add init logger in printFlags

---

core/validatorapi/eth2types.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
testutil/beaconmock/options.go

Adds support for sync committee duties to validatorapi.
ticket: #1261

core/validatorapi: add sync committee duties to validatorapi

---

dkg/dkg.go
dkg/sync/server.go
p2p/discovery.go
p2p/p2p.go

Removes duplicate `Connected to peer 3 of 4` logs when relay circuits reconnect.
Also removes colons and periods from other logs.
category: misc
ticket: none

dkg: remove reconnected logs

---

p2p/metrics.go
p2p/p2p.go
testutil/compose/static/grafana/dash_simnet.json

Zero connection type metrics so combing them in prometheus queries is simpler.
Update simnet dash.
category: misc
ticket: none

p2p: zero connection type metrics

---

app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
core/bcast/bcast.go
core/bcast/bcast_test.go
core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
core/parsigex/parsigex_test.go
core/signeddata.go
core/types.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
eth2util/eth2exp/attagg.go
eth2util/eth2exp/attagg_test.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go
testutil/random.go

Optimisation to remove usage of `/eth/v1/beacon/states/head/committees` when calculating `is_aggregator` since it downloads 3.3MB on prater and probably more on mainnet. Rather use the in-memory available attester duty field and cache it.
ticket: none

core/validatorapi: cache commitee length with committee subscriptions

---

app/retry/retry.go
app/retry/retry_test.go

This attempts to fix the flapping `app` tests due to shutdown timeout by cancelling the async contexts on shutdown.
category: bug
ticket: none

app/retryer: cancel async context on shutdown

---

core/parsigdb/memory_internal_test.go
core/proto.go
core/signeddata.go
core/signeddata_test.go

Fixes bug in beacon committee subscription json marshalling that didn't include committee length.
category: bug
ticket: none

core: fix beacon committee subscription marshalling

---

app/app.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
app/simnet_test.go
app/vmock.go
core/validatorapi/router.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go
testutil/beaconmock/server.go
testutil/validatormock/attest.go
testutil/validatormock/synccomm.go
testutil/validatormock/synccontributionflow_test.go

Integrates DutySyncMessage by adding support to validatormock and adds a simnet_test.
ticket: #1261

testutil/validatormock: integrate DutySyncMessage

---

app/peerinfo/peerinfo.go

Reset previous peerinfo metrics when peer githash or version changes.
Also do basic sanity check on values (since peers can send arbitrary values). 
category: bug
ticket: none

app/peerinfo: reset peer info metrics

---

app/metrics.go
app/monitoringapi.go
app/monitoringapi_internal_test.go
app/peerinfo/peerinfo.go
app/simnet_test.go
testutil/compose/static/grafana/dash_simnet.json

Instruments not ready reasons for improved UX. 
Also fix a "concurrent map write" panic in peerinfo.
ticket: #999

app: instrument not ready reasons

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/eth2wrap_test.go
app/eth2wrap/genwrap/genwrap.go

Decompose and return structured errors from eth2wrap to support better error groupability and metrics with improved signal to noise.
ticket: none

app/eth2wrap: return structured errors

---

app/peerinfo/peerinfo.go
p2p/sender.go

Fixes issue with `PeerInfo` protocol reporting `zero` values like `SentAt`. This was due to missing returned error from `p2p.Sender.SendReceive`.
category: bug
ticket: #1295

p2p: fix missing error from SendReceive

---

eth2util/eth2exp/attagg.go
eth2util/eth2exp/attagg_old.go
testutil/validatormock/synccontributionflow_test.go

Specs the 2 new "aggregate selection" endpoints to support aggregations in middleware DVT clusters.
- `POST /eth/v1/aggregate/beacon_committee_selections`
- `POST /eth/v1/aggregate/sync_committee_selections`
VCs should call these at the start of the slot to fetch a DVT aggregate selection proof for use in committee aggregator duties (both beacon committee and sync committee).
```
// BeaconCommitteeSelectionAggregator is the interface for aggregating beacon committee selection proofs in a DVT cluster.
type BeaconCommitteeSelectionAggregator interface {
// AggregateBeaconCommitteeSelections returns DVT aggregated beacon committee selection proofs.
// This would call a new BN API endpoint: POST /eth/v1/aggregate/beacon_committee_selections
AggregateBeaconCommitteeSelections(ctx …
```

eth2util/eth2exp: spec new proposal aggregate endpoint

---

dkg/dkg_test.go

Fixes flapping test due to bind errors by cancelling the context so all nodes exit. Previously, the test timed out on bind errors.
category: test
ticket: none

dkg: fix flapper due to bind error

---

app/eth2wrap/eth2wrap.go
testutil/validatormock/synccomm.go

Fixes on issue in validatormock that subscribes to sync committee subnets even if no duties are present.
category: bug
ticket: none

testutil/validatormock: only subscribe contributions if duties

---

app/simnet_test.go

Attempts to fix the flapping test due to shutdown timeout. The problem is that the http request context is not closed when the server is shutdown. So rather use the external test context in the select.
category: test
ticket: none

app: fix test shutdown timeout

---

main.go

Don't handle any signals (specifically SigTERM) as it causes docker containers to hang if stopped.
category: bug 
ticket: none

main: don't handle kill signal

---

app/app.go
core/deadline.go

Aid in debugging when warning occurs.
```
WARN app-start  Deadliner output channel full
```
category: misc
ticket: none

core: add label to deadliner

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_test.go
go.mod
go.sum

Upgrade to latest go-eth2-client and handle structured errors.
category: misc
ticket: none

app/eth2wrap: decompose eth2client http errors

---

core/signeddata.go
core/signeddata_test.go
core/types.go

Add explicit unsigned data message root function to signed data as a better way to ensure consistent unsigned data in parsigdb. Relying on json serialisation to check for consistent signed data is brittle.
ticket: #1347

core: add message root to signed data interface

---

app/app.go
app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/httpwrap.go
core/dutydefinition.go
core/scheduler/offset.go
core/scheduler/scheduler.go
core/scheduler/scheduler_test.go
core/types.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go

Adds support for sync committee duties to the `scheduler` component.
ticket: https://github.com/ObolNetwork/charon/issues/1265

core/scheduler: adds support for sync committee duties

---

core/parsigdb/memory.go
core/parsigdb/memory_internal_test.go
core/tracker/tracker.go
core/tracker/tracker_internal_test.go

Use message root for partial signed data consistency check in parsigdb. Also do the same in tracker.
ticket: #1347

core/parsigdb: use message root for consistency check

---

core/tracker/tracker.go
core/tracker/tracker_internal_test.go

Fixes a bug in the newly added logic in tracker that checks for consistent partial signed message roots. It didn't support multiple validators performing a duty in the same slot.
category: bug
ticket: #1347

core/tracker: fix inconsistent message logic

---

core/fetcher/fetcher.go
core/fetcher/metrics.go

Adds a counter metric to monitor inconsistent attestation data obtained from beacon node for the same slot.
category: misc
ticket: none

core/fetcher: monitor inconsistent attestation data

---

core/dutydefinition.go
core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
core/signeddata.go
eth2util/eth2exp/attagg_old.go
eth2util/eth2exp/attagg_test.go
testutil/beaconmock/options.go
testutil/random.go
testutil/validatormock/attest.go

Adds support for `DutySyncContribution` to fetcher.
ticket: #1266

core/fetcher: add support for `DutySyncContribution`

---

core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
eth2util/signing/signing.go
testutil/random.go

Verify inner attestation aggregation selection proof, not just the aggregation signature. This should fix the sporadic aggregation failures which I suspect is due to the cluster running both validatormock and teku, and that teku is per-chance submitting aggregation using legacy selection proofs in the same slot. It is also good practice to verify all signatures.
category: bug
ticket: #1343

core/validatorapi: verify attestation aggregation selection proof

---

core/dutydb/memory.go
core/dutydb/memory_test.go
core/interfaces.go
core/unsigneddata.go

Adds support for `DutySyncContribution`.
ticket: #1270

core/dutydb: add support for `DutySyncContribution`

---

core/scheduler/metrics.go
core/scheduler/scheduler.go

Skip missed slots in scheduler to avoid thundering heard due to pause-the-world-events.
category: misc
ticket: none

core/scheduler: skip missed slots

---

app/app.go
cmd/createcluster.go

Revert failing on invalid forkversion as it seems to be a common use-case in the wild.
category: bug 
ticket: none

app: revert invalid forkjoin error

---

core/eth2signeddata.go
core/eth2signeddata_test.go
core/signeddata.go
eth2util/signing/signing.go
eth2util/signing/signing_test.go

Adds tests for eth2signeddata.
category: test
ticket: #920

core: add tests for eth2signeddata

---

core/eth2signeddata.go
core/eth2signeddata_test.go
core/parsigex/parsigex_test.go
core/signeddata.go
testutil/random.go

Implement core.Eth2SignedData for SyncCommitteeSelection to support signature verification.
ticket: #1264

core: add verification for sync selection

---

core/eth2signeddata_test.go
core/signeddata.go
core/validatorapi/eth2types.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
eth2util/signing/signing.go
testutil/random.go

Adds support for `DutySyncContribution` to validatorapi.
ticket: #1267

core/validatorapi: add support for `DutySyncContribution`

---

core/eth2signeddata.go
core/proto.go
core/proto_test.go
core/signeddata.go
core/signeddata_test.go
core/unsigneddata.go

Adds support for sync committee duties data to proto. 
ticket: #1263

core: add sync committee duties to proto

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_test.go

Fixes panic when `net.OpError` have nil `Addr` field.
category: bug
ticket: none

app/eth2wrap: fix panic on unexpected network errors

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_test.go

Fixes a race in `eth2wrap` forkjoin code when context is cancelled before any results are returned. This resulted in `<zero>,nil` being returned which resulted in unexpected behaviour, including "divide by zero".
category: bug
ticket: #1326

app/eth2wrap: fix cancelled context race

---

core/consensus/component.go
core/qbft/qbft.go
core/qbft/qbft_internal_test.go

Adds `timeout_reason` debug logging when consensus rounds timeout.
The reason would be either:
- `missing pre-prepare, missing leader=foo`
- `insufficient prepares, missing peers=[foo,bar]`
- `insufficient commits, missing peers=[bar,baz]`
category: misc
ticket: none

core/consensus: improve debug logs

---

app/simnet_test.go
app/vmock.go
testutil/validatormock/attest.go
testutil/validatormock/synccomm.go
testutil/validatormock/validatormock.go

Integrate `DutyPrepareSyncContribution` into validatormock.
category: feature  
ticket: #1262

validatormock: integrate `DutyPrepareSyncContribution`

---

app/version/version.go
core/consensus/component.go
core/infosync/infosync.go
core/priority/component.go
core/priority/prioritiser.go
core/priority/prioritiser_test.go
core/types.go
core/types_test.go
p2p/peer.go
p2p/peer_test.go

Adds the `infosync` component that prioritised cluster supported versions. Also add the `priority.Component` that wraps the prioritiser to hide protobuf types and do signing.
ticket: #1380

core/infosync: implement infosync priority protocol use case

---

app/eth2wrap/httpwrap.go
app/simnet_test.go
app/vmock.go
core/interfaces.go
core/signeddata.go
core/validatorapi/validatorapi.go
testutil/beaconmock/attestation.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go
testutil/validatormock/attest.go
testutil/validatormock/synccomm.go

Integrate `DutySyncContribution` into core workflow. Also, test on simnet.
ticket: #1268

core: integrate `DutySyncContribution`

---

core/tracker/tracker.go
core/tracker/tracker_internal_test.go

Updates tracker to mark sync message as unexpected as `DutySyncContribution` is scheduled now.
category: misc
ticket: none

core/tracker: mark sync message as unexpected

---

app/app_test.go

When a priority protocol is triggered and not all peers are ready it will complete with an empty result. Just ignore that for now. This fixes the flapping test.
category: test
ticket: none

app: ignore failed infosyncs

---

app/app.go
app/eth2wrap/cache.go
app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/eth2wrap_test.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/httpwrap.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go

Reduce overall latency and eth2client call rates by caching slow changing `validators_by_pubkey` in eth2wrap per epoch.
ticket: #1396

app/eth2wrap: cache validators by pubkey per epoch

---

testutil/validatormock/synccomm.go

Fixes problem in vmock that prepares sync committee selections even though no duties are present. Also avoid fetching block root in this case.
category: misc
ticket: none

testutil/validatormock: handle no sync committee duties properly

---

.github/workflows/test.yml
app/simnet_test.go
testutil/beaconmock/options.go

Adds table tests for simnet mock VCs.
category: test
ticket: #921

app: add table tests for simnet

---

app/app_test.go

Fix flapping test, was checking the wrong structure.
ticket: none

app: fix flapping info sync test

---

testutil/compose/alert.go
testutil/compose/auto.go
testutil/compose/compose/main.go
testutil/compose/config.go
testutil/compose/docker-compose.template
testutil/compose/smoke/smoke_test.go
testutil/compose/testdata/TestDockerCompose_define_create_yml.golden
testutil/compose/testdata/TestDockerCompose_define_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_lock_create_yml.golden
testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden

Refactors the `auto` command by moving it into the main `compose` repo. This simplifies the smoke tests and cleans up the compose cli `main` package.
category: test
ticket: #992

testutil/compose: refactor auto

---

.github/workflows/test.yml

Send a notification to discord if main branch tests fails. Currently we only send notifications on `pre-commit` failures.
category: misc
ticket: #1412

github: notify on trunk test failures

---

p2p/metrics.go
p2p/p2p.go
p2p/ping.go
p2p/sender.go

Refactor pings to be periodic (once per second). Currently we ping as fast as we can. In cloud clusters with low latency, this can go up to thousands of pings per second.
Also refactor the connection duration histogram into a connection counter as that is much simpler and easier to use in dashboards.
ticket: none

p2p: do periodic pings

---

cmd/bootnode.go

Increase bootnode libp2p relay connection limits from default 128kB to 2MB as the default is very small.
category: misc
ticket: #1420

cmd: increase bootnode connection data limit

---

cmd/bootnode.go

Increases relay limit to 32MB. This is to enable relays not dropping connections when load increases. QBFT exchange of beacon block in such a case when each peer exchanges beacon block (~2MB max) 4 times in a single consensus round. 
category: misc
ticket: none

cmd/bootnode: increase relay limit

---

core/fetcher/fetcher.go

Compare fee recipients from beacon block and cluster-lock properly considering since they can be in uppercase or lowercase.
category: misc
ticket: none

core/fetcher: compare fee recipients properly

---

testutil/compose/smoke/smoke_test.go

Log alerts on smoke test failure so we can debug them.
category: test
ticket: #992

testutil/smoke: log alerts on failure

---

app/app.go
app/app_test.go
app/featureset/featureset.go

Move priority protocol to beta feature as it still has a goroutine leak and needs a big refactor.
category: misc
ticket: #1421

app: refactor prioritise to beta feature

---

app/app.go
core/infosync/infosync.go
core/infosync/metrics.go
core/priority/component.go

Adds metrics to infosync in order to track results. 
Also refactor duty deadline by moving it to prioritise instead of infosync so users of prioritise do not need to worry about that.
ticket: #1421

core/infosync: add metrics

---

app/monitoringapi.go

Increase readyz insufficient peers hysteresis from 30s to 1min.
category: bug
ticket: #1426

app: increase insufficient peers hysteresis

---

app/app.go
app/simnet_test.go
core/validatorapi/teku.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go

Swallow unexpected validator registration based provided builderAPI flag.
category: misc
ticket: none

core/validatorapi: swallow unexpected validator registrations

---

core/priority/component.go
core/priority/prioritiser.go
p2p/receive.go
p2p/sender.go

Skip exchanging messages with peers that do not support the protocol. Add protocol to p2p logging. Do not error on deadline since this is expected.
ticket: #1421

core/priority: skip unsupported peers

---

app/app.go
app/disk_internal_test.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
testutil/beaconmock/options.go

- Do not attempt to set fee recipient if no active validators.
- Return empty response instead of 404 for `get_validators` (aligns with beacon node behaviour)
ticket: none

app: handle no active validators better

---

app/simnet_test.go
core/parsigdb/memory.go
core/parsigdb/memory_internal_test.go

Avoids signature aggregation and broadcast if threshold is already reached.
category: misc
ticket: none

core/parsigdb: avoid aggregating and submitting again

---

core/consensus/component.go

Adds the missing "insufficient round changes" reason. This happens when quorum peers do not send a round change, then no peer can send their pre-prepare.
category: bug
ticket: none

core/consensus: add missing 'insufficient round changes' reason

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/eth2wrap_test.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/httpwrap.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go

Add `block_attestation` endpoint to eth2wrap to fetch block attestations to calculate inclusion distance.
ticket: #1254

app/eth2wrap: add block attestation endpoint

---

core/scheduler/metrics.go
core/scheduler/scheduler.go
testutil/compose/static/grafana/dash_charon_overview.json

Adds label for validator status (e.g., `active`, `pending`, `exited` and so on) to balanceGauge.
category:  misc
ticket: none

core/scheduler: add label for validator status

---

app/app.go
core/parsigdb/memory.go
core/parsigdb/memory_internal_test.go
dkg/exchanger.go

Adds deadliner to parsigdb to trim expired duties.
ticket: none

core/parsigdb: add deadliner to trim state

---

app/app.go
app/lifecycle/order.go
app/lifecycle/orderstart_string.go
core/parsigdb/memory.go
core/parsigdb/memory_internal_test.go

Refactor trimming of parsigdb state to a dedicated goroutine since the deadliner's output buffer is small and overflows easily causing `Deadliner output channel full` errors.
category: bug
ticket: none

core/parsigdb: dedicated trimming goroutine

---

app/version/version.go

Bumps version to `v0.12.0`. 
category: misc
ticket: none

app/version: bump version

---

p2p/sender.go
p2p/sender_internal_test.go

Retry sends once on relay errors. This should solve 99% of the `stream reset` warnings of infosync and peerinfo protocols when using relay connections. This only now became an issue since these protocols do send-receive (other protocols did send and receive separately). 
category: bug 
ticket: none

p2p: retry send once on relay errors

---

core/consensus/component.go

Fixes nil map panic for `recvDropped` map in core/consensus/component.go. Found this while testing very-large cluster test in smoke tests.
category: bug
ticket: none

core/consensus: fix nil map panic

---

.github/workflows/test.yml
testutil/compose/alert.go
testutil/compose/auto.go
testutil/compose/compose_internal_test.go
testutil/compose/run.go
testutil/compose/smoke/smoke_test.go

Handle `docker-compose build` command separately before starting alerts collector. This step takes longer at first and takes almost no time to build again. This might be the reason why `default_alpha` test in smoke tests seldom completes. Also increased alert timeout for `very_large` test.
category: test
ticket: #992

testutil/compose: handle docker-compose build seperately

---

core/tracker/incldelay.go
core/tracker/incldelay_internal_test.go
core/tracker/inclusiondistance.go
core/tracker/metrics.go

Implement a function that calculates the clusters inclusion delay for a specific block.
ticket: #1254

core/tracker: implement inclusion delay tracker

---

app/peerinfo/peerinfo.go
app/peerinfo/peerinfo_test.go
p2p/sender.go

Refactor `p2p.SendReceiveFunc` to support explicit RTT callback via functional options. This solves the issue that external wrapping calculation includes opening connection delay.
category: bug
ticket: #1445

app/peerinfo: fix clock offset calculation

---

app/eth2wrap/eth2wrap_test.go
app/eth2wrap/httpwrap.go

Fixed incorrect http method in block attestation request client.
The error log was:
```
ERRO sched Emit scheduled slot event: beacon api block_attestations: request block attestations: get failed {"slot": 4392784, "label": "block_attestations", "status": 405, "body": "{\"code\":405,\"message\":\"METHOD_NOT_ALLOWED\",\"stacktraces\":[]}"} 
```
category: bug
ticket: none

app/eth2wrap: fix block attestation request

---

app/eth2wrap/eth2wrap_test.go
app/eth2wrap/httpwrap.go

Lighthouse returns a 404 if no block for the slot exists. Return empty attestation slice in this case.
Error log: 
```
Emit scheduled slot event: beacon api block_attestations: request block attestations: get failed 
{"code":404,"message":"NOT_FOUND: beacon block at slot 4397358","stacktraces":[]}
```
category: bug
ticket: none

app/eth2wrap: handle block attestations 404

---

.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/track-pr.yml
.github/workflows/verify-pr.yml
.golangci.yml
.pre-commit-config.yaml
Dockerfile
core/consensus/sniffed_internal_test.go

Updates github workflows to `go1.19.3`
category: misc
ticket: #1366

github: update workflows to go1.19.3

---

app/app.go
app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_test.go
app/eth2wrap/httpwrap.go
app/eth2wrap/synthproposer.go
core/scheduler/scheduler_test.go
go.mod
go.sum

Adds support for deterministic synthetic proposer duties to eth2wrap package.
TODO: add tests and wire in subsequent PRs.
ticket: #1486

app/eth2wrap: support synthetic proposers

---

core/scheduler/metrics.go
core/scheduler/scheduler.go
testutil/compose/static/grafana/dash_charon_overview.json

Clears previous status when validator status changes. For ex: when a validator progresses from `pending_queued` to `active_ongoing`, we currently see two values, one for each status. This PR fixes this by removing the older statuses. In this example, it removes status `pending_queued`.
ticket: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/139

scheduler: clear previous status when validator status changes

---

app/app.go
app/app_test.go
app/featureset/featureset.go
p2p/config.go
p2p/discovery.go
p2p/p2p.go
p2p/ping.go

Adds a new alpha feature called `relay_discovery` which disables discv5, relying purely on relay connections to be upgraded to direct connections via libp2p Indentify protocol that resolves peer direct addresses.
Facts:
- We know which peers we want to connect to (from lock file)
- We know all the nodes in a cluster will use the same bootnode(s)/relay(s) (either Obol-hosted or cluster-hosted).
- We know all the nodes always reserve circuit relays on all configured bootnode/relays.
Connection logic
- Use direct connection if possible
- But if direct connection not possible
- either because peer address unknown 
- or because known addresses do not work
- The try to connect to peer via bootnode relay
- Once connected, libp2p's identify protocol will detect the peers direct address
- Rinse …

p2p: add alpha relay discovery feature

---

app/app.go
app/log/config.go
app/log/loki/batch.go
app/log/loki/client.go
app/log/loki/client_test.go
cmd/bootnode.go
cmd/run.go

Adds lazy loaded cluster labels when pushing logs to loki so we can filter and query by node/cluster/network. 
ticket: #1509

log/loki: lazy loading of cluster labels

---

app/app_test.go

This check was removed in previous refactor so test started flapping again. Re-adding.
category: test
ticket: none

app: fix flapping InfoSync test

---

core/qbft/qbft.go
core/qbft/qbft_internal_test.go

Since some messages are justified, justified rules can be triggered for a future (or a previous) round at any point. So include round when deduping.
category: bug
ticket: #1493

core/qbft: include round when deduping

---

testutil/trackpr/graphql.go
testutil/trackpr/track.go

Automate assigning PR to author when adding to project board to avoid needing to do this manually as per requested process.
category: misc
ticket: none

testutil/trackpr: automate assigning pr to author

---

app/app.go
app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_test.go
app/eth2wrap/httpwrap.go
app/eth2wrap/synthproposer.go
app/eth2wrap/synthproposer_test.go
app/simnet_test.go
cmd/run.go
core/scheduler/scheduler_test.go
docs/configuration.md
testutil/compose/lock.go
testutil/compose/testdata/TestDockerCompose_run_template.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden

Wire synthetic block proposals via the config flag `--synthetic-block-proposals`. Also enable this by default in compose, it replaces beaconmock scheduled deterministic duties.
ticket: #1486

app: wire synthetic block proposals

---

docs/goguidelines.md

Adds canonical slice initialisation to go guidelines.
category: docs
ticket: none

docs: add declartions section to go guidelines

---

core/consensus/component.go
core/consensus/metrics.go

Adds QBFT rounds to decide consensus per duty type gauge.
category: misc
ticket: none

core/consensus: add QBFT decided round gauge

---

app/simnet_test.go

Teku exit docker tests started failing in github CI/CD probably due to changes in latest teku versions which resulted in quicker exits which triggered this race condition.
category: test
ticket: none

app: fix failing teku exits

---

cmd/run.go
docs/configuration.md
p2p/config.go
p2p/p2p.go

Adds a config option to disable libp2p TCP port reuse to test a network issue we are having in GCP.
ticket: none

p2p: add option to disable port reuse

---

app/app_test.go
cmd/bootnode.go
cmd/bootnode/bootnode.go
cmd/bootnode/p2p.go
dkg/dkg_test.go

Enables prometheus metrics in the bootnode.
ticket: #1506

cmd/bootnode: enable prometheus

---

app/app.go
app/app_test.go
core/priority/prioritiser.go
core/priority/prioritiser_test.go

Hardcode peer protocols during infosync test to fix flapping test where one peer didn't think the other peers don't support priority protocol which isn't automatically resolved within the 10s timeout. 
ticket: none

core/priority: fix flapping test

---

.github/workflows/test.yml
app/app_test.go
app/peerinfo/adhoc.go
app/peerinfo/peerinfo.go
app/simnet_test.go
cmd/bootnode/bootnode.go
cmd/bootnode/metrics.go
cmd/bootnode/p2p.go
core/scheduler/scheduler.go
core/validatorapi/router.go
p2p/ping.go
p2p/sender.go
testutil/compose/docker-compose.template
testutil/compose/lock.go
testutil/compose/static/prometheus/prometheus.yml
testutil/compose/testdata/TestDockerCompose_lock_dkg_template.golden
testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_run_template.golden
testutil/compose/testdata/TestDockerCompose_run_yml.golden

Instrument bootnode peer connection count and bandwidth rates via peerinfo protocol to group by cluster hash.
Also added workaround for teku SSZ blocks.
ticket: #1521

cmd/bootnode: instrument peer connections

---

app/app.go
app/eth2wrap/synthproposer.go
core/scheduler/scheduler.go
testutil/validatormock/attest.go
testutil/validatormock/validatormock.go

Always use `head` when querying `validators_by_pubkey` since this is an expensive call and head mitigates against needing to parse and fetch previous state. It also mitigates against errors when querying slots that are too old. Also add TODOs to introduce a cache like Vouch does. Also do this vmock.
ticket: #1486

app/eth2wrap: use validators at head for synthetic blocks

---

cmd/cmd.go
cmd/cmd_internal_test.go

Redacts passwords contained in address flags.
category: bug
ticket: none

cmd: redact address flag passwords

---

core/consensus/component.go
core/consensus/metrics.go
core/consensus/sniffed_internal_test.go
testutil/compose/docker-compose.template
testutil/compose/static/grafana/dash_duty_details.json
testutil/compose/testdata/TestDockerCompose_run_yml.golden

Adds a histogram metric to report consensus duration for each consensus instance.
ticket: #1247

core/consensus: add histogram metric for consensus duration

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/httpwrap.go
app/eth2wrap/synthproposer.go
app/eth2wrap/synthproposer_test.go
core/consensus/component.go
p2p/sender.go

Cache and use correct fee recipients in synthetic blocks.
category: bug
ticket: #1486

app/eth2wrap: use correct fee recipient in synthetic blocks

---

app/qbftdebug.go

Increases sniffed message buffer from 2MB to 20MB since it is too small for block proposals. Downloaded messages never contain duty proposer at this point.
ticket: none

app: increase sniffed message buffer

---

app/qbftdebug.go

Increase to temporary 2GB buffer to ensure we capture the proposer messages. RAM metrics indicate up to 500MB might be possible.
category: test
ticket: none

app: increase sniffed buffer even more

---

app/eth2wrap/synthproposer.go
app/qbftdebug.go

Decrease synthetic block sizes to manageable levels so we can test the logic. We need to refactor the wire protocol to send and duplicate much less.
ticket: none

app/eth2wrap: decrease synth block sizes

---

cmd/createcluster.go
cmd/createcluster_internal_test.go
testutil/compose/lock.go
testutil/compose/testdata/TestDockerCompose_lock_create_template.golden
testutil/compose/testdata/TestDockerCompose_lock_create_yml.golden

Makes the `name` field required in the `charon create cluster` command since clusters without names are hard to debug and monitor.
ticket: none

cmd: require name in create cluster

---

core/consensus/component.go
p2p/receive.go

Adds duration labels to p2p receive errors. Rename consensus specific label to avoid clash.
category: misc
ticket: none

p2p: add duration labels to receive errors

---

testutil/promrated/prom/prometheus.go
testutil/promrated/prometheus.go
testutil/promrated/promrated.go

Start serving prom metrics at the specified address along with a health endpoint to use for a liveness check.
category: misc
ticket: https://github.com/ObolNetwork/charon/issues/1540

testutil/promrated: add health listener and monitoring endpoint

---

app/log/loki/client.go

Increases batch sending timeout to 10s to solve `context deadline exceeded` issue. 
This aligns with official loki client: https://github.com/grafana/loki/blob/main/clients/pkg/promtail/client/config.go#L21
category: misc
ticket: none

app/log: increase loki batch send timeout to 10s

---

cmd/bootnode/bootnode.go
cmd/bootnode/metrics.go
cmd/bootnode/p2p.go

Refactors network bytes metrics into counters (since gauges are sticky and do not reset when peers go away). Adds "active connections" metric.
ticket: none

cmd/bootnode: refactor metrics

---

testutil/promrated/prometheus.go
testutil/promrated/prometheus_internal_test.go
testutil/promrated/promrated.go
testutil/promrated/promrated/main.go
testutil/promrated/testdata/TestGetValidators.golden

Adding in prometheus query to get all the necessary cluster information and associated private keys.
category: misc
ticket: https://github.com/ObolNetwork/charon/issues/1540

testutils/promrated: add prom query to collect pubkey to cluster information

---

app/app.go
app/metrics.go
app/monitoringapi.go
app/monitoringapi_internal_test.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go

Configures monitoringapi to detect all validators queried by VC.
ticket: #1501

app/monitoringapi: detect all validators queried by VC

---

cmd/bootnode/p2p.go

Fixes missing cluster_hash in bootnode metrics.
category: bug 
ticket: none

app/bootnode: fix missing cluster hash in metrics

---

core/dutydb/memory.go
core/dutydb/memory_internal_test.go

Delete expired dutydb queries since they may never be resolved which causes a memory leak.
category: bug
ticket: #978

core/dutydb: delete cancelled queries

---

app/app.go
core/scheduler/scheduler.go
core/scheduler/scheduler_test.go

Delete expired duties from scheduler.
ticket: #1584

core/scheduler: delete expired duties

---

app/metrics.go
app/monitoringapi.go
app/monitoringapi_internal_test.go
core/validatorapi/validatorapi_test.go

Configures monitoringapi to detect all validators queried by VC.
Note: This needs to be tested.
ticket: #1501

app/monitoring: re-enable detect VC feature

---

app/app.go
core/fetcher/fetcher.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_internal_test.go
core/validatorapi/validatorapi_test.go

Improves error message when when VC key share index doesn't match charon index.
ticket: #947

core/validatorapi: improve error

---

core/validatorapi/validatorapi.go

Fixes readyz issues in canary clusters. This is done by moving seenPubkeys logic to getPubShareFunc. In canary clusters such as `canary-goerli-1` it turns out that the nodes reporting value 5 are the ones with lighthouse VC which calls get_validator with validator_index and not pubkey.
category: bug
ticket: #1501

core/validatorapi: fix readyz issues in canary clusters

---

core/fetcher/fetcher.go
core/validatorapi/validatorapi.go

Adds a function to log unexpected fee-recipient for blinded blocks. Also, adds a log to debug capella backwards compatibility tests.
ticket: #1587

core/fetcher: add capella support to verify fee recipient for blinded blocks

---

core/validatorapi/validatorapi.go

Refactors mismatching key shares error to 0-indexed.
ticket: #947

core/validatorapi: refactor to 0-indexed

---

app/app.go
app/app_test.go
app/featureset/featureset.go
cmd/run.go
docs/configuration.md
p2p/config.go
p2p/p2p.go

Deprecate discv5 and enable relay discovery by default as part of future v0.13 release.
ticket: #1606
feature_flag: relay_discovery

cmd: deprecate discv5 and release relay discovery

---

core/validatorapi/validatorapi.go

Fixes readyz issue of `vc missing some validators` by adding seenPubkeys logic to `getPubKeyFunc`.
category: bug
ticket: #1501

core/validatorapi: fix readyz issue

---

core/validatorapi/validatorapi.go

Fix golangci-lint action on main.
ticket: none

core/validatorapi: fix golangci-lint

---

app/eth2wrap/eth2wrap.go

Adds latency metrics for custom eth2wrap endpoints.
category: misc
ticket: none

app/eth2wrap: instrument custom endpoint latency

---

app/app.go
app/monitoringapi_internal_test.go
core/scheduler/scheduler.go
core/scheduler/scheduler_test.go

Fixes issue introduced by #1596 that trimmed data after 5 slots which caused inclusion delay calculation to stop working (it requires duties of 32 ago). Instead just delete duties after 3 epochs (avoid races and off-by-one issues of 2 epochs).
category: bug
ticket: none

core/scheduler: trim duties after 3 epochs

---

dkg/dkg_test.go

Fixes error handling in TestSyncFlow. Refer: https://github.com/ObolNetwork/charon/actions/runs/3882432301/jobs/6622576116
category: test
ticket: none

dkg: fix error handling in TestSyncFlow

---

dkg/dkg_test.go

Fixes golangci-lint on main.
ticket: none

dkg: fix golangci-lint

---

cmd/cmd_internal_test.go
cmd/run.go
docs/configuration.md

Re-adds the previous relay address for backwards compatibility:
- Keep both default relay addresses
- https://0.relay.obol.tech/enr points to new relay-cluster
- http://bootnode.gcp.obol.tech:3640/enr points to the old relay-cluster. 
- Then existing clusters can smoothly upgrade., nodes either use the old relay or both relays
- Note discv5 is still required in relay and v0.13 charon nodes to support direct connections with older versions.
- We can update the old DNS record of http://bootnode.gcp.obol.tech:3640/enr to point to the new relay-cluster at some point if we want. (auto-heal supports this) 
- We can remove the old URL in v0.15 (or when we want to drop support for v0.12 and older)
ticket: none

cmd: re-add previous relay address for backwards compatibility

---

testutil/compose/docker-compose.template
testutil/compose/lock.go
testutil/compose/template.go
testutil/compose/testdata/TestDockerCompose_define_create_template.golden
testutil/compose/testdata/TestDockerCompose_define_dkg_template.golden
testutil/compose/testdata/TestDockerCompose_lock_create_template.golden
testutil/compose/testdata/TestDockerCompose_lock_dkg_template.golden
testutil/compose/testdata/TestDockerCompose_lock_dkg_yml.golden
testutil/compose/testdata/TestDockerCompose_run_template.golden

Sleep for 2 seconds after successful DKG completion to allow other DKGs to complete as well before exitting causing docker-compose to stop all other containers. This fixes shutdown race in compose DKG tests.
category: test
ticket: #1625

testutil/compose: fix dkg shutdown race

---

app/app.go
cmd/relay/p2p.go
cmd/relay/relay.go
cmd/relay/relay_internal_test.go
dkg/dkg.go
p2p/p2p.go
p2p/peer_test.go

Relay serves multiaddrs from http-address server.
ticket: #1632

cmd/relay: serve multiaddrs from http address

---

eth2util/keymanager/keymanager.go
eth2util/keymanager/keymanager_test.go
eth2util/keystore/keystore.go
testutil/random.go

Introduces a new package `eth2util/keymanager` for keymanager api functionalities.
ticket: https://github.com/ObolNetwork/charon/issues/1502

keymanager: api design

---

README.md

Changes the DVL link to the real one, updates to reflect nimbus do have a validator now. 
ticket: none

readme: update readme

---

core/tracker/tracker.go
core/tracker/tracker_internal_test.go

Fixes sync contribution fetcher analysis in tracker for sync message duty. DutySyncMessage is initiated from validatorapi so we need to check for sigagg step and not consensus step.
category: bug
ticket: none

core/tracker: fix sync contribution analysis in tracker for sync message duty

---

eth2util/enr/enr.go
eth2util/enr/enr_test.go

Adds support for encoding and decoding IPs and TCP ports to the ENR package to relays may serve the addresses via ENRs for backwards compatibility.
ticket: none

eth2util/enr: add support for ip and port

---

cmd/createcluster.go
cmd/createcluster_internal_test.go
eth2util/keystore/keystore.go

Refactors create cluster to use the new `keymanager` package.
ticket: #1503

cmd: refactor create cluster to use keymanager package

---

app/monitoringapi_internal_test.go
cmd/relay/relay.go
cmd/relay/relay_internal_test.go
p2p/bootnode.go

Reintroduces the ability for the relay to serve its ID and address via an ENR for backwards compatibility to v0.13 charon nodes.
category: bug
ticket: none

cmd/relay: serve enr

---

core/consensus/component.go
core/interfaces.go
core/sigagg/sigagg.go
core/tracker/tracker2/metrics.go
core/tracker/tracker2/tracker.go
core/tracking.go

Adds refactored tracker logic as tracker2 package in `core/tracker` package.
ticket: #1478

core/tracker2: add tracker2 package

---

cmd/dkg.go
dkg/disk.go
dkg/dkg.go
dkg/dkg_test.go
eth2util/keystore/keystore.go

Adds support for keymanager API to `charon dkg` command.
ticket: #1504

dkg: add keymanager support

---

cmd/createcluster.go

Edits `--keymanager-addresses` flag description for create cluster command.
ticket: #1503

cmd: edit flag description

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/httpwrap.go
app/monitoringapi.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go

Fixes bug in NodePeerCount method.
category: bug
ticket: #1603

eth2wrap: fix node peer count

---

app/k1util/k1util.go
app/k1util/k1util_test.go
go.mod

Adds a `app/k1util` package that will replace the `geth/crypto` package. The aim is to work with underlying `github.com/decred/dcrd/dcrec/secp256k1/v4` types which is aligned with libp2p's way of doing this:
- `k1.PrivateKey` to replace `ecdsa.PrivateKey`
- `k1.PublicKey` to replace `ecdsa.PublicKey`
ticket: #1626

app/k1util: ports geth crypto package helper functions

---

app/app.go
app/disk_internal_test.go
cluster/definition.go
core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
core/validatorapi/teku.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_internal_test.go
core/validatorapi/validatorapi_test.go

Uses multiple fee-recipient addresses from lock introduced in v1.5.
ticket: #1651

core: use multiple fee-recipient addresses

---

eth2util/helpers.go
eth2util/helpers_test.go

Implements ethereum EIP155 address checksum as part of moving away from geth libraries. Also add an`PublicKeyToAddress` function.
ticket: #1626

eth2util: implement checksum address

---

.golangci.yml
app/simnet_test.go
core/bcast/bcast_test.go
core/dutydb/memory.go
core/dutydb/memory_test.go
core/fetcher/fetcher.go
core/fetcher/fetcher_test.go
core/interfaces.go
core/sigagg/sigagg_test.go
core/signeddata.go
core/signeddata_test.go
core/unsigneddata.go
core/validatorapi/router.go
core/validatorapi/router_internal_test.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_test.go
testutil/beaconmock/beaconmock.go
testutil/beaconmock/options.go
testutil/random.go
testutil/validatormock/validatormock.go

Adds imports alias linters.
category: misc
ticket: #1684

golangci: add import alias linter

---

cluster/cluster_internal_test.go
cluster/distvalidator.go
cluster/examples/cluster-definition-003.json
cluster/helpers.go
cluster/helpers_internal_test.go
cluster/lock.go
cluster/ssz.go

Fixes the SSZ issue that didn't ensure `BytesN` are always of length N. This is only included in v1.5 onwards. 
Also removes the lock.DistributedValidator.FeeRecipient field completely, also for previous versions as this isn't used at all and we do not need to support it for older versions.
category: bug
ticket: #1689

cluster: fix SSZ BytesN issue

---

.golangci.yml
app/app.go
app/eth2wrap/genwrap/genwrap.go
cluster/cluster_test.go
cluster/definition.go
cmd/relay/p2p.go
core/bcast/bcast.go
core/dutydb/memory.go
core/fetcher/fetcher_test.go
core/qbft/qbft.go
core/qbft/qbft_internal_test.go
core/tracker/incldelay.go
core/validatorapi/validatorapi.go
dkg/dkg.go
dkg/dkg_test.go
testutil/combine/main.go
testutil/compose/alert.go
testutil/compose/auto.go
testutil/trackpr/track.go
testutil/verifypr/verify.go

We keep on ignoring `gocognit`, rather just disable it.
ticket: none

golangci: disable gocognit lint

---

.github/workflows/golangci-lint.yml
.pre-commit-config.yaml

Remove "only linting new issues" since it only results in some lints being skipped and then the main build failing, rather fail fast and early.
category: misc
ticket: none

golangci: lint everything all the time

---

.golangci.yml
app/log/config.go
app/log/config_internal_test.go
app/log/loki/client.go

Fixes the resulting log `caller` field when using the multilogger (when pushing logs to loki).
Previously all loki logs had the caller: `log/log.go:82`.
category: bug
ticket: none

app/log: fix loki caller

---

cmd/run.go

Logs a warning if a relay with `http` scheme is provided instead of `https`.
ticket: #1637

cmd: add warning if http relay is provided

---

core/scheduler/scheduler.go
core/scheduler/scheduler_test.go

Marks scheduler epoch as resolved when no validators are active. This mitigates errors on new clusters:
```
Emit scheduled slot event: epoch not resolved yet
```
category: bug
ticket: none

core/scheduler: mark epoch as resolve if no validators

---

app/k1util/k1util_test.go
go.mod
go.sum

Finally removes all traces of go-ethereum and the dependency.
ticket: #1698

gomod: remove geth dependency

---

.github/workflows/govulncheck.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/track-pr.yml
.github/workflows/verify-pr.yml
.golangci.yml
.pre-commit-config.yaml
Dockerfile
testutil/promrated/Dockerfile

Mitigates again https://pkg.go.dev/vuln/GO-2022-1143 although we do not use that code.
category: misc
ticket: none

*: update to go v1.19.5

---

Dockerfile
app/log/config.go

Fixes missing error/warn stack traces when logged from docker built binaries. This is due to `formatZapStack` that assumes the source code was located in a `.../charon/` folder when built. Not sure how to fix that properly, so the workaround is to rename the folder used when building the source.  
category: bug
ticket: none

app/log: fix missing stacktraces

---

cmd/relay/relay.go

Include a dummy UDP port when serving relay public address via ENR. This is required by v0.13 that parses it as discv5 bootnode addresses before using it as libp2p relay addresses.
category: bug
ticket: none

cmd/relay: include dummy udp port in ENR

---

.github/workflows/test.yml

Enables cgo when building compose smoke test local binary.
category: misc
ticket: none

github: build compose local binary with cgo

---

testutil/compose/docker-compose.template
testutil/compose/testdata/TestDockerCompose_run_yml.golden

This commit makes jaeger run with an in-memory database rather than Badger.
It also limits the amount of stored traces to 10K.
category: bug
ticket: none

testutil/compose: run jaeger in in-memory mode, limited stored traces

---

Dockerfile

Bring in `ca-certificates` in Docker image, to allow connection to TLS-enabled servers.
category: bug 
ticket: none

Dockerfile: bring in `ca-certificates`

---

testutil/promrated/metrics.go
testutil/promrated/promrated.go
testutil/promrated/promrated/main.go
testutil/promrated/rated.go
testutil/promrated/rated_internal_test.go

Rated recently added authentication and this has been failing silently as the error was just being logged
category: bug
ticket: #1738

testutil/promrated: add metric to count errors from rated api

---

testutil/promrated/rated.go

remove the endpoint from error metric
category: bug
ticket: #1738

testutil/promrated: only report status code

---

app/app.go
app/app_test.go
core/infosync/infosync.go
core/types.go

Includes local proposal type in infosync protocol. Note the output isn't used yet.
ticket: #1652

core/infosync: prioritise proposal types

---

.github/workflows/test.yml
app/app.go
app/featureset/featureset.go
testutil/compose/define.go

This PR adds support for the `herumi_bls` feature flag.
Right now the flag is used in `app/app.go` in preparation for #1744, but apart for that this is 100% dormant code.
I had to update the way we compile binaries for `compose` so that we don't end up with glibc issues between host and Docker.
ticket: #1743

featureset: `herumi_bls` feature flag

---

app/app.go
cluster/definition.go
cmd/createcluster.go
dkg/dkg.go

Verify all withdrawal addresses in `create cluster` command.
ticket: none

cmd: validator all withdrawal addresses

---

app/app.go
app/priorities.go
core/config.go
core/scheduler/scheduler.go
core/scheduler/scheduler_test.go
core/validatorapi/teku.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_internal_test.go
core/validatorapi/validatorapi_test.go
testutil/helpers.go

Introduces `core.BuilderEnabled` that abstracts `app.mutableConfig` which wraps `infosync.Component` such that whether builderAPI is enabled is dynamically based on prioritise results.
ticket: #1652

core: introduce mutable builder enabled config

---

core/sigagg/sigagg.go
core/sigagg/sigagg_test.go
tbls/v2/tblsconv/tblsconv.go

This PR moves `core/sigagg` package to use `tbls/v2` package, which allows us to leverage Herumi BLS.
ticket: #1744 

core/sigagg: refactor to use tbls/v2

---

app/eth2wrap/eth2wrap.go
app/eth2wrap/eth2wrap_gen.go
app/eth2wrap/eth2wrap_test.go
app/eth2wrap/genwrap/genwrap.go
app/eth2wrap/httpwrap.go
app/eth2wrap/lazy.go
app/eth2wrap/synthproposer.go

Wraps eth2clients in a "lazy loader", this allows charon to start even if one or more beacon nodes are down (as long as one is up and available).
ticket: #1312

app/eth2wrap: add lazy init

---

app/priorities.go

Disables mutable BuilderAPI enabled config since VCs do not support dynamically enabling/disabling so manual configuration is always required.
ticket: #1652

app: disable mutable builderAPI config

---

app/app.go
app/metrics.go
app/monitoringapi.go
app/monitoringapi_internal_test.go

Changes VC readyz statuses:
- `vc not connected` indicates no vapi calls
- `vc missing validators` indicates some or all validators not configured in VC 
ticket:  #1612

app: refactor VC readyz checks

---

tbls/v2/herumi/herumi.go
tbls/v2/kryptology/kryptology.go
tbls/v2/tbls.go
tbls/v2/tbls_test.go
tbls/v2/unimplemented.go

We were missing those two important methods, needed for the Charon migration to `tbls/v2`.
ticket: none

tbls/v2: implement FastAggregateVerify and CombineSignatures methods

---

core/eth2signeddata.go
core/eth2signeddata_test.go
core/parsigex/parsigex_test.go
core/validatorapi/validatorapi_test.go
eth2util/signing/signing.go
eth2util/signing/signing_test.go

Kryptology types are still in there, will be refactored later.
ticket: #1744 

ethu2util/signing: refactor to use tbls/v2

---

app/app_test.go
cluster/cluster_test.go
cluster/helpers.go
cluster/helpers_internal_test.go
cluster/lock.go
cluster/test_cluster.go
cmd/createcluster_internal_test.go
core/consensus/component_test.go
dkg/dkg_test.go
p2p/peer_test.go
tbls/v2/tblsconv/tblsconv.go
testutil/combine/main_internal_test.go

Kryptology types are still in there, will be refactored later.
ticket: #1744

cluster: refactor to use tbls/v2

---

app/app.go

Without this commit, lockfile verification would fail with "unimplemented" because tbls/v2 was initialized later.
It's now initialized right after featureset.
category: bug
ticket: none

app: initialize tbls/v2 earlier

---

eth2util/enr/enr.go
eth2util/enr/enr_internal_test.go
testutil/random.go

Adds backwards compatibility in ENR parsing with older versions. Older versions created padded ENRs.
category: bug
ticket: none

eth2util/enr: add backwards compatibility with older versions

---

app/app.go
app/simnet_test.go
cluster/helpers.go
cluster/test_cluster.go
cmd/createcluster.go
cmd/createcluster_internal_test.go
core/eth2signeddata.go
core/eth2signeddata_test.go
core/parsigex/parsigex.go
core/parsigex/parsigex_test.go
core/validatorapi/validatorapi.go
core/validatorapi/validatorapi_internal_test.go
core/validatorapi/validatorapi_test.go
dkg/disk.go
dkg/dkg_test.go
eth2util/deposit/deposit.go
eth2util/deposit/deposit_test.go
eth2util/keymanager/keymanager_test.go
eth2util/keystore/keystore.go
eth2util/keystore/keystore_test.go
eth2util/signing/signing.go
eth2util/signing/signing_test.go
testutil/combine/main.go
testutil/combine/main_internal_test.go
testutil/validatormock/validatormock.go

This PR is bigger than usual because refactoring eth2util had *a lot* of consequences on other parts of the codebase.
The flip side is we got many packages and their respective tests on tbls/v2.
ticket: #1744

eth2util: refactor to use tbls/v2

---

p2p/p2p.go

Adds debug logs to identify invalid `p2p_peer_connection_types` metric values.
category: bug 
ticket: #1790

p2p: adds debug logs for metric issue

---

core/sigagg/sigagg.go
core/sigagg/sigagg_test.go
eth2util/eth2exp/attagg_test.go
tbls/v2/tblsconv/tblsconv.go
tbls/v2/tblsconv/tblsconv_test.go

Added tests to v2 tblsconv, and removed `SigFromBytes` in favor of `SignatureFromBytes`.
Also `SigFromCore` now has bounds checks.
ticket: none

tbls/v2: add tests to tblsconv, small refactors

---

p2p/p2p.go

Refactor `p2p_peer_connection_types` metric, calculating it from scratch periodically instead of stateful approach.
category: bug
ticket: #1790

p2p: fix connection metrics

---

cmd/createcluster.go
cmd/createcluster_internal_test.go

Fixes the issue where during a `create cluster` workflow with more than one distributed validator, only the last key in the pubkey slice was used for them all.
This should fix compose tests 500 errors as well.
category: bug
ticket: none

cmd: rescope distributed validator pubkey during slice iteration

---

cmd/run.go
cmd/run_internal_test.go
docs/configuration.md

Removes deprecated `data-dir` flag from `charon run` command.
ticket: none

cmd: remove deprecated data-dir flag

---

core/validatorapi/router.go
core/validatorapi/router_internal_test.go

Fixes sending incorrect `Content-Type` header in HTTP response. Found this bug while integrating nimbus VC which errored when charon sent `text/plain` instead of `application/json`.
category: bug 
ticket: none

validatorapi: fix content type in http response

---

app/app_test.go
cmd/relay/p2p.go

Fixes issue with relay limits not being applied correctly getting stuck at 256 connections.
category: bug
ticket: none

cmd/relay: fix connection limits
